### ISSUE TITLE
Elastic Search per-replica storage is awkward

### ISSUE THREAD

**Issue by sosiouxme** [openshift/origin-aggregated-logging#101]
This is a tracking issue for future improvements to the current deployment implementation.

The issue is that each instance of Elastic Search requires its own storage volume, but there is no mechanism in current Kubernetes/OpenShift to set up a replica controller that varies parameters or volumes per replica, so multiple replicas could only reuse the same storage volume. Thus for multiple instances of Elastic Search we are required to create multiple deployments, each with a single "replica" so that each can have its own storage. This violates expectations from the rest of the platform and is difficult to manage.

This problem is not specific to aggregated logging; actually just about any clustered storage mechanism is likely to run into it. There is an [upstream proposal to solve this generically](https://github.com/kubernetes/kubernetes/pull/18016). The discussion goes beyond simple storage concerns to cluster parameters or other parameters that may need to vary per instance, specialized deployment hooks, and so forth.

At this time the proposal and design itself is still under heavy debate, with spinoff issues to investigate the requirements of specific cluster implementations. We will add comments to this issue when there are substantive developments in the implementation and implications for logging specifically.

**Comment by lldata** [comment]
Seems like StatefulSets are a part of kubernetes 1.5
http://kubernetes.io/docs/concepts/abstractions/controllers/statefulsets/

**Comment by jcantrill** [comment]
StatefulSets/PetSets have been available in some form or another for awhile know.  We deliberately chose to forgo adoption until they moved out of alpha and the dust has settled.

**Comment by jcantrill** [comment]
closing without prejudice
