### ISSUE TITLE
How can I access elasticsearch API from outside

### ISSUE THREAD

**Issue by RainF930125** [openshift/origin-aggregated-logging#1017]
I want to access elasticsearch API from outside.I follow the guide with 
`$ curl -k -H "Authorization: Bearer $token" -H "X-Proxy-Remote-User: $(oc whoami)" -H "X-Forwarded-For: 127.0.0.1" https://es.example.test/_cat/indices`

and provide every var, but return below respose when I access /_cat/indices

{
"error": {
"root_cause": [
{
"type": "security_exception",
"reason": "no permissions for cluster:monitor/state"
}
],
"type": "security_exception",
"reason": "no permissions for cluster:monitor/state"
},
"status": 403
}

I can access '/_cat/health'.

I used ldap authentication.

**Comment by himmatb** [comment]
Have you try to send logs using logstash from outside of openshift to flush them into openshift elasticsearch to view on kibana ?

**Comment by richm** [comment]
access /_cat/indices is denied - there is an open issue for this I think

**Comment by pruan-rht** [comment]
@richm, other endpoints seem to be denied as well. ` _cat/indices` and `_cat/indices`.  Can you pls paste the link to the opened issue for this bug?   Thanks!

**Comment by pruan-rht** [comment]
@richm, found the [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1548640)
