### ISSUE TITLE
fluentd container does not work with Project Atomic

### ISSUE THREAD

**Issue by danni** [openshift/origin-aggregated-logging#104]
This appears to be a known issue, but I thought it would be nice to have an open bug about it, because it's extremely hard to google for.

The Fluentd container generates SELinux exceptions on Project Atomic. Dan Walsh has written about how to create an SELinux context to allow Fluentd to run: http://www.projectatomic.io/blog/2016/03/selinux-and-docker-part-2/

However, it's not at all clear to me how to generate such a policy on Atomic (i.e. via openshift-ansible) and then make use of it in the fluentd template.

**Comment by richm** [comment]
Could be related to https://github.com/openshift/origin-aggregated-logging/issues/89

**Comment by danni** [comment]
Yep that's it.
