### ISSUE TITLE
Add support for image pull secrets

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#105]
The deployer supports arbitrary prefixes for the logging component images. It would be nice if you could specify an image pull secret, in order to allow them to be hosted on a locked-down external Docker registry.

**Comment by sosiouxme** [comment]
Working on this and non-secured registries too.

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin-aggregated-logging/pull/127

**Comment by ewolinetz** [comment]
#127 has been merged
