### ISSUE TITLE
Improve script to update ViaQ model

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#1054]
We should improve the script `/hack/update-viaq-data-model.sh` to print bold warning if it does not find any files for provided ES version.

Why? I provided ES version `2.2.4` instead of `2.4.4` and it did update only the documentation files. If it yelled at me loudly that no index templates or index patterns were found for this ES version that would helped much.

This is _nice to have_ feature.

**Comment by jcantrill** [comment]
@ewolinetz @t0ffel Does template seeding need to move to the operator?

**Comment by ewolinetz** [comment]
@jcantrill yes, it should belong there, however I think the concern that is being brought up here would still be relevant
