### ISSUE TITLE
Handle kibana-proxy SSL/TLS termination in the router

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#106]
As far as I can tell, there's no real reason to have SSL/TLS termination be handled by the Kibana auth proxy instead of in the OpenShift router. This is especially true since the router image is updated far more often than that of the Kibana auth proxy, which is running on Node.js v0.10.36 with an old version of OpenSSL.

**Comment by sosiouxme** [comment]
You're right, there's no real reason for it to do termination, other than it saves a reencryption at the router. That's probably not a substantial burden. It makes for a more obvious place to update the cert too. It is on my personal to-do list to have the deployer create this reencrypt route.

**Comment by elyscape** [comment]
Is there a real reason to have the auth proxy do SSL/TLS at all? Why not have it just run on HTTP and trust the `X-Forwarded-Proto` header?

**Comment by sosiouxme** [comment]
Because that would leave the internal traffic in cleartext, which would be
vulnerable to internal network taps and such.

**Comment by elyscape** [comment]
Gotcha.

**Comment by sosiouxme** [comment]
The logging deployment now (as of a week or so ago?) creates a reencrypt route, using the key/certificate if supplied or letting the router cert handle it if not. Enjoy!
