### ISSUE TITLE
hardcode for image version for es,curator,kibana components

### ISSUE THREAD

**Issue by chunyunchen** [openshift/origin-aggregated-logging#107]
https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/es.yaml#L43
https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/curator.yaml#L45
https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/kibana.yaml#L45

It's better to use IMAGE_VERSION parameter to specify image tag for above template instead of hardcode.

**Comment by sosiouxme** [comment]
I think I tried it and something about it didn't work. But I need to take another look at this. We need to ensure it's not too hard to deploy a specific version as opposed to "latest".

**Comment by chunyunchen** [comment]
For now, the "latest" tag is not point to the latest image version. Like ES image, the "latest" tag always point to tag "3.1.1-x", but not "3.2.0-x", so if we always use "latest", we should make sure it point to latest image.

Sometimes, we need to specify image tag for a special image, not all images use same tag like "latest".

**Comment by sosiouxme** [comment]
As a short-term fix, you can tag anything you want as "latest" in the imagestream and it will be deployed that way, e.g.:

`oc tag logging-kibana:3.1.1 logging-kibana:latest`

This is obviously not ideal and I'm working on fixing the deployer to put the configured version in the deployments.

**Comment by sosiouxme** [comment]
Fix in Origin. I also built OSE 3.2.0-5 and 3.1.1-13 with the fix; I'm not sure they made it to the QE registry but they should be available from pulp-brew.

**Comment by chunyunchen** [comment]
@sosiouxme I tried with latest images from pulp-brew, the issue is still reproduced, only deployer pod can be used specific image with specifying tag, the kibana/es/fluentd pods still using "latest" tag, please refer to [1].

My test commands with specifying IMAGE_VERSION=3.2.0 as below:

oc process openshift//logging-deployer-template -v ENABLE_OPS_CLUSTER=false,IMAGE_PREFIX={pulp-brew-prefix},KIBANA_HOSTNAME={kibana-route},KIBANA_OPS_HOSTNAME={kibana-ops-route},PUBLIC_MASTER_URL=https://{master-domain}:8443,ES_INSTANCE_RAM=1024M,ES_CLUSTER_SIZE=1,IMAGE_VERSION=3.2.0,MASTER_URL=https://{master-doamin}:8443|oc create -f -

[1] http://fpaste.org/351403/07937414/

**Comment by sosiouxme** [comment]
Hm. Could you `oc describe` one DC, RC, and IS from that deployment?

I'll also retry this when I get a chance.

**Comment by chunyunchen** [comment]
@sosiouxme 
The descriptions for DC, RC and IS,  http://pastebin.test.redhat.com/364183

**Comment by sosiouxme** [comment]
I *think* this is a bug in oc import. https://github.com/openshift/origin/issues/8440 This causes the istag to point at the :latest tag which is passed on to the RC and pod. I'm not sure how to work around this yet.

There was an additional bug in the deployer which was missing putting the correct tag on logging-auth-proxy. I'll fix that.

**Comment by chunyunchen** [comment]
I have added one bug [1] to track the issue [openshift/origin#8440](https://github.com/openshift/origin/issues/8440)

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1325727

**Comment by sosiouxme** [comment]
So the workaround that seems to work is to import individual insecure tags like so:

`oc import-image logging-elasticsearch:3.1.0 --insecure --from brew-pulp-docker01...com:8888/openshift3/logging-elasticsearch:3.1.0`

BTW the insecure annotation doesn't seem to help us much (per https://github.com/openshift/origin/issues/8452) although that usage may well get fixed for 3.2.0.

**Comment by chunyunchen** [comment]
Tried the workaround, get below error:

*$ oc import-image logging-auth-proxy:3.2.0 --insecure=true --from brew-pulp-docker01...com:8888/openshift3/logging-auth-proxy:3.2.0

error: the tag "3.2.0" points to "brew-pulp-docker01...com:8888/openshift3/logging-auth-proxy" - use the 'tag' command if you want to change the source to "brew-pulp-docker01...com:8888/openshift3/logging-auth-proxy:3.2.0"*

**Comment by sosiouxme** [comment]
Yes, sorry for my confusion. The workaround still doesn't work.

**Comment by sosiouxme** [comment]
This, at last, seems to work (after creating the stock IS):

   oc import-image logging-elasticsearch:3.2.0 --from=brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/logging-elasticsearch:3.2.0 --insecure=true

(same for other images of course... specifying the tag in two places. Ugh!)

**Comment by sosiouxme** [comment]
@chunyunchen i think the original issue is solved and we have other issues following the difficulties with non-secure registries - can we cloes this?

**Comment by chunyunchen** [comment]
@sosiouxme I am closing it now. ^^
