### ISSUE TITLE
Cant find Pod of OpenShift

### ISSUE THREAD

**Issue by eitamring** [openshift/origin-aggregated-logging#1078]
Openshift version 3.7
Centos 7
3 masters 
2 Nodes

Hey all ,

I ran the ansible in the following guide :https://github.com/openshift/origin-aggregated-logging/blob/master/docs/quickstart.md

and it finished running with no errors(on any server)
but i cant find any pod related to Kibana or elastic , but the weird thing i can access the Kibana URl i set , but it lead to error that kibana is still raising(two days since i ran the script)

**Comment by richm** [comment]
on the master

oc get project

do you see a logging project?  If so

oc project logging
oc get pods

do you see your logging pods?

**Comment by richm** [comment]
do you have a logging project?

**Comment by richm** [comment]
do you have any resources in the logging project?
oc get dc
oc get ds
oc get secret
oc get cm

**Comment by eitamring** [comment]
No

**Comment by eitamring** [comment]
Yes. 
i got only Secrets

**Comment by eitamring** [comment]
Hey ,
Was a issue with the host file,
Can close!
Thanks for the help @richm

**Comment by bessalahAmar** [comment]
can you please share exctly what was the problem ?  i have the same issue
