### ISSUE TITLE
syslog forwarding on OCP 3.9.14 not working

### ISSUE THREAD

**Issue by chris-milsted** [openshift/origin-aggregated-logging#1079]
I am trying to get syslog working from fluentd on OCP v3.9.14 (OpenShift Enterprise) and I am not seeing any logs being sent. I have tried editing the Daemon Set and I can see that the /etc/fluent/config.d/dynamic file is being created BUT I am not seeing the include statement in the /etc/fluent/fluent.conf file being updated to pickup this new config file which I am wondering is the cause of this. Please see below for the steps I have taken:

OK - did an oc edit ds

```
    spec:
      containers:
      - env:
        - name: USE_REMOTE_SYSLOG
          value: "false"
        - name: REMOTE_SYSLOG_HOST
          value: 10.60.0.60
```

Then I logged into the container and the fluent.conf reads:

```
# cat fluent.conf
# This file is the fluentd configuration entrypoint. Edit with care.

@include configs.d/openshift/system.conf

# In each section below, pre- and post- includes don't include anything initially;
# they exist to enable future additions to openshift conf as needed.

## sources
## ordered so that syslog always runs last...
@include configs.d/openshift/input-pre-*.conf
@include configs.d/dynamic/input-docker-*.conf
@include configs.d/dynamic/input-syslog-*.conf
@include configs.d/openshift/input-post-*.conf
##

<label @INGRESS>
## filters
  @include configs.d/openshift/filter-pre-*.conf
  @include configs.d/openshift/filter-retag-journal.conf
  @include configs.d/openshift/filter-k8s-meta.conf
  @include configs.d/openshift/filter-kibana-transform.conf
  @include configs.d/openshift/filter-k8s-flatten-hash.conf
  @include configs.d/openshift/filter-k8s-record-transform.conf
  @include configs.d/openshift/filter-syslog-record-transform.conf
  @include configs.d/openshift/filter-viaq-data-model.conf
  @include configs.d/openshift/filter-post-*.conf
##
</label>

<label @OUTPUT>
## matches
  @include configs.d/openshift/output-pre-*.conf
  @include configs.d/openshift/output-operations.conf
  @include configs.d/openshift/output-applications.conf
  # no post - applications.conf matches everything left
##
</label>

```

NOTE in the /etc/fluent/configs.d/dynamic

We only have the following files:

# ls -lr
total 4
-rw-r--r--. 1 root root 262 Apr 12 18:40 input-docker-default-docker.conf

Notice there is no output syslog file....

############

Update Daemon Set:

```
    spec:
      containers:
      - env:
        - name: USE_REMOTE_SYSLOG
          value: "true"
        - name: REMOTE_SYSLOG_HOST
          value: 10.60.0.60
```

```
# cat fluent.conf
# This file is the fluentd configuration entrypoint. Edit with care.

@include configs.d/openshift/system.conf

# In each section below, pre- and post- includes don't include anything initially;
# they exist to enable future additions to openshift conf as needed.

## sources
## ordered so that syslog always runs last...
@include configs.d/openshift/input-pre-*.conf
@include configs.d/dynamic/input-docker-*.conf
@include configs.d/dynamic/input-syslog-*.conf
@include configs.d/openshift/input-post-*.conf
##

<label @INGRESS>
## filters
  @include configs.d/openshift/filter-pre-*.conf
  @include configs.d/openshift/filter-retag-journal.conf
  @include configs.d/openshift/filter-k8s-meta.conf
  @include configs.d/openshift/filter-kibana-transform.conf
  @include configs.d/openshift/filter-k8s-flatten-hash.conf
  @include configs.d/openshift/filter-k8s-record-transform.conf
  @include configs.d/openshift/filter-syslog-record-transform.conf
  @include configs.d/openshift/filter-viaq-data-model.conf
  @include configs.d/openshift/filter-post-*.conf
##
</label>

<label @OUTPUT>
## matches
  @include configs.d/openshift/output-pre-*.conf
  @include configs.d/openshift/output-operations.conf
  @include configs.d/openshift/output-applications.conf
  # no post - applications.conf matches everything left
##
</label>
```

BUT there is NO include here for the OUTPUT rule to pickup the file I can see below…

When I look in /etc/fluent/configs.d/dynamic

```
# ls -lrt
total 8
-rw-r--r--. 1 root root 262 Apr 12 18:48 input-docker-default-docker.conf
**-rw-r--r--. 1 root root 191 Apr 12 18:48 output-remote-syslog.conf**
```

BUT the fluent.conf is not being updated?

**# oc version
oc v3.9.14
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ivy-oscp.demolab.local:8443
openshift v3.9.14
kubernetes v1.9.1+a0ce1bc657**

So I am not seeing any syslog output on the remote server…..

NB I have tested sysylog by sending messages using logger and this is working so I know syslog and the rsyslog receiver is working OK.

Looking at the code we seem to generate the file here:

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/generate_syslog_config.rb

But I am not sure we will ever pick it up as there is not reference to the file in the fluent.conf output rules for some reason.

```
<label @OUTPUT>
## matches
  @include configs.d/openshift/output-pre-*.conf
  @include configs.d/openshift/output-operations.conf
  @include configs.d/openshift/output-applications.conf
  # no post - applications.conf matches everything left
##
</label>
```

**Comment by chris-milsted** [comment]
Hi Rich,

So I think I figured out what changed and why the logs stopped, which has me a little bit confused.

It seems that in 3.9 the default logging level is Debug (I am sure I saw some logs in 3.7 which had a severity of info by default?). I tested this with the configuration to dump the config file as you described above and indeed I see:

```
      <store>
        @type syslog_buffered
        remote_syslog 10.60.0.60
        port 514
        hostname logging-fluentd-9hrzt
        facility local0
        severity debug
      </store>
```
In the config file.

So I updated my rsyslog to accept *.debug and sure enough I now see logs.

This aligns with the current documentation so I assume this is working as designed - I will make sure I update the variable to also set the severity as I am sure I never had to do that pre-3.9 to make it come through as info.

I was also looking at the BZ below which has a line that states:

        severity - configured value in output-remote-syslog.conf is set.
                   'info' by default

As a follow up:

I was hoping that with BZ1515715 that the syslog would stamp the messages with the namespace and pod name so we could do some intelligent syslog filtering to put each namespace log into a separate file. However on the 3.9.14 version I see logs like:

Apr 17 07:24:43 logging-fluentd-9hrzt output_tag: <log payload>

Where it is being stamped with the fluentd logging pod name and the payload - but not the source pod or namespace.

It looks like BZ1515715 is targetted at 3.9.Z so I am assuming this will drop into a future 3.9 maintenance release?

Thanks for the pointers on the debugging,

**Comment by richm** [comment]
@nhosoi Are you working on the bz for remote syslog?

**Comment by nhosoi** [comment]
@richm, bz1515715 is in the post status.  The upstream pr/955 is merged into the master and release-3.9 branches.

@chris-milsted,
> However on the 3.9.14 version ...

Right.  The patch has not been included in the downstream build yet.

> It looks like BZ1515715 is targetted at 3.9.Z so I am assuming this will drop into a future 3.9 maintenance release?

 Yes, that's our plan.

**Comment by chris-milsted** [comment]
OK - that's great.

Will keep an eye on the BZ and retest when it releases.

Thanks for the help and happy with syslog forwarding testing to date.

Chris

**Comment by portante** [comment]
What problem are you trying to solve by this approach?

**Comment by chris-milsted** [comment]
Hi Peter,

The approach was just to store logs, I was thinking that if we could use rsyslog filters, we could write one log file per namespace and just create a store-forward for the logs.

This would avoid using elastic entirely and then I could give different users access to their own log files and let them Grep for events.

https://www.rsyslog.com/doc/v8-stable/configuration/filters.html

I am trying to come up with an alternative log path, that just captures the logs and writes them to a file per namespace which should be much lower disk I/O requirement and memory requirement than Elastic is today.

Thanks

Chris

**Comment by portante** [comment]
They have that today, with oc logs, no?  Just increase the storage for docker/CRI-O per container and do "`oc logs | grep foo`", right?

Aggregated logging is about bring all logs in a namespace together to make them searchable, giving them the ability to perform visualizations on them to distill patterns and behaviors from the volume of data, making them consumable.  It is not designed to be a log file storage system.

It is also about bring together all namespaces and operational logs so that when one has to debug the whole system the necessary data can be correlated.

The performance issues seen so far are really about fluentd's inability to keep up and bad behaviors of fluentd causing Elasticsearch to twist and turn as if under a thumb screw.  =)

**Comment by gunjan-miglani** [comment]
> They have that today, with oc logs, no? Just increase the storage for docker/CRI-O per container and do "`oc logs | grep foo`", right?
> 
> Aggregated logging is about bring all logs in a namespace together to make them searchable, giving them the ability to perform visualizations on them to distill patterns and behaviors from the volume of data, making them consumable. It is not designed to be a log file storage system.
> 
> It is also about bring together all namespaces and operational logs so that when one has to debug the whole system the necessary data can be correlated.
> 
> The performance issues seen so far are really about fluentd's inability to keep up and bad behaviors of fluentd causing Elasticsearch to twist and turn as if under a thumb screw. =)

Hi Peter, I just came across above comment and its good that openshift logs them per project/namespace. I have a case specific query here - I want logs from one namespace to be parsed based on a field and then go to different index in es. Is there any such facility/refernces to implement that in openshift.?

**Comment by jcantrill** [comment]
> > They have that today, with oc logs, no? Just increase the storage for docker/CRI-O per container and do "`oc logs | grep foo`", right?
> > Aggregated logging is about bring all logs in a namespace together to make them searchable, giving them the ability to perform visualizations on them to distill patterns and behaviors from the volume of data, making them consumable. It is not designed to be a log file storage system.
> > It is also about bring together all namespaces and operational logs so that when one has to debug the whole system the necessary data can be correlated.
> > The performance issues seen so far are really about fluentd's inability to keep up and bad behaviors of fluentd causing Elasticsearch to twist and turn as if under a thumb screw. =)
> 
> Hi Peter, I just came across above comment and its good that openshift logs them per project/namespace. I have a case specific query here - I want logs from one namespace to be parsed based on a field and then go to different index in es. Is there any such facility/refernces to implement that in openshift.?

There is not.  You will need to hack together your own collector configuration and ES permissions scheme.  OCP logging is not intended to be a general purpose ES deployment and is opinionated about the data schema

**Comment by gunjan-miglani** [comment]
I second that thought but on the other hand if I could say filter error
logs and info logs from app and then send them to different indices in Es
hence not over filling project index and making it easy for developers...
we should have ability to add say another error.output_tag and then may be
set another viaq index name for it... right now whatever output tag I
create, it always send all the logs to project index!!!

Any idea how can I have another elastic output plugin for that new tag??

Thanks for your reply. Really appreciate it!!!

Gunjan

**Comment by richm** [comment]
@gunjan-miglani  https://richm.github.io/how-to-send-app-logs-to-external-and-ops-to-internal
