### ISSUE TITLE
Decide on a proper name for the deployer

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#108]
Should it be deployer or deployment:

origin-logging-deployment

metrics calls it:

openshift/origin-metrics-deployer

**Comment by sosiouxme** [comment]
It should be "deployer". It's just an accident that it's "deployment" in a few places. However it's a bit of a pain to fix it... particularly the enterprise image names.

**Comment by jcantrill** [comment]
@sosiouxme is this resolved by 61e3970b14b9e52360b67ae8669d0923a18330b1 or is there additional tasks like renaming the image?

**Comment by sosiouxme** [comment]
That only changes the source. The name of the image hasn't been changed
yet. I stopped short of that because I'm not sure how hard it'll be to
match for enterprise. Honestly though it probably won't be hard.

**Comment by jcantrill** [comment]
@sosiouxme @ewolinetz did we update the image name too? since my last question?

**Comment by sosiouxme** [comment]
I made it so we're building images with both names in origin. Once the
"deployer" image actually exists I'll switch the template to refer to that.
OSE 3.3 has this change as well.
