### ISSUE TITLE
Failed to initialize Reverse Proxy: certificate authority file (/etc/elasticsearch/secret/admin-ca) could not be read - open /etc/elasticsearch/secret/admin-ca: no such file or directory

### ISSUE THREAD

**Issue by ghost** [openshift/origin-aggregated-logging#1085]
Openshift version 3.7
Centos 7
3 masters
2 Nodes

Hey all ,

I ran the ansible in the following guide :https://github.com/openshift/origin-aggregated-logging/blob/master/docs/quickstart.md

and it finished running with no errors(on any server)
all the pods went up correctly except for the ES-data , i can see the following error "Failed to initialize Reverse Proxy: certificate authority file (/etc/elasticsearch/secret/admin-ca) could not be read - open /etc/elasticsearch/secret/admin-ca: no such file or directory"

**Comment by richm** [comment]
@eitamring where do you see that error?
