### ISSUE TITLE
"error: couldn't read version from server: Get https://kubernetes.default.svc.cluster.local/api: dial tcp: lookup kubernetes.default.svc.cluster.local: no such host" in logging-deployer Pod

### ISSUE THREAD

**Issue by chunyunchen** [openshift/origin-aggregated-logging#11]
Met "error: couldn't read version from server: Get https://kubernetes.default.svc.cluster.local/api: dial tcp: lookup kubernetes.default.svc.cluster.local: no such host" in logging-deployer Pod.

Steps to Reproduce:
1. Log into OSE env
2. Create a project named "chunpj"
3. Create the Deployer Secret
oc secrets new logging-deployer nothing=/dev/null
4. Create the Deployer ServiceAccount
oc create -f - <<API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-deployer
secrets:
\- name: logging-deployer
API

oc policy add-role-to-user edit \
          system:serviceaccount:chunpj:logging-deployer
5. Run the Deployer
oc process -f https://raw.githubusercontent.com/openshift/origin-aggregated-logging/master/deployment/deployer.yaml -v IMAGE_PREFIX=\<rcm-img-docker01_REGISTRY\>/openshift3/,KIBANA_HOSTNAME=kibana.example.com,PUBLIC_MASTER_URL=https://\<OSE_MASTER\>:8443,ES_INSTANCE_RAM=1024M,ES_CLUSTER_SIZE=1 | oc create -f -
6. Check the logging-deployer's logs, please refer to the detail logs from this gist: https://gist.github.com/chunyunchen/19122b09b62cc178af2d

**Comment by jcantrill** [comment]
closed in favor of https://bugzilla.redhat.com/show_bug.cgi?id=1272908
