### ISSUE TITLE
Required filtered audit logs and more plugins in 3.6v 

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1141]
Current Configuration:
OC version: v3.6.173.0.113 
logging images v3.6 

In coming future we are not planning to upgrade our opesnshift cluster as live application are running on prod.
I got requirement for sending logs to HDFS/SIEM and more filtered Audit logs, i could see this were added in release 3.7v,3.8v, 3.9v.

Can i build my own Fluentd image to get all these feature and which should not effect other EFK component images and other images.

at least if i can get filterd audit logs, if i could upgrade to 3.7v fluentd configuration.  
It seems all logging images are tightly coupled with openshift cluster version. i need workaround to upgrade only fluentd images with my customization. 
  
Please help me with solution.. I desperately wanted to customize get all updated feature.

Thanks in advance.

**Comment by josefkarasek** [comment]
You can set your `FROM` instruction in your custom fluentd Dockerfile to follow specific releases.
E.g. v3.9 etc..

**Comment by jcantrill** [comment]
You may just be able to pull the 3.7 image and use it since the stack is relatively the same from 3.6->3.9.  Note this is not supported configuration so use at your own risk.

**Comment by himmatb** [comment]
Currently as you suggested we can use logging fluentd images from 3.6 to 3.9 logging images. accordingly  I have updated logging fluentd image from 3.6 to 3.9 successfully without any error. As i need specially audit related logs like need to extract all the keys like auid, pid, user, ops, ip, result etc...

I could see its 3.9 version for aggregator deployed, its using **viaq_docker_audit** plugin as a format in below fluentd conf file but i couldn't able see all the key's extracted and mapped  in kibana to have better visualization and better formatted/structured logs so i can create specific dashboards for have successful login as particular user and disallowed login with proper IP from which user trying to login.

<source>
  @type tail
  @id audit-input
  @label @INGRESS
  path "#{ENV['AUDIT_FILE'] || '/var/log/audit/audit.log'}"
  pos_file "#{ENV['AUDIT_POS_FILE'] || '/var/log/audit/audit.log.pos'}"
  tag audit.log
  format viaq_docker_audit
</source>

please help me on the same.

**Comment by richm** [comment]
The audit log parser in openshift logging is only for the very specific case of auditing "container" events e.g. container created, started, stopped, deleted. It is not a general purpose audit log parser (which carries with it many security risks).

**Comment by himmatb** [comment]
I have written filters specific to security logs but use login and other things .. i want to add in this in our 3.9 images and it should be part of .operation index .. how can i make this possible .. its very tricky for me i tried couple of things but its failing .. can you please help me with solution .

we have deployed microservices in production in openshift getting raw stdout logs.... i want to write filter for particular project logs and extract specific required fields to make more visualize on kibana . please help me with steps or if you have any specific document or sample file which is achieving same things please share steps or documents for only one use case so i will do for rest of projects..

**Comment by richm** [comment]
What have you tried so far?  please share your configs

**Comment by himmatb** [comment]
Using 3.9v images, I am trying to install plugin to work with customize fluentd configuration file.  
Below Docker file file try to build but end up with error: - 

FROM registry.access.redhat.com/openshift3/logging-fluentd:v3.9

RUN  gem install fluent-plugin-grok-parser

ADD input-pre-secure.conf /etc/fluent/config.d/
----------------------------------------------------------------------
ERROR:  Error installing fluent-plugin-grok-parser:
        serverengine requires Ruby version >= 2.1.0.

Please help me on this , i Know it will very question i am asking ..even not able to find out the way to start customizing image using 3.9v .. Its really showstopper for me to proceed further.

**Comment by richm** [comment]
https://rubygems.org/gems/fluent-plugin-grok-parser/versions - you'll have to use a version that supports fluentd 0.12

**Comment by himmatb** [comment]
Thanks @richm its build successfully.

I have written grok filter in configuration file like below. 

<source>
  @type tail
  @id audit-input
  @label @INGRESS
  path /var/log/secure
  pos_file /var/log/secure.log.pos
  tag audit.log
  <parse>
    @type grok
     <grok>
        pattern %{DATA:Type} for invalid user %{DATA:User} from %{IP:IpAddress} port %{DATA:port %{GREEDYDATA:SSH2}
     </grok>
 so on......

 What all configuration changes require to update in Docker file to get all security realated logs in particular operation index or any other namespace index.

Please suggest next step to proceed further..

**Comment by himmatb** [comment]
Thanks a Lot for your help @richm .. 
I will try this tomorrow and get in touch with you if i will face any issue. 

How fluentd will identify that it has to send logs to specific operation index .. do we need to mention any specific tag.. 
Suppose i have create new namespace named as "security" then I need to specify tag as below in my fluentd configuration file . 

``` 
<source>
  @type tail
  @id secure-input
  @label @INGRESS
  path /var/log/secure
  pos_file /var/log/secure.log.pos
  tag security.xxx.xx
</source> 
```
and in  filter section 
``` 
<filter security.xxx.xx >
  ---
  ---
</filter>
```

 .....  will it send logs to security index automatically .

Is this the actual concept of sending logs to Elasticsearch?  Please Correct me if  i am wrong.

**Comment by himmatb** [comment]
As suggested by you i have created below configuration files to get security logs and push them to elasticsearch .. 
Below is my input-pre-secure.conf
```
<source>
@type tail
@label @INGRESS
@id secure-input
path /var/log/secure*
read_from_head true
pos_file /var/log/secure.log.pos
tag audit.log
format none
</source>
```
and filter-pre-secure.conf
```
<filter audit.log>
@type parser
key_name message
format grok
#<parse>
#@type grok
#       Invalid username/Failed password/Accepted password
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: (?<EventType>%{WORD} %{WORD}) (?<USERNAME>%{WORD}) from %{IP:src_ip} port %{BASE10NUM:port}
</grok>
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: %{DATA:EventType} for %{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port} ssh2
</grok>
#</parse>
</filter>
```
Dockerfile: 

```
FROM registry.access.redhat.com/openshift3/logging-fluentd:v3.9

COPY fluent-plugin-grok-parser-1.0.1.gem .
RUN gem install fluent-plugin-grok-parser-1.0.1.gem
COPY input-pre-secure.conf /etc/fluent/configs.d/openshift/
COPY filter-pre-secure.conf /etc/fluent/configs.d/openshift/
```
I have deployed new logging images to aggregator and fluentd daemonset but i endup with below mentioned error .. please help !!

config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"  

2018-05-17 14:58:00 +0400 [info]: reading config file path="/etc/fluent/fluent.conf"
--
  | 2018-05-17 14:58:01 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [error]: config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"
