### ISSUE TITLE
Facing issue with customizing logging-image version v3.9  

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1172]
@richm I am just creating new issue regarding customizing of  existing logging images version 3.9 for our customize needs to get security logs...
As suggested by you i have created below configuration files to get security logs and push them to elasticsearch ..
Below is my input-pre-secure.conf
```
<source>
@type tail
@label @INGRESS
@id secure-input
path /var/log/secure*
read_from_head true
pos_file /var/log/secure.log.pos
tag audit.log
format none
</source>
```
and filter-pre-secure.conf
```
<filter audit.log>
@type parser
key_name message
format grok
#<parse>
#@type grok
#       Invalid username/Failed password/Accepted password
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: (?<EventType>%{WORD} %{WORD}) (?<USERNAME>%{WORD}) from %{IP:src_ip} port %{BASE10NUM:port}
</grok>
<grok>
        pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: %{DATA:EventType} for %{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port} ssh2
</grok>
#</parse>
</filter>
```
Dockerfile:
```
FROM registry.access.redhat.com/openshift3/logging-fluentd:v3.9

COPY fluent-plugin-grok-parser-1.0.1.gem .
RUN gem install fluent-plugin-grok-parser-1.0.1.gem
COPY input-pre-secure.conf /etc/fluent/configs.d/openshift/
COPY filter-pre-secure.conf /etc/fluent/configs.d/openshift/
```
I have deployed new logging images to aggregator and fluentd daemonset but i endup with below mentioned error .. please help !!

config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

2018-05-17 14:58:00 +0400 [info]: reading config file path="/etc/fluent/fluent.conf"
  | 2018-05-17 14:58:01 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
  | 2018-05-17 14:58:02 +0400 [error]: config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

I have tried above configuration in my local environment its working perfect but while i am adding above configuration with docker images i am facing issue and getting above error.

**Comment by richm** [comment]
> config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

not sure what the problem is - maybe the fluentd forum can help you here

**Comment by himmatb** [comment]
I am not sure who has develop this image Please assign or tag here someone who can help me to customize images for using in openshift .. I really need this to be done !!
Our stack is running on production but we got additional requirement from security related stuff .. as we are very big bank organization security is main concern for us.. we want to implement this solution for accross organization which as a centralizing  logging for all. 

Please help me @richm !! You helped me lot till date and I have lots of hopes on you to resolve this !!

**Comment by josefkarasek** [comment]
@himmatb you're supplying a logstash configuration to fluentd. Those are two different components and their configuration is not interchangeable.

Check how the `format` parameter is [used for fluentd](https://docs.fluentd.org/v0.12/articles/filter_parser)

**Comment by himmatb** [comment]
Its clearly mention in below fluentd documentation that we can use ``` format grok ```   
and parser plugin also supports 3rd party grok plugin [look at this](https://docs.fluentd.org/v0.12/articles/parser-plugin-overview)
Den i downloaded below plugin and install on logging image to get this functionality 
[see this](https://github.com/fluent/fluent-plugin-grok-parser) 

I tried in local vm environment before implement on docker to test this fluentd configuration and its worked ..

**Comment by himmatb** [comment]
@josefkarasek I have cross checked configuration which you have suggested to use is for fluentd > 0.12v .

**Comment by richm** [comment]
> Please help me @richm !! You helped me lot till date and I have lots of hopes on you to resolve this !!

I don't know where this error is coming from:

> config error file="/etc/fluent/fluent.conf" error="'format' parameter is required"

You say you tested the exact same configuration outside of the container environment and it worked fine.  AFAICT, this doesn't appear to be a problem with openshift logging or the image.  That is why I suggested that you ask your question in a fluentd forum - perhaps they could help you in debugging.

Another thing - it is perfectly fine to open issues if you have found a bug in the code, or if you have an idea for an enhancement to the product.  The issue tracker is not a good place for an extended question and answer conversation.

In the future, if you have questions about how to do something, please use users@lists.openshift.redhat.com - put `[logging]` in the subject.  That will also make your questions available to a wider audience, and share the answers more broadly.

**Comment by himmatb** [comment]
Hi Team,
Finally i have mange to make mux container running but i got some warning and above filter part is not working at all .. i think its issue with filter_viaq_data_model.rb plugin.   
 Please find below error: 

2018-05-20 10:25:45 +0400 [warn]: dump an error event: error_class=TypeError error="no implicit conversion of nil into String" location="/usr/share/gems/gems/fluent-plugin-viaq_data_model-0.0.13/lib/fluent/plugin/filter_viaq_data_model.rb:413:in `parse'" tag="audit.log.raw" time=1526797545 record={"message"=>"May 20 10:22:54 lopnshft2d sudo:    root : TTY=pts/1 ; PWD=/opt/logging ; USER=root ; COMMAND=/bin/oc edit ds/logging-fluentd", "pipeline_metadata"=>{"normalizer"=>{"ipaddr4"=>"10.128.0.40", "ipaddr6"=>"fe80::858:aff:fe80:28", "inputname"=>"fluent-plugin-systemd", "name"=>"fluentd", "received_at"=>"2018-05-20T06:25:45.904674+00:00", "version"=>"0.12.42 1.6.0"}}}

filter-pre-secure.conf
```
<filter *audit.log*>
    @type parser
    key_name message
    format grok
   # <parse>
   #     @type grok
        <grok>
            pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: (?<EventType>%{WORD} %{WORD}) (?<USERNAME>%{WORD}) from %{IP:src_ip} port %{BASE10NUM:port}
        </grok>
        <grok>
            pattern (?<timestamp>%{WORD} %{DATA} %{TIME}) %{HOSTNAME:host_target} sshd\[%{BASE10NUM}\]: %{DATA:EventType} for %{USERNAME:username} from %{IP:src_ip} port %{BASE10NUM:port} ssh2
        </grok>
   # </parse>
</filter>
```

**Comment by jcantrill** [comment]
Looks like your incoming record no longer has the '@timestamp' field in the record [1] which is hte default it is expecting.  Time value is required.

[1] https://github.com/ViaQ/fluent-plugin-viaq_data_model/blob/master/lib/fluent/plugin/filter_viaq_data_model.rb#L413

**Comment by himmatb** [comment]
Can you please explain how to add this Time Value with above configuration...

**Comment by richm** [comment]
> Can you please explain how to add this Time Value with above configuration...

You should completely bypass this code, as I have described in the email to the openshift users email list.
