### ISSUE TITLE
Remove mapper.allow_dots_in_name settings for ES 5.x

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#1188]
I think we should remove (_cleanup_) the setting from Docker file(s):
```
ES_JAVA_OPTS="-Dmapper.allow_dots_in_name=true"
```
It is supported OOB in ES 5.x and later.

Some references:
- <https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html>
- <https://discuss.elastic.co/t/is-there-a-way-to-allow-dots-in-the-fieldname/90134>

Thoughts?

**Comment by jcantrill** [comment]
Sure. Make it so

-- 
--
Jeff Cantrill
Senior Software Engineer, Red Hat Engineering
OpenShift Integration Services
Red Hat, Inc.
*Office*: 703-748-4420 | 866-546-8970 ext. 8162420
jcantril@redhat.com
http://www.redhat.com
