### ISSUE TITLE
Using truststore and keystore for logstash server to send logs to elasticsearch...

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1191]
Hi Team,

I have deployed rabbitmq, logstash server on openshift to make another ELK pipeline for logging which supports some set of application and want to forward logs from those application logs through ELK pipeline but Elasticsearch will be the common For both EFK/ELK pipeline.
   
I have below secrets on openshift logging-elasticsearch :   
```
logging-elasticsearch created 3 months ago
Opaque Reveal Secret
admin-ca
*****
admin-cert
*****
admin-key
*****
admin.jks
*****
key
*****
searchguard.key
*****
searchguard.truststore
*****
truststore
*****
```

--------------------------------------------------------

I have grabbed truststore key using below command and used truststore_password => tspass from elasticsaerch.yml : 
```
sudo oc get secret logging-elasticsearch --template='{{index .data "truststore"}}' | base64 -d > truststore.jks
```

Please help me with procedure i need to follow if i want to connect using truststore keys,username,password for truststore. 

Below is logstash.conf file :  : 

```
input {
  rabbitmq {
    host => "rabbitmq-logstash"
        queue => "logstash"
        durable => true
        port => 5672
        user => "admin"
        password => "admin"
}
}
output {
  elasticsearch {
    hosts => ["logging-es:9200"]
    #cacert => '/etc/logstash/conf.d/keys/es-ca.crt'
    #user => 'fluentd'
    #password => 'changeme'
    ssl => true
    ssl_certificate_verification => false
    truststore => "/etc/logstash/conf.d/keys/truststore.jks"
    truststore_password => tspass
    index => "logstash-%{+YYYY.MM.dd}"
    manage_template => false
    document_type => "%{[@metadata][type]}"
   }
  stdout { codec => rubydebug }
}
```
I am facing below error:

10:51:56.154 [Ruby-0-Thread-5: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:228] WARN  logstash.outputs.elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://logging-es:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'https://logging-es:9200/'"}
 10:52:01.155 [Ruby-0-Thread-5: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:228] INFO  logstash.outputs.elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://logging-es:9200/, :path=>"/"}
  | 10:52:01.158 [Ruby-0-Thread-5: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.4.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:228] WARN  logstash.outputs.elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://logging-es:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'https://logging-es:9200/'"}

Please help me with correct configuration.

**Comment by jcantrill** [comment]
You are trying to contact Elasticsearch in the same way that fluentd does so I would extract the logging-fluentd secret and add it to a java keystore.  This will provide you with the same set of credentials.  The keystore referenced here may only contain the CA certificate; i'm not sure if and when we changed that.  @ewolinetz ?

**Comment by ewolinetz** [comment]
We have mutual auth configured for the provided Elasticsearch image, so as @jcantrill said you will want to pull the client key/certs/ca from the logging-fluentd secret and configure logstash to provide them.

**Comment by himmatb** [comment]
If you see in above configuration file commented part.. I have tried to use fluend ca certificate but it didn't worked for me.. So i thought to use truststore key to make connection.. 
Both cases i got same error. 
I will try again tomorrow.. 

What would be usename /password I have to provide if i need those in configuration.

How can we customize all these certificates, so i can use my company certificate as it seems all certificates are auto generated..
Please share link if anywhere documentated!!

FYI.. rabbitmq and logstash server are running in pod..

**Comment by ewolinetz** [comment]
@himmatb You need to also provide to Elasticsearch (from Logstash) a client cert and client key. 

In your example you are pulling from the secret `logging-elasticsearch` for building your truststore (this should be alright though since its created from the same CA that signed the other keys).

This Fluentd Elasticsearch output plugin that we provide: https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/output-es-config.conf

We don't appear to have documentation, nor a way to allow you to specify a CA key to use for signing via a variable, however this where the logic for generating our keys/certs [1] in theory if you provide those files at `{{ generated_certs_dir}}` which should resolve to something like `/etc/origin/logging` on the first node in your master group (within your inventory) then it should use that instead for building the secrets for the different components.

[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging/tasks/generate_certs.yaml

**Comment by himmatb** [comment]
I have literally try all the option to make connection b/w logstash and elasticsearch. 

https://docs.search-guard.com/latest/logstash , This document clearly states to use truststore and its pretty straight forward to use but not sure about username/password so i just use fluentd/changeme.

As you suggested, I have extracted ca.crt from logging-fluentd secret and try to use with username/password and without username/password :
```
sudo oc get secret logging-fluentd --template='{{index .data "ca"}}' | base64 -d > ca.crt
```

```
output {
  elasticsearch {
    hosts => ["logging-es:9200"]
    cacert => '/etc/logstash/conf.d/keys/ca.crt'
    #user => 'fluentd'
    #password => 'changeme'
    ssl => true
    ssl_certificate_verification => false
    index => "logstash-%{+YYYY.MM.dd}"
    manage_template => false
    document_type => "%{[@metadata][type]}"
   }
  stdout { codec => rubydebug }
}
```
I tried to use with truststore keys with below configuration : 

```
output {
  elasticsearch {
    hosts => ["logging-es:9200"]
    user => 'fluentd'
    password => 'changeme'
    ssl => false
    ssl_certificate_verification => false
    truststore => "/etc/logstash/conf.d/keys/searchguard.truststore.jks"
    truststore_password => tspass
    index => "logstash-%{+YYYY.MM.dd}"
    manage_template => false
    document_type => "%{[@metadata][type]}"
   }
  stdout { codec => rubydebug }
}
```
```
sudo oc get secret logging-elasticsearch --template='{{index .data "truststore"}}' | base64 -d > truststore.jks
```
and searchguard.truststore.jks ..

I am not sure where i am doing wrong , I couldn't identify how to resolve this connection please suggest  me with proper solution to make this fix. i badlly need this to be ready.

**Comment by ewolinetz** [comment]
@himmatb 
> You need to also provide to Elasticsearch (from Logstash) a client cert and client key.
