### ISSUE TITLE
Allow user to configure availability zone

### ISSUE THREAD

**Issue by portante** [openshift/origin-aggregated-logging#1197]
(Copies from https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/74)

Allow a user to configure the availability zones for each ES DC (pod).

Here is an example configuration we use in our internal production environment.  We have 6 nodes, 3 in each rack.  We consider a rack an availability zone.  So we do the following:

```
node.rack_id: "bagl-h2"
cluster.routing.allocation.awareness.attributes: rack_id
cluster.routing.allocation.awareness.force.zone.values: ["bagl-h2", "bagl-h3"]
```

Here we provide an arbitrary metadata data on the node using an attribute name we define, called `rack_id`.  We tell Elasticsearch the attribute's name using `cluster.routing.allocation.awareness.attributes`, and set it to the arbitrary value we chose (actually chosen to match the physical labels of the rack in our data center).  Then we use `cluster.routing.allocation.awareness.force.zone.values` to enumerate the list of values to expect to force the behavior of NEVER allowing copies of the same shard to be allocated to the same zone.

For our purposes, using an attribute of `zone`, and values `z1` and `z2` would be sufficient:

```
node.zone: "z2"
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: ["z1", "z2"]
```

**Comment by jcantrill** [comment]
@ewolinetz @t0ffel is this something we should consider adding to the elasticsearch operator?

**Comment by ewolinetz** [comment]
@jcantrill didn't we remove this plugin from our ES image? I'm not sure how the operator would provide this functionality, it's a change in our ES forms its clusters.
