### ISSUE TITLE
USER 1000 in Dockerfile

### ISSUE THREAD

**Issue by joergHen** [openshift/origin-aggregated-logging#1229]
Hi, my name is Jörg Henkel, we using OCP on premise and we have got this little Problem with the 
fixed USER 1000 in your Image. It produces conflicts with some Monitor Agent Software what uses the same
ID as the origin logging, we can work arround it, but it would be nicer to have the possibility to change it
as variable in OCP or when it's set to a higher range of ID number, eg. 5000. Is it possible? 
Best regards, Jörg

**Comment by jcantrill** [comment]
@joergHen Can you specify which image in particular is an issue?  @sosiouxme @richm @ewolinetz any of you recall why we need to utilize a specific UID and can not depend on the random one provided by the runtime?

**Comment by richm** [comment]
I don't recall

**Comment by ewolinetz** [comment]
IIRC we specified this for ES as part of setting SCCs for handling storage...

**Comment by joergHen** [comment]
Ah, i see you need this for Storage, ... NFS PV's? Same thing in Kibana, there is the USER 1001 in the dockerfile, what is not a real problem for us, but does it make sence to make these values customizable generally for this cases where it's not possible to use a random value?

**Comment by joergHen** [comment]
oh yes, possibly in the configmap, a variable and an ansible var to set it in the ocp installation process?

**Comment by jcantrill** [comment]
Isn't this something you can set in the security context [1]?  We would probably need to add a var in openshift-ansible (or the operator) to set it during deployment.

[1] https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by joergHen** [comment]
@jcantrill: Yes, this looks like the right way to set it, Thx. Such openshift-ansible var is not existing yet, right? If not, would be great and helpful to have this.
