### ISSUE TITLE
Cluster initialization and modifications proposal

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#1251]
# Overview
Initialization of the ES cluster is currently executed by the run script by backgrounding a process which is contrary to recommendations for running containers.  Kubernetes does not offer (AFAIK) a way to run post initialization outside of using something like a Job.  In anticipation of the introduction of operators, this proposal identifies how we may modify and structure the initialization and migration tasks so they could be executed by something like a Job or the operator.  It would move us more in line with the original deployer which allows us to add version the initialization and migration tasks within our elasticsearch image.

# Proposal
* Create directories specifically for initialization tasks and migration tasks
* Add an `init` (or `cluster-init`) and `migrate` entrypoints
## Directory Structure
Each directory includes the scripts needed to perform the init or migrate tasks:
* prefixed with a 4 digit number to identify the order in which they are executed
* idempotent
```
/etc/elasticsearch
  |- init/
     |- 0001-seed-acl
     |- 0010-seed-index-templates
  |-migrate/
    |- 0100-clean-kibana-index-patterns
    |- 0150-remove-old-searchguard-indices
```
## Entry points
```
${HOME}/init

  #!/bin/bash
  source logging
  for file in $(/etc/elasticsearch/init/*); do
     if [ -f $file ] ; then
       $("./${file}")
     fi  
  done

${HOME}/migrate
```
## run.sh
Initially, modify the `run.sh` script to background the `init` and `migrate` scripts

**Comment by richm** [comment]
Sounds good.  We will need to use it for the index settings in es 6 as well.

My only concern is around how users will edit or supply their own configs.  e.g. will there be a logging-elasticsearch-init configmap with entries for 0001-seed-acl, etc.?

**Comment by jcantrill** [comment]
There are a few layers of abstractions here. The base logic could be backported to the common image to point the top level script to empty, well known directories to allow users to mount and provide their own initialization logic.  Openshift then layer on top of that.  In your example specifically, we can do the same with our seeding script, either avertise the config directory to overwrite, or another, well known dir to overwrite which we use if it exists or our defaults if it doesn't.

IMO, 99.99% of the time we do not want or expect people to modify these scripts, though maybe ACLs is  outside the norm here.

**Comment by ewolinetz** [comment]
:+1: to this, I'm leaning more towards this being moved into the ES operator as we plan to move the curation logic into there already. It probably wouldn't be too difficult to have a watch on specific index patterns/ACLs being in there and then seeding them if necessary
