### ISSUE TITLE
Allow extending SearchGuard configuration

### ISSUE THREAD

**Issue by rhnewtron** [openshift/origin-aggregated-logging#1256]
Currently the init script modifies the SearchGuard Configuration in place. 

See https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/run.sh#L84-L88

This prohibits moving the SearchGuard Configuration to a configmap, allowing for custom roles and rolesmapping for advanced logging scenarios (e.g. tenant writable logs) for external log integration.

Workaround is to use a init container and a emtyDir{} host volume for /opt/app-root/src/sgconfig/, however this is dirty.

Please provide a way to extend the SearchGuard config (new Roles / Rolesmapping) via Configmap (e.g. mounted on /sgconfig)

**Comment by sghosh151** [comment]
+1

**Comment by richm** [comment]
Might also require changes to https://github.com/fabric8io/openshift-elasticsearch-plugin

**Comment by jcantrill** [comment]
> Currently the init script modifies the SearchGuard Configuration in place.
> 
> See https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/run.sh#L84-L88
> 
This is not correct. This particular line copies the Elasticsearch config to an alternate place in the image; I don't recall why we do this.

> This prohibits moving the SearchGuard Configuration to a configmap, allowing for custom roles and rolesmapping for advanced logging scenarios (e.g. tenant writable logs) for external log integration.
> 
> Workaround is to use a init container and a emtyDir{} host volume for /opt/app-root/src/sgconfig/, however this is dirty.

Custom SG configuration can be accomplished by extracting '/opt/app-root/src/sgconfig' into a configmap and mounting it into the image.  I caution doing this without extensive testing to determine if you are able to modify the ACLs; SearchGuard and the way its utilized with OKD ClusterLogging is highly specific.

> 
> Please provide a way to extend the SearchGuard config (new Roles / Rolesmapping) via Configmap (e.g. mounted on /sgconfig)

We should consider extracting to a Configmap anyway so user's can modify via an Unmanaged cluster-logging-operator.  @ewolinetz thoughts?

**Comment by jcantrill** [comment]
> Might also require changes to https://github.com/fabric8io/openshift-elasticsearch-plugin

I believe the plugin will operate with mounting a configmap over the place it expects.  There still is an issue with how certs are processed and/or tokens needing to exist on the headers.

**Comment by rhnewtron** [comment]
It seems there have been a lot of changes in the init script. The last time I checked, it modified the stuff in place: https://github.com/openshift/origin-aggregated-logging/blob/fc4a7f7b0b7234e2c2532078c938525ad90a0fc6/elasticsearch/run.sh#L84-L88 
So it may be that this is fixed now.
