### ISSUE TITLE
Upgrade ruby to 2.4.3 for v3.9

### ISSUE THREAD

**Issue by addozhang** [openshift/origin-aggregated-logging#1264]
In order to output to logstash, `fluent-plugin-out-http` plugin is required.

But ruby version is required >=2.1. So upgrade ruby env to 2.4.3, and update other plugins's version. 

Desc:
- `Dockerfile.centos-rb24`: install ruby 2.4.3 via `rvm` base on `centos:centos7`
- `Dockerfile.output-http`: add `fluent-plugin-out-http` base on what we did in `Dockerfile.multi-line`

**Comment by richm** [comment]
We can't possibly do this in 3.9. One of the requirements of fluentd is that we have to be able to support it downstream in rhel7, which means
- all rubygems must be rpm packaged
- ruby 2.0 (yes, it's past eol, but Red Hat has a dedicated team to support it)

fluentd pulls in a _lot_ of gems, all of which must be packaged as rpms - in addition, if we want to support ruby > 2.0, that means using SCL, which means all of those rpms must be converted to SCL.

If you would be interested in supporting this effort, we would welcome that.
