### ISSUE TITLE
Default Kibana Index Mode to 'shared_ops'

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#1274]
I think we should consider modifying our default Kibana Index Mode to be `shared_ops` for 3.11 which means operations users by default can share queries and dashboards.  All other users are still unique.  This would be a nice precursor to providing OOTB dashboards and would be a great point to make the change since we are rolling out the ES5.x stack.

Thoughts?

cc @tkatarki @richm @ewolinetz ?

Biggest contention I see is the 'surprise' of the change which hopefully can be captured in documentation without incident.  cc @mburke5678

**Comment by jcantrill** [comment]
We may have missed the window to introduce this for 3.11.  I'm not sure we would want to modify in a z stream deployment.  @ewolinetz @richm should we settle for the change in 4.0?

**Comment by richm** [comment]
yes - 4.0

**Comment by jcantrill** [comment]
Closing in favor of https://jira.coreos.com/browse/LOG-312
