### ISSUE TITLE
How best to clean up project.<PROJECTNAME>.* index-patterns

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#1276]
With the merge of https://github.com/fabric8io/openshift-elasticsearch-plugin/pull/128 the kibana index no longer creates index patterns for all projects.  The ones that were seeded prior to the change still exist and should be cleaned up.  I'm questioning the best way to do that.

My original thought was to create a migrate script but then we need to figure out:
How do we know if we should run it?  Possibly:
1. Run script to remove all index-patterns which match
2. Write a migration document to the index with the name of this script and when for history
1. future 'migrates' will check for document and only run if its missing
This assumes we will clean all that match the pattern even if they were manually created.

Alternatively,

We create a script along with a kbase and have users manually clean the index.  Opinions?

cc @ewolinetz @t0ffel @richm @lukas-vlcek @josefkarasek @nhosoi

**Comment by ewolinetz** [comment]
I dont think theres a need to run a migration script, it may be beneficial to make it a task as part of starting up to remove any search guard indices that match this pattern (and are no longer being used)

**Comment by jcantrill** [comment]
fixed by https://github.com/openshift/origin-aggregated-logging/pull/1335
