### ISSUE TITLE
[exploratory] client-node based optimizations for finer grained scaling tasks

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin-aggregated-logging#128]
Problem

Scaling Elastic search now is done course-grained:  By creating more servers.  However, there are many different types of scaling - write throughput, capacity, etc...  So, when we need to just scale one aspect (i.e. write throughput), we  may have to take up extra resources on a cluster (storage) if we only have 1 way to scale elastic search.  

Soution

To prevent wasting resources, we can implement finer-grained scaling of different elastic search nodes (writers, readers, clients).

Details 

 @portante  has suggested we leverage ES-Client nodes to decouple scaling requirements , cc @jeremyeder  @timothysc @rflorenc 

the elastic search "client node" is a special node which is really just there to do smart "ES-aware" loadbalancing, https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html. 

[this diagram summarizes the arch change we might implement if we use ES Clients ](https://github.com/openshift/origin-aggregated-logging/files/255191/x.txt)

This is just a first pass but the main idea is:
- separate writers from readers
- have kuberentes service abstraction connect to "client nodes"

The benefits: 

Writers never have to field read requests, clients minimize the amount of "hops" they have to do when connecting to a shard, and you decouple scaling of logging capacity (bottlnecked by servers) from scaling of other operations (reads/writes/lookups).

**Comment by jcantrill** [comment]
I'm chiming in a little late here but his is probably work that needs to be undertaken by either @richm team or the performance to team to validate what's best.  It's worth the effort to explore but IMO we are most likely WRITE intensive.  I don't image we will ever experience large READ loads in relation to ES cluster size even at the larger scales for online and dedicated environments.

**Comment by jcantrill** [comment]
closing without prejudice.  Any change related to this would be under the openshift/cluster-logging-operator to define  and impl
