### ISSUE TITLE
v3.10.0 tag missing on docker hub

### ISSUE THREAD

**Issue by jfcoz** [openshift/origin-aggregated-logging#1307]
It seems that v3.10.0 is missing on all openshift/origin-logging-* images on docker hub (v3.10.0-rc.0 or v3.10 are available)

example : https://hub.docker.com/r/openshift/origin-logging-curator/tags/

Could you add this tag ?

**Comment by jocelynthode** [comment]
This is a really irritating issue as everytime we run the playbook we have to quickly and manually edit the deployment to fix this.

**Comment by jcantrill** [comment]
v3.10 is a floating tag to the latest version of that release stream.  Consider updating your ansible inventory variable `openshift_logging_image_version` to use `v3.10` instead of `v3.10.0`.  In the meantime we'll see what we can do to provide the additional tag

**Comment by jocelynthode** [comment]
openshift_logging_image_version as well as  openshift_metrics_image_version seem to not exist anymore in the openshift ansible release-3.10. I have them setup and used them with great success up to 3.10 or am I missing something? 

Am 11. September 2018 19:58:44 MESZ schrieb Jeff Cantrill <notifications@github.com>:

**Comment by ewolinetz** [comment]
We have oriented ourselves to use a similar pattern to other openshift components when it comes to image names being defaulted. We have variables for each logging component which you could set individually.

Or, if you are running the logging playbook separately you could update your `oreg_url` variable to specify the actual version you want to use: `oreg_url=openshift3/${component}:${version}` => `oreg_url=openshift3/${component}:v.3.10` (as an example)
