### ISSUE TITLE
Kibana index needs index template

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#1315]
Currently (on CI) I observed that our ES cluster isn't able to go `green` because the `.kibana` index was created with `1` primary and `1` replica.

We should conform the Kibana index to match what our other indices are created with.

**Comment by ewolinetz** [comment]
@lukas-vlcek how difficult would this be? Can we just add another pattern for one of our existing templates?

**Comment by lukas-vlcek** [comment]
@ewolinetz Adding one more index template for `.kibana*` to specify number of replicas isn't difficult. But first we should check how exactly the kibana index is created. I do not remember which process is in charge of this but there is a chance that when creating the index it explicitly specify number of shards/replicas in which case the index pattern would not have desired effect.

So what is the root issue here. Is it that we do not want .kibana index (indices) to have any replicas?

**Comment by ewolinetz** [comment]
The root issue is that we want to ensure that the number of replicas and shards matches what the other indices will be. I can check to see if Kibana has a way to tune the number of replicas and shards, if so then we could update the Kibana DC to accept these values and update them accordingly.

**Comment by ewolinetz** [comment]
@lukas-vlcek looks like the recommended approach is to use index templates per discussions on the Kibana issues page

**Comment by lukas-vlcek** [comment]
@ewolinetz then it should be as easy as adding one more file here <https://github.com/openshift/origin-aggregated-logging/tree/master/elasticsearch/index_templates>
