### ISSUE TITLE
Help Wanted/Question:  FluentD Forwarding and Aggregated Logging

### ISSUE THREAD

**Issue by vguaglione** [openshift/origin-aggregated-logging#1337]
We are using the FluentD Secure Forward Output plugin within our logging-fluentd configuration in OpenShift to forward messages to an external aggregator (td-agent3 running on a different server).

We have noticed that the messages collected by the aggregator are the messages being generated by the logging-fluentd* pods running in the cluster, not the actual cluster and application messages.  

When viewing messages through the Kibana UI within our cluster, we do see all cluster and application messages being collected and available for perusal, so my question is twofold:

1. In what location(s) does flunentd look for cluster and application messages to forward to elasticsearch?  I'm looking for the actual location(s) on the nodes such as /var/lib/docker/containers.... etc.

2. Since we do not see actual cluster and application messages making it to the aggregator, I'm assuming our forwarder configuration may need adjusting.  This is confusing because it appears to me that what is being collected by the aggregator is the messages from the fluentd pods only (what I see when viewing the fluentd pod log via the OpenShift UI), rather than the actual messages being generated by the cluster.

Can someone point me in the right direction for better understanding of how the aggregated logging system works in OpenShift and where I can find the answers to these questions?  At this point, I've scanned a bunch of official documentation and have searched through numerous posts online to find answers to these questions but have come up empty.  

Essentially, we would like to hook into the EFK stack, probably in the fluentd configuration, and send a copy of every application generated message to a second destination (a splunk instance, most likely).  

Any help would be appreciated.

**Comment by jcantrill** [comment]
Consider reviewing the DaemonSet template [1], config [2] files, and [3] run script.  These provide info where the node's filesystem is mounted into the fluent pod and how it is configured.  The run script 'figures' out which driver is being used (though that is changing) and uses this to determine the log sources.  The config will provide you additional information how the logs are tagged and routed through fluent's pipeline

[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_fluentd/templates/fluentd.j2#L63
[2]https://github.com/openshift/origin-aggregated-logging/tree/master/fluentd/configs.d
[3] https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/run.sh

**Comment by vguaglione** [comment]
Thanks, Jeff.  I will take a look and follow up on this thread with additional questions if need be.  Leaving this thread open for now.
