### ISSUE TITLE
fluentd filling logs with backslashes

### ISSUE THREAD

**Issue by benscottub** [openshift/origin-aggregated-logging#1423]
Hello, we are running origin 3.9:

[root@osn4 containers]# oc version
oc v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://webapps.buffalo.edu:443
openshift v3.9.0+ba7faec-1
kubernetes v1.9.1+a0ce1bc657

We just switched one of our nodes from journald to json-file logging driver (and restarted fluentd and docker) and now this node's fluentd logs are spammed with backslashes like this:

\"message\":\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"level\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"info\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"hostname\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"xxxxx.net\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"pipeline_metadata\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"collector\\\\\\\\\\\\\\\":{\\\\\\\\\\\\\\\"ipaddr4\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"x.x.x.x\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"ipaddr6\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"fe80::e02xxxx:fxxxxxx\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"inputname\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"fluent-plugin-systemd\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"name\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"fluentd\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"received_\\\",\\\"level\\\":\\\"info\\\",\\\"hostname\\\"

but also the logs contain hundreds of lines of just pure backslashes with no messages contained.
We have tried a couple of edits to the fluentd configmap including adding this directive:

<match fluent.**>
  @type null
</match>

but the logs behavior did not change. Can you provide some guidance on this issue?

**Comment by richm** [comment]
You might be asking "why then doesn't `<match fluent.**>` match them?  The answer is that these are not internal fluentd events, they are the actual stderr/stdout of fluentd being picked up by docker, logged as a regular container, and picked up by fluentd to be read as regular container log.

The message appears to be truncated - perhaps there is an error message being emitted by fluentd?

**Comment by benscottub** [comment]
Hey Rich, thanks for the fast response. will changing this variable in the daemonset trigger any restarts/redeploys? We have cordoned off one node for testing but would like to avoid triggering a restart across all of the nodes as the rest of them are in production.

I can provide more complete logs if you'd like, the message was truncated as I just wanted to provide a short example of what I was seeing in the logs.

**Comment by richm** [comment]
> Hey Rich, thanks for the fast response. will changing this variable in the daemonset trigger any restarts/redeploys?

Yes.

> We have cordoned off one node for testing but would like to avoid triggering a restart across all of the nodes as the rest of them are in production.

Not sure how to do that.

> I can provide more complete logs if you'd like, the message was truncated as I just wanted to provide a short example of what I was seeing in the logs.

I'd like to see if it is an error message, and, if it is, what is the error.

**Comment by benscottub** [comment]
Thanks Rich, we will deploy this tonight and get back to you tomorrow.

**Comment by benscottub** [comment]
Hey Rich, this fixed all of our problems. Thank you again for the quick response.

**Comment by richm** [comment]
@benscottub note that logging to /var/log/fluentd.log _will not rotate and will eventually fill up /var and kill your machine_.  Unless you create a `logrotate` rule for it or some such.

**Comment by richm** [comment]
@benscottub If you can use the very latest code (not sure which 3.9 you are using, and when you can update it), fluentd logs to /var/log/fluentd/fluentd.log by default _with rotation and max size configuration_.

**Comment by benscottub** [comment]
Hey Rich, thanks for the heads up. I'm testing a logrotate rule but fluentd continues logging to the rotated file after logrotate runs (it doesn't switch over to the new empty fluentd.log file that logrotate creates). What is the proper way to get fluentd to pick up the new fluentd.log file when it rotates?

**Comment by richm** [comment]
@benscottub I don't know.  The proper way is to use a version of OCP 3.x which has the version of fluentd which implements true file logging + size based rotation - see https://github.com/openshift/origin-aggregated-logging/pull/1336 and this was merged to 3.9 branch by this PR: https://github.com/openshift/origin-aggregated-logging/pull/1354
Not sure where you are getting 3.9 from, but you may have to build your own fluentd image based on the above PR (or just use the latest release-3.9 branch).
