### ISSUE TITLE
Issue with visualizing custom application logs with EFK in openshift

### ISSUE THREAD

**Issue by Heshma** [openshift/origin-aggregated-logging#1445]
In openshift , I'm trying to visualize custom application logs through EFK stack.

Operation system:
Centos 7

Openshift origin version:
oc v3.9.0+71543b2-33
kubernetes v1.9.1+a0ce1bc657

By default fluentd is configured to collect only PID1 docker logs which are written to var/log/containers/ directory. 
For fluentd to collect my application logs, I have first volume mounted logs directory from my container to a sub directory under /var/log/ in host machine. This would mount the application logs to hostmachine. As /var/log/ host path is alrady mounted inside fluent container with the default configuration, my application logs are mounted to fluentd container.
While starting fluentd container a conf file is generated(input-docker-default-docker.conf) in which source tag is configured with path as below: 
```
<source>
  @type tail
  @label @INGRESS
  path "/var/log/containers/*.log"
  pos_file "/var/log/es-containers.log.pos"
  time_format %Y-%m-%dT%H:%M:%S.%N%Z
  tag kubernetes.*
  format json
  keep_time_key true
  read_from_head "true"
  exclude_path []
</source>
```

But as I mounted my application logs to a different path, I have created another conf file (input-docker-default-applogs.conf) and mounted it to fluentd container with path pointing to a directory where my application logs are mounted
```
<source>
  @type tail
  @label @INGRESS
  path "/var/log/applogs/*.log"
  pos_file "/var/log/app-logs.log.pos"
  tag kubernetes.*
  format json
  keep_time_key true
  read_from_head "true"
  exclude_path []
</source>
```

Next I have included above conf file in default fluent.conf in config map as below
```
@include /mnt/pegajson/input-docker-default-logs.conf
```

With this configuration we were able to configure fluentd to collect logs from custom source path where I have mounted my logs. 
My application logs are in JSON format. But indexing of my log file is failing and we are seiing below error message.
**record cannot use elasticsearch index name type project_full: record is missing kubernetes field**

After exploring on this error, itseems that indexing is failing as it is expecting some fields in my log file (project_full - "project.${kubernetes.namespace_name}.${kubernetes.namespace_id}.YYYY.MM.DD") - https://github.com/ViaQ/fluent-plugin-viaq_data_model/blob/master/lib/fluent/plugin/filter_viaq_data_model.rb
[applicationlog.json.log](https://github.com/openshift/origin-aggregated-logging/files/2530398/applicationlog.json.log)

**Comment by richm** [comment]
Is your application running as a container in kubernetes?  If so, can you configure your application to write its logs to stdout/stderr?
If not, then you cannot use this tag:
```
  tag kubernetes.*
```
That tag must only be used for container log files from /var/log/containers/*.log written by docker/kubernetes.

**Comment by Heshma** [comment]
> In openshift , I'm trying to visualize custom application logs through EFK stack.
> 
> Operation system:
> Centos 7
> 
> Openshift origin version:
> oc v3.9.0+71543b2-33
> kubernetes v1.9.1+a0ce1bc657
> 
> By default fluentd is configured to collect only PID1 docker logs which are written to var/log/containers/ directory.
> For fluentd to collect my application logs, I have first volume mounted logs directory from my container to a sub directory under /var/log/ in host machine. This would mount the application logs to hostmachine. As /var/log/ host path is alrady mounted inside fluent container with the default configuration, my application logs are mounted to fluentd container.
> While starting fluentd container a conf file is generated(input-docker-default-docker.conf) in which source tag is configured with path as below:
> 
> ```
>   @type tail
>   @label @INGRESS
>   path "/var/log/containers/*.log"
>   pos_file "/var/log/es-containers.log.pos"
>   time_format %Y-%m-%dT%H:%M:%S.%N%Z
>   tag kubernetes.*
>   format json
>   keep_time_key true
>   read_from_head "true"
>   exclude_path []
> </source>```
> 
> But as I mounted my application logs to a different path, I have created another conf file (input-docker-default-applogs.conf) and mounted it to fluentd container with path pointing to a directory where my application logs are mounted
> `<source>
>   @type tail
>   @label @INGRESS
>   path "/var/log/applogs/*.log"
>   pos_file "/var/log/app-logs.log.pos"
>   tag kubernetes.*
>   format json
>   keep_time_key true
>   read_from_head "true"
>   exclude_path []
> </source>`
> 
> Next I have included above conf file in fluent.conf in config map as below
> @include /mnt/pegajson/input-docker-default-logs.conf
> 
> With this configuration we were able to configure fluentd to collect logs from custom source path where I have mounted my logs. 
> My application logs are in JSON format. But indexing of my log file is failing and we are seiing below error message.
> **record cannot use elasticsearch index name type project_full: record is missing kubernetes field**
> 
> After exploring on this error, itseems that indexing is failing as it is expecting some fields in my log file (project_full - "project.${kubernetes.namespace_name}.${kubernetes.namespace_id}.YYYY.MM.DD") - https://github.com/ViaQ/fluent-plugin-viaq_data_model/blob/master/lib/fluent/plugin/filter_viaq_data_model.rb
> [applicationlog.json.log](https://github.com/openshift/origin-aggregated-logging/files/2530398/applicationlog.json.log)
> ```



> Is your application running as a container in kubernetes? If so, can you configure your application to write its logs to stdout/stderr?
> If not, then you cannot use this tag:
> 
> ```
>   tag kubernetes.*
> ```
> That tag must only be used for container log files from /var/log/containers/*.log written by docker/kubernetes.

In openshift, we have to include input, filter and output conf in fluent.conf with input conf file having source directive which determines the input sources and output conf file having match/store directive which determines the output destinations.
We tried to explore on these configurations, but we are running into issues. Could you provide us with sample templates of these conf files to collect custom application logs so that it would be helpful to us to configure for my custom application logs?

**Comment by jcantrill** [comment]
@Heshma The collector does not support what you are trying to accomplish in the way you are trying to implement it.  The OKD log stack is specifically configured to collect logs written to STDOUT via a container running on the platform.  It additionally enriches the data to include kubernetes labels which it retrieves by discerning the pod name and namespace from the file path.  The file names are written in a well known format by the container runtime.  Additionally, the information parsed from the file name is used to determine where in Elasticsearch the logs will be indexed.  Your error is a direct result of producing logs in an unexpected format.

The recommend solution is to add a side-car container to your pod which will tail and dump the logs to STDOUT.  This will ensure the logs flow through the existing pipeline without needing to modify the configuration.  I encourage you to follow this pattern as the current implementation of the logging stack also includes security provisions around the existing schema which would prohibit you from reading logs in any index that does not conform to the pattern it expects.
