### ISSUE TITLE
Add `index` path in common.settings.kibana.template.json

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#1449]
It seems we use `index` path when settings `number_of_shards` and `number_of_replicas` in all our index templates but [elasticsearch/index_templates/common.settings.kibana.template.json](https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/index_templates/common.settings.kibana.template.json). Although Elasticsearch accept both ways _(\[citation needed\])_ we should stick to one of them only. I suggest using the `index` path to follow doc at https://www.elastic.co/guide/en/elasticsearch/reference/5.6/index-modules.html

**Comment by jcantrill** [comment]
fixed by https://github.com/openshift/origin-aggregated-logging/pull/1497
