### ISSUE TITLE
Deployer pod fails on timeout: How to debug?

### ISSUE THREAD

**Issue by jayunit100** [openshift/origin-aggregated-logging#145]
I'm finding that on a cluster, after deploying some ES nodes, I get this: 

```
logging-es-wucg4yv5-1-deploy   0/1       Error       0          2m
logging-es-wvn347bb-1-deploy   0/1       Error       0          4m
logging-es-xf75ods2-1-deploy   0/1       Error       0          2m
logging-es-xtb58wpb-1-deploy   0/1       Error       0          4m
logging-es-y2kmwhda-1-deploy   0/1       Error       0          2m
logging-es-ybwfcgo1-1-deploy   0/1       Error       0          2m
```

Basically, all the ES deploy tasks fail.  Since there's no `logging-es` pod ever created, all i see is a timeout.

```
root@support: /opt/jay/team8/projects/enterprise_logging # oc logs logging-es-q0pf7vnt-1-deploy
I0520 17:44:24.403372       1 deployer.go:200] Deploying logging/logging-es-q0pf7vnt-1 for the first time (replicas: 1)
I0520 17:44:24.447335       1 recreate.go:126] Scaling logging/logging-es-q0pf7vnt-1 to 1 before performing acceptance check
F0520 17:46:25.543245       1 deployer.go:70] couldn't scale logging/logging-es-q0pf7vnt-1 to 1: timed out waiting for the condition
```

1) Any idea how to fix this?  
2) How can we get more information about where the logging deployer is falling down?

cc @rflorenc

**Comment by richm** [comment]
I think this is coming from `oc new-app logging-es-template` - is there some sort of timeout we can specify here?  Can we set a timeout in the template somehow?

When `oc logs` doesn't give much information, try `oc get events`, then take a look at the logs for the openshift node agent, and the openshift master (e.g. `journalctl -u atomic-openshift-node.service` or `journalctl -u atomic-openshift-master.service`

**Comment by ewolinetz** [comment]
It looks like this is occurring after the logging-deployer has completed and the RC deployer for ES is timing out.  The OpenShift logs should be able to give a little bit more information what condition we timed out on.  I'm wondering if the image isn't available (judging by the fact that all of the ES nodes have status `Error`)?

**Comment by jcantrill** [comment]
Closing for now since this issue looks dated and we are moving deployer to ansible
