### ISSUE TITLE
Archive old logs

### ISSUE THREAD

**Issue by camabeh** [openshift/origin-aggregated-logging#1464]
Hello,

is there any reason why curator wrapper only supports delete action? I would like to add snapshot functionality to curator.py.

**Comment by josefkarasek** [comment]
Our wrapper was firstly developed for ES 2.x (@richm or maybe even 1.x?).
Back then curator didn't have what now is the actions file and the feature list wasn't as rich as it is today.
Instead users configured curator via command line arguments.
With the move to newer curator for ES 5.x, we allow users to either use our custom config file, that we initially developed for older version of curator, or provide their own actions file.
Internally, the wrapper generates actions file from the custom config format.
So, if you're on ES 5.x and you want to use other curator functions than just delete, you're best shot is to [provide your own actions file](https://github.com/openshift/origin-aggregated-logging/tree/master/curator#using-actions-file).

**Comment by jcantrill** [comment]
@camabeh Pull requests are always welcome.
