### ISSUE TITLE
EFK Stack - Getting Started

### ISSUE THREAD

**Issue by sklakken** [openshift/origin-aggregated-logging#1480]
I'm swimming in a sea of TMI (too much info) and don't know which direction to take. I have a default instance of Origin OKD (gshipley/installcentos) running and simply want to get started using the EFK stack. This isn't a production implementation, so I simply want a bare-bones implementation.

1. Isn't fluentd part of my default install? How would I know?
2. How do I use Elasticsearch with fluentd? 

Thank for your support!

**Comment by richm** [comment]
For a really quick quickstart, try https://github.com/ViaQ/Main/blob/master/README-install.md

> Isn't fluentd part of my default install? How would I know?

Yes, it is.

more detailed docs are at

https://docs.okd.io/3.11/install_config/aggregate_logging_sizing.html
and
https://docs.okd.io/3.11/install_config/aggregate_logging.html
