### ISSUE TITLE
Error in deployment instruction (minor)

### ISSUE THREAD

**Issue by andriyfomenko** [openshift/origin-aggregated-logging#149]
https://docs.openshift.org/latest/install_config/aggregate_logging.html#pre-deployment-configuration

Preparation step #3 has to have URL corrected: https://raw.githubusercontent.com/openshift/origin-aggregated-logging/master/**deployment**/deployer.yaml

**Comment by ewolinetz** [comment]
Noted, will open a PR against our docs to update that.  Thanks!

**Comment by ewolinetz** [comment]
https://github.com/openshift/openshift-docs/pull/2155

**Comment by ewolinetz** [comment]
fix has been merged in, should be made public with next docs build.
