### ISSUE TITLE
Cannot enable debug logging for fluentd

### ISSUE THREAD

**Issue by konradgaluszka** [openshift/origin-aggregated-logging#1496]
Hi all,
I've noticed that fluentd installation in openshift image has **ids** declared in its plugins.
(https://github.com/openshift/origin-aggregated-logging/commit/de661200ef9de2e86101d5920b54f26af711527f).
I was trying to utilize this to enable debug logging in  elasticsearch plugin by adding my custom extra configuration (output-extra-es.conf) with something like this:
```
<store>
  @type elasticsearch
  @id elasticsearch-apps
  @log_level debug
</store>
```
But fluentd is not working as in my assumptions and therefore not merging store configuration from the  image  (in output-es-config.conf). 
Is there any way to enable debug logging only in this one plugin and not globally?
Is there any plan to add the log to output-es-config.conf with proper default level?

Regards

**Comment by konradgaluszka** [comment]
@richm It's OpenShift v3.11.59, image version of fluentd is openshift3/ose-logging-fluentd:v3.11.59.
When I override es-output-config.conf file from /etc/fluent/configs.d/openshift/es-output-config.conf with my configmap and  add @log_level debug:

```
<store>
  @type elasticsearch
  @id elasticsearch-apps
  host "#{ENV['ES_HOST']}"
  port "#{ENV['ES_PORT']}"

 @log_level debug # <-- here
 
 scheme https
  ssl_version TLSv1_2
  target_index_key viaq_index_name
  id_key viaq_msg_id
  remove_keys viaq_index_name
  user fluentd
  password changeme

  client_key "#{ENV['ES_CLIENT_KEY']}"
  client_cert "#{ENV['ES_CLIENT_CERT']}"
  ca_file "#{ENV['ES_CA']}"

  type_name com.redhat.viaq.common
  retry_tag "retry_es"

  reload_connections "#{ENV['ES_RELOAD_CONNECTIONS'] || 'true'}"
  # https://github.com/uken/fluent-plugin-elasticsearch#reload-after
  reload_after "#{ENV['ES_RELOAD_AFTER'] || '200'}"
  # https://github.com/uken/fluent-plugin-elasticsearch#sniffer-class-name
  sniffer_class_name "#{ENV['ES_SNIFFER_CLASS_NAME'] || 'Fluent::ElasticsearchSimpleSniffer'}"
  reload_on_failure false
  flush_interval "#{ENV['ES_FLUSH_INTERVAL'] || '1s'}"
  max_retry_wait "#{ENV['ES_RETRY_WAIT'] || '300'}"
  disable_retry_limit true
  buffer_type file
  buffer_path '/var/lib/fluentd/buffer-output-es-config'
  buffer_queue_limit "#{ENV['BUFFER_QUEUE_LIMIT'] || '32' }"
  buffer_chunk_limit "#{ENV['BUFFER_SIZE_LIMIT'] || '8m' }"
  buffer_queue_full_action "#{ENV['BUFFER_QUEUE_FULL_ACTION'] || 'block'}"
  flush_at_shutdown "#{ENV['FLUSH_AT_SHUTDOWN'] || 'false'}"

  write_operation 'create'

  # 2 ^ 31
  request_timeout 2147483648
</store>

```
then it works. But it's rather a workaround than a clean solution.

Do you have any idea for something better? Thanks

**Comment by richm** [comment]
> Do you have any idea for something better?

I suppose we could add an env. var. to the config:
```
<store>
  @type elasticsearch
  @id elasticsearch-apps
  @log_level "#{ENV['ES_APPS_LOG_LEVEL'] || ENV['ES_LOG_LEVEL'] || 'warn'}"
  ...
```
or something like that - patches welcome

**Comment by konradgaluszka** [comment]
Thanks for the answer. I will prepare a PR

**Comment by konradgaluszka** [comment]
> @log_level "#{ENV['ES_APPS_LOG_LEVEL'] || ENV['ES_LOG_LEVEL'] || 'warn'}"

Could you explain the suggestion for 2 envs? I cannot find any reference in the project.
Should I also provide proper changes in openshift-ansible repository?

Regards

**Comment by richm** [comment]
> @richm
> 
> > @log_level "#{ENV['ES_APPS_LOG_LEVEL'] || ENV['ES_LOG_LEVEL'] || 'warn'}"
> 
> Could you explain the suggestion for 2 envs? I cannot find any reference in the project.

Never mind.  Just use
```
@log_level "#{ENV['ES_LOG_LEVEL'] || 'warn'}"
```

> Should I also provide proper changes in openshift-ansible repository?

I don't think any change there is required.

> 
> Regards

**Comment by konradgaluszka** [comment]
Have you had a chance to see my changes? Please let me know if there is a need to add anything. Thanks

**Comment by jcantrill** [comment]
@konradgaluszka please ref PR here

**Comment by richm** [comment]
> @richm Have you had a chance to see my changes? Please let me know if there is a need to add anything. Thanks

I requested a couple of minor changes.  Did you see that?

https://github.com/openshift/origin-aggregated-logging/pull/1543
