### ISSUE TITLE
Improve experience around scaling ES

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#151]

**Comment by jcantrill** [comment]
@ewolinetz more detail...

**Comment by ewolinetz** [comment]
Currently the process is very manual [0] and if not done correctly _could_ result in some split-brain scenarios.  We should probably provide a mode so that the deployer performs those steps for us.

[0] https://github.com/openshift/openshift-docs/pull/2136/files

**Comment by ewolinetz** [comment]
give option to use some of what #128 mentions?

**Comment by jcantrill** [comment]
@ewolinetz aside from needing to move to stateful sets, are you concerns mitigated with the move to ansible?  Can we close this issue?

**Comment by ewolinetz** [comment]
@jcantrill it should be, however I haven't tested yet to confirm... we can always reopen this though
