### ISSUE TITLE
Nodes unable to join cluster: no cipher suites in common

### ISSUE THREAD

**Issue by ayushmathur86** [openshift/origin-aggregated-logging#1510]
I have recently upgraded 3 node EFK cluster from 5.4.2 to 6.2.3 version using logging project on OCP 3.6.
The upgrade is successful and works without any issues if X-pack is kept disabled.
However, on enabling x-pack, the nodes are not able to perform SSL handshake and start throwing:
`[2019-02-11T12:41:21,921][WARN ][o.e.x.s.t.n.SecurityNetty4ServerTransport] [HbWWj1T] exception caught on transport layer [NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:45230, remoteAddress=/0:0:0:0:0:0:0:1:9300}], closing connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure`

On further looking into the logs, I can see:
`[2019-02-11T12:41:21,921][WARN ][o.e.x.s.t.n.SecurityNetty4ServerTransport] [HbWWj1T] exception caught on transport layer [NettyTcpChannel{localAddress=0.0.0.0/0.0.0.0:9300, remoteAddress=/0:0:0:0:0:0:0:1:45230}], closing connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: no cipher suites in common
Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common
`
The full log file from one of the node is attached for reference.
Can someone please let me know how this issue can be resolved ?
[logging-es-g7c8vog7-33-nm61w.log](https://github.com/openshift/origin-aggregated-logging/files/2851182/logging-es-g7c8vog7-33-nm61w.log)

**Comment by richm** [comment]
We don't support x-pack.
We don't yet support ES 6.x
