### ISSUE TITLE
How can we debug or check the timezone while running Curator ?

### ISSUE THREAD

**Issue by bysnupy** [openshift/origin-aggregated-logging#1519]
* Version:
  - OCP: `v3.11.69`
  - image: `ose-logging-curator5:v3.11.69`

* Issue:
  I've verified the curator is aware of `CURATOR_RUN_TIMEZONE` when it runs
  
  But I could not find how to check/debug the configuration is valid, even though log level is debug as follows.
~~~
CURATOR_SCRIPT_LOG_LEVEL=DEBUG
CURATOR_LOG_LEVEL=DEBUG
~~~

Could you please inform me some guides to verify the configuration details  ?

**Comment by richm** [comment]
What are you trying to check?
We do have a CI test for the old-style curator config: https://github.com/openshift/origin-aggregated-logging/blob/release-3.10/test/curator.sh
the test hasn't been ported to use the new style cronjob, but you might be able to use some of the old code to test and verify

**Comment by bysnupy** [comment]
Thank you for your swift response @richm

> What are you trying to check?
I'd like to check the value of `timezone` after changing the value while the `curator` is running.

> the test hasn't been ported to use the new style cronjob, but you might be able to use some of the old code to test and verify

Is it valid on v3.11 yet ? `new style cronjob` is what version of OCP or image is ? such as  `v4.0` or `v3.11`.

**Comment by bysnupy** [comment]
Thank you @richm

I've checked `curator.sh`, I think it's helpful how to check the validation based on running time.
We don't have option to view directly the recognized `env` variable in the curator runtime ?

> the test hasn't been ported to use the new style cronjob, but you might be able to use some of the old code to test and verify

For more clarification let me ask for above comment, does it mean just test hasn't been ported, but the curator on v3.11 also is aware of CURATOR_RUN_TIMEZONE when running ?

**Comment by josefkarasek** [comment]
Hi @bysnupy, timezone for k8s cronjobs isn't configurable. Instead, the timezone of the host, on which the pod gets scheduled to, is used.

Pls refer to our documentation - https://github.com/josefkarasek/origin-aggregated-logging/tree/master/curator#compatibility-with-openshift-37
