### ISSUE TITLE
Support for rollover API at EFK stack

### ISSUE THREAD

**Issue by kacper-jackiewicz** [openshift/origin-aggregated-logging#1531]
Hi, during deployment/testing of EFK stack on our Openshift cluster, we stumbled on a problem.

 In our case some of the namespaces generate huge amount of logs, which results in shards with over 50GB of size. We know that the easiest way would to be increase primary shards amount, but in our case this would result hundreds of projects with multiple shards with low amount of data, which would result in decrease of performance.
The best solutions for us would be to configure Fluentd to create aliases and write to them as we could make use of rollover api to rollover only the indices, which require that operation.

In [fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) we found an option with rollover capabilities, but on current Openshift Images v3.11.59 version of this plugin is to old to allow us to use it.
 
We wonder, if there is a plan to update fluentd-elasticsearch plugin to a newer version with writing to an aliases enabled, in which case we could use rollover api, through curator, or "operator" like pod in namespace.

If this is not possible in near future, what would be the best approach for us to take to handle this case?

**Comment by richm** [comment]
We are not planning to update fluentd in v3.11.

Master branch (which will be ocp 4.0) uses fluentd 1.3 and the latest versions of 
[fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) - please try that

**Comment by kacper-jackiewicz** [comment]
Ok, thanks for information. For now we won't be able to update environments. So we will template the indexes which will pass the 50GB/shard mark till update will be available. 
Thanks again, this issue can be closed.
