### ISSUE TITLE
fluentd remote - syslog over TLS

### ISSUE THREAD

**Issue by sghosh151** [openshift/origin-aggregated-logging#1547]
Would it be possible to upgrade the Fluentd output to remote syslog server to support TLS connections instead of raw  UDP.

eg: [https://github.com/dlackty/fluent-plugin-remote_syslog](https://github.com/dlackty/fluent-plugin-remote_syslog)

**Comment by richm** [comment]
https://github.com/openshift/origin-aggregated-logging/commit/d54579359357b0b79d5d67d8316cae3eca91ee75

**Comment by sghosh151** [comment]
Is patch for just TCP or supporting TLS as well?

**Comment by richm** [comment]
Yes, sorry, no TLS support

**Comment by sghosh151** [comment]
Any thoughts on pattern for forwarding over TLS?

**Comment by richm** [comment]
> Any thoughts on pattern for forwarding over TLS?

The only way to do that now is to use secure_forward.  We don't currently have any plans to switch from using `fluent-plugin-remote-syslog` to `fluent-plugin-remote_syslog` or some other syslog plugin with TLS support - we haven't had any Red Hat customers asking for such a feature.  Patches welcome, but there is a lot of work that would need to be done to the ruby script that generates the config - https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/generate_syslog_config.rb
