### ISSUE TITLE
Can't connect fluentd to external, insecure (HTTP clear text) ElasticSearch 

### ISSUE THREAD

**Issue by Dimss** [openshift/origin-aggregated-logging#1560]
As per OCP documentation, I need to execute following changes to connect Fluent to external elastic search insecure instance
```
Update  ES_HOST, ES_PORT, OPS_HOST, OPS_PORT 
```
and in case my ES is insecure [then:](https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#sending-logs-to-an-external-elasticsearch-instance)
```
If your externally hosted Elasticsearch instance does not use TLS, update the _CLIENT_CERT, _CLIENT_KEY, and _CA variables to be empty.
```
So, I've updated the daemon set configs, all pods redeployed, but now in FluentD logs I see following error: 
```
2019-03-14 12:23:42 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2019-03-14 12:24:48 +0000 
error_class="Fluent::ElasticsearchOutput::ConnectionFailure"
error="Can not reach Elasticsearch cluster ({:host=>\"10.166.0.24\", :port=>9200, 
:scheme=>\"https\", :user=>\"fluentd\", :password=>\"obfuscated\"})!" 
plugin_id="elasticsearch-apps"
```
While checking the `out_elasticsearch` plugin configuration, I've found that in `output-es-config.conf` file, the `scheme https` configured statically and can't be changed by any parameter. 

Is it bug? Or it's by design and the docs out of date? 
What are my options to use insecure external ES instance with OpenShift FluentD?

**Comment by jcantrill** [comment]
You can always extract the configuration of the generated files or edit the logging-fluentd configmap to define  your own configuration.  In regards to the scheme, it sounds like a bug
