### ISSUE TITLE
How can we add custom index template to existing OCP's EFK stack ?

### ISSUE THREAD

**Issue by bysnupy** [openshift/origin-aggregated-logging#1593]
As written in the title, how can we add custom index template to existing EFK stack ?

AFAIK, OCP's EFK stack is configured for only cluster's log management, so it did not allow index template custom. But if I was mistaken about it, please let me know the custom guidance.

* OCP version: v3.11

Thanks,
Daein

**Comment by bysnupy** [comment]
Sorry ignore kindly this issue.

**Comment by richm** [comment]
Elasticsearch - add fields to index template
https://github.com/richm/docs/releases/tag/20180904175002
