### ISSUE TITLE
Connect Grafana to ElasticSearch

### ISSUE THREAD

**Issue by sghosh151** [openshift/origin-aggregated-logging#1602]
With Openshift now including Prometheus and grafana components, it would be really useful to have Grafana be able to query ElasticSearch for integrated log + metrics view.

Limited to "operator" indices in ElasticSearch would be a great first step.

**Comment by arocki7** [comment]
Looking for the same.

**Comment by jcantrill** [comment]
@sichvoge Is this a feature we want to investigate?

**Comment by sichvoge** [comment]
Not at the moment. The Grafana instance we currently still ship is read-only anyways.
