### ISSUE TITLE
How non cluster-admin user can see all indexes

### ISSUE THREAD

**Issue by danilorsilva** [openshift/origin-aggregated-logging#1603]
Hello all, I have a custom index on elasticsearch inside okd 3.11.

The index name is different from the pattern "project.namespace.randomnumber", the name for my custom index is test.example.*

My problem is that only a user  with cluster-admin role can see this log on kibana.

- I tried to give admin role to a specific user on the namespaces's pod that generate this index without success.
- I tried to give cluster-reader role for this specific user without success.

I would like to give access for this index or all indexes for a specific user without use the cluster-admin role for this specific user. Anyone can help me?

**Comment by jcantrill** [comment]
This is outside the scope of using OKD cluster logging as its not intended to be anything other then an aggregated log store.  However, you may find [1] useful.  I would expect if you defined a role and mapping like:
```
example_role:
  cluster: [CLUSTER_MONITOR_KIBANA]
  indices:
    'test.example.*' :
       '*':
         '*': ALL
example_role:
   users: [*]
```
Additionally, you may need to edit the files in $HOME/sgconfig/ directly and then reseed 'oc exec -c elasticsearch $espod -- es_seed_acl`

[1] https://github.com/openshift/origin-aggregated-logging/blob/master/docs/access-control.md

**Comment by danilorsilva** [comment]
First of all, thanks for your time and attention.

In my case, is not a problem if a specific user can access all logs like admin user. So, can i just configure my user on mapping "sg_role_admin" ?

sg_role_admin:
  users:
    - 'CN=system.admin,OU=OpenShift,O=Logging'
    - 'CN=MYUSER,OU=OpenShift,O=Logging' (I dont know yet how to put my user info here in this section)

Another question: Is this will bypass the openshift rbac? Once i configure my user on sg_role_admin section, do i need to give any specific role for the user?

Thanks one more time.

**Comment by jcantrill** [comment]
> First of all, thanks for your time and attention.
> 
> In my case, is not a problem if a specific user can access all logs like admin user. So, can i just configure my user on mapping "sg_role_admin" ?
> 
> sg_role_admin:
> users:
> - 'CN=system.admin,OU=OpenShift,O=Logging'
This entry comes from the certs generated by the install process.
> - 'CN=MYUSER,OU=OpenShift,O=Logging' (I dont know yet how to put my user info here in this section)
This entry should match whatever the response is to 'oc whoam' which uses your token and returns the associated name.
> 
> Another question: Is this will bypass the openshift rbac? Once i configure my user on sg_role_admin section, do i need to give any specific role for the user?
You are fundamentally bypassing openshift RBAC as this particular role is left untouched. We otherwise dynamically build an cul roles for users based on their token
> 
> Thanks one more time.

**Comment by danilorsilva** [comment]
Okay. Please check if i have the correct understand:

I will not create a specif role for this user, i will use the existing role "sg_role_admin" on sgconfig/sg_roles_mapping.yaml.

I will configure my user like that:
```
sg_role_admin:
users:
- 'CN=system.admin,OU=OpenShift,O=Logging'
- 'CN=danilo,OU=OpenShift,O=Logging'
```
I will keep my user as cluster-reader once we are bypassing openshift rbac.
After that, do i need to restart elasticsearch pod ou execute any command to validate this operation?

**Comment by jcantrill** [comment]
``` oc exec -c elasticsearch $espod -- es_seed_acl```

will reseed the documents

**Comment by danilorsilva** [comment]
I am back @jcantrill ,I set up a new okd 3.11 standalone to validate this steps. Everything works fine, thank you so much!

Now, my question is: Once i have edited sgconfig/sg_roles_mapping.yaml , how can i make change permanent? Because if delete pod this file (sgconfig/sg_roles_mapping.yaml) will be overwrite with the initial configurations.

**Comment by jcantrill** [comment]
Only by extracting the '$HOME/sgconfig' dir to a configmap and mounting it to the deploymentconfig which will go away everytime you run ansible

**Comment by danilorsilva** [comment]
I did it. I created a config map for sgconfig and put all the 5 files on this config map. Everything works fine.

Thank you so much @jcantrill

**Comment by danilorsilva** [comment]
@jcantrill Solved my problem. Closed.
