### ISSUE TITLE
Elasticsearch's run.sh does not set heap size at all

### ISSUE THREAD

**Issue by ibotty** [openshift/origin-aggregated-logging#161]
ES_JAVA_OPTS is not exported, so the elasticsearch start script does not even see the options set there.
Also, it configures elasticsearch to use a variable amount of Ram (-Xms512m -Xmx$HALF_THE_RAM). Elasticsearch's [heap sizing guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html#_give_half_your_memory_to_lucene) recommends to set them to the same value, or better: set `ES_HEAP_SIZE`.

When this is fixed, it might possibly conflict with options set in `elasticsearch.in.sh`. That should be checked.

**Comment by ewolinetz** [comment]
I'd agree that ES_JAVA_OPTS not being available to the ES start script is an issue.

However, I'm a little hesitant to follow their sizing guide verbatim in this case given that it is running within a container and may need to share resources with other applications on a given OpenShift node.  We will probably need to do some performance tests surrounding that to know if the trade off of having the JVM grow vs starving other applications or if there isn't enough memory to allocate initially on the node is worth it.

**Comment by jcantrill** [comment]
I agree with @ewolinetz that in the environment in which we intend ES to operate it does not make sense for us to pre-allocate the memory by setting the min and max heap size to be the same.  Ideally, it would be nice if we could configure the JVM to return memory that is not being utilized in order that it could be allocated to other containers on the node.

**Comment by sosiouxme** [comment]
I have no problem with explicitly exporting the value, but it seems to work somehow without. Here's the cmdline from a running logging ES in a container:

`    7 ?        Sl     1:54 /bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Xms128M -Xmx4096m -Delasticsearch -Des.foreground=yes -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.5.2.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch`

The first set of memory settings on the line is misleading, being overridden by the configured settings later.

I also don't think we want to fully expand the memory usage at the start. Java will generally do a good job of that as needed, and we don't particularly want to request 4G RAM on simple demos where folks don't know to specify the setting and have it crash out of the box.

**Comment by ibotty** [comment]
Well. it does not work here. I have no Idea how it could if you did not (implicitly) exported ES_JAVA_OPTS. Maybe you have it set as env variable in the pod definition.

```
sh-4.2$ echo $INSTANCE_RAM 
8G
sh-4.2$ ps aux|grep java          
1000050+      7 34.2 12.4 3992164 963596 ?      Sl   14:15 103:00 /bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.5.2.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch
1000050+   8411  0.0  0.0   9036   672 ?        S+   19:16   0:00 grep java
```

**Comment by ibotty** [comment]
A better test:

```
< /proc/7/environ xargs -0n 1|grep JAVA
```
where 7 is the pid of all my elasticsearch java processes in various logging-es containers.

**Comment by sosiouxme** [comment]
@ibotty my apologies, you are quite right. I was testing with my PR https://github.com/openshift/origin-aggregated-logging/pull/156 where apparently I made this change long ago and forgot about it. If that merges tonight, it'll be fixed, otherwise I'll just merge your change for a short-term fix.

**Comment by ibotty** [comment]
No harm done!

I looked at upstreams script and it exec's elasticsearch. So my second commit introduces a functional change in that elasticsearch is going to be pid 1.
