### ISSUE TITLE
dynamic target_index_key

### ISSUE THREAD

**Issue by Zephery** [openshift/origin-aggregated-logging#1647]
how to realize dynamic es target_index_key?

**Comment by richm** [comment]
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/output-es-config.conf#L9

You need to set the field `viaq_index_name` to your desired index name.  Keep in mind that this will probably cause problems with the logging pipeline, depending on what you are trying to do.
