### ISSUE TITLE
Add dynamic volume provisioning

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#165]
Ref https://github.com/openshift/origin-metrics/pull/138

**Comment by jcantrill** [comment]
cc @detiber

**Comment by sosiouxme** [comment]
https://github.com/openshift/origin-aggregated-logging/pull/168

**Comment by sosiouxme** [comment]
ES_PVC_DYNAMIC

**Comment by jcantrill** [comment]
Do we need  a README update?

**Comment by sosiouxme** [comment]
well, yes.
