### ISSUE TITLE
Allow prometheus to access index-level metrics release 3.11

### ISSUE THREAD

**Issue by Reamer** [openshift/origin-aggregated-logging#1653]
Hi,
I get with the newest Elasticsearch image build from branch release-3.11, the same error, which is describe in RedHat bugzilla (https://bugzilla.redhat.com/show_bug.cgi?id=1706478). Openshift-Logging Project is created with newest ansible-openshift branch release-3.11.

The commit https://github.com/openshift/origin-aggregated-logging/commit/998495784bb3403f4594afcc278a9650b55aeb98 on master fixed the problem also in release-3.11. It would be nice, if we merge this commit also into branch release-3.11.

Commit https://github.com/openshift/origin-aggregated-logging/commit/e29f7e717244041971f25be6618768f962560e79 introduced token authentication.

Best Regards
Reamer

**Comment by richm** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1712423

**Comment by Reamer** [comment]
Pull request https://github.com/openshift/origin-aggregated-logging/pull/1672/files has fixed this issue.
