### ISSUE TITLE
Allow buffer config options for fluentd remote syslog

### ISSUE THREAD

**Issue by blofroth** [openshift/origin-aggregated-logging#1655]
We had some performance issues with Fluentd in Openshift v3.11 when sending to a remote syslog server and experimented with different options for increasing throughput. One option that seemed to help was setting "num_threads" in Fluentd 0.12.
https://docs.fluentd.org/v/0.12/output#num_threads

I could contribute our changes as a PR, but it seems the configuration structure has changed in the Fluentd 1.x that is used on master:
https://docs.fluentd.org/buffer#configuration-example
https://docs.fluentd.org/output#flush_thread_count

It seems a <buffer> tag now is needed to provide that config. Otherwise the option could be added easily at
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/generate_syslog_config.rb#L24

**Comment by richm** [comment]
submit a PR for the release-3.11 branch if you like, and we'll port it to master.  I suggest you make the thread count settable via an env var, as in https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/output-es-config.conf#L35

**Comment by jcantrill** [comment]
@richm This should maybe be a config option on the CR that is consumed during config generation?
