### ISSUE TITLE
Leverage Interpod Anti-affinity on ES pods.

### ISSUE THREAD

**Issue by timothysc** [openshift/origin-aggregated-logging#167]
For fault tolerance and disk utilization issues, the ES pods should aim to leverage inter-pod anti-affinity. 
https://github.com/kubernetes/kubernetes/blob/master/docs/design/podaffinity.md

In general this should almost be a requirement for Pet-Sets.

/cc @rflorenc @richm

**Comment by jcantrill** [comment]
Resolved with https://github.com/openshift/openshift-ansible/pull/7864
