### ISSUE TITLE
Elasticsearch fails to start on origin 3.11 cluster

### ISSUE THREAD

**Issue by benscottub** [openshift/origin-aggregated-logging#1687]
When attempting to deploy EFK stack in openshift origin 3.11, the logging-es-data-master deployment fails to successfully deploy the elasticsearch pod. Looking into the pod, the proxy container starts and passes its readiness check but the elasticsearch container does not. Here is the entire log output of the elasticsearch container at deployment. It hangs in this state and eventually the deployment times out and cancels. 
```
[2019-07-09 13:30:05,954][INFO ][container.run            ] Begin Elasticsearch startup script
[2019-07-09 13:30:06,030][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
[2019-07-09 13:30:06,031][INFO ][container.run            ] Inspecting the maximum RAM available...
[2019-07-09 13:30:06,034][INFO ][container.run            ] ES_JAVA_OPTS: ' -Xms3814m -Xmx3814m'
[2019-07-09 13:30:06,035][INFO ][container.run            ] Building required jks files and truststore
[2019-07-09 13:30:06,047][INFO ][container.run            ] Checking if Elasticsearch is ready
[2019-07-09 13:30:06,054][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
[2019-07-09 13:30:06,055][INFO ][container.run            ] ES_JAVA_OPTS: ' -Xms3814m -Xmx3814m -XX:HeapDumpPath=/elasticsearch/persistent/heapdump.hprof -Dsg.display_lic_none=false -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.type=unpooled'

### LICENSE NOTICE Search Guard ###

If you use one or more of the following features in production
make sure you have a valid Search Guard license
(See https://floragunn.com/searchguard-validate-license )

* Kibana Multitenancy
* LDAP authentication/authorization
* Active Directory authentication/authorization
* REST Management API
* JSON Web Token (JWT) authentication/authorization
* Kerberos authentication/authorization
* Document- and Fieldlevel Security (DLS/FLS)
* Auditlogging

In case of any doubt mail to <sales@floragunn.com>
###################################
Consider setting -Djdk.tls.rejectClientInitiatedRenegotiation=true to prevent DoS attacks through client side initiated TLS renegotiation.

### LICENSE NOTICE Search Guard ###

If you use one or more of the following features in production
make sure you have a valid Search Guard license
(See https://floragunn.com/searchguard-validate-license )

* Kibana Multitenancy
* LDAP authentication/authorization
* Active Directory authentication/authorization
* REST Management API
* JSON Web Token (JWT) authentication/authorization
* Kerberos authentication/authorization
* Document- and Fieldlevel Security (DLS/FLS)
* Auditlogging

In case of any doubt mail to <sales@floragunn.com>
###################################
Consider setting -Djdk.tls.rejectClientInitiatedRenegotiation=true to prevent DoS attacks through client side initiated TLS renegotiation.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder  for further details.
[2019-07-09 13:35:40,280][ERROR][container.run            ] Timed out waiting for Elasticsearch to be ready
cat: elasticsearch_connect_log.txt: No such file or directory
```

The elasticsearch image is "docker.io/openshift/origin-logging-elasticsearch:v3.11". I have tried completely deleting the openshift-logging project and redeploying EFK using the config.yml ansible playbook with the same result. Checking metrics shows that the elasticsearch container grows up to approx 4 Gb in the first minute or so of deploying and then plateaus there. There is no quota or resource limit on this project that would constrain it. Here is the relevant section of the inventory file I used for the ansible playbook. The openshift-logging project shows that a corresponding PVC was bound to a PV as the inventory file specifies.

```
openshift_logging_image_version=v3.11
openshift_logging_use_ops=false
openshift_logging_master_url=https://osmdev.acsu.buffalo.edu
openshift_logging_public_master_url=https://webappsdev.acsu.buffalo.edu
openshift_logging_install_logging=true
openshift_logging_kibana_hostname=logs.osndev.acsu.buffalo.edu
openshift_logging_es_memory_limit=8G
openshift_logging_es_cluster_size=1
openshift_logging_es_pvc_size=10Gi
openshift_logging_es_pvc_prefix=logging-es-
openshift_logging_es_nodeselector={"region": "infra"}
```

Thank you for any guidance you can provide.

**Comment by richm** [comment]
Did this previously work?  If so, when did it stop working?

If you use the logs command, does it give you more information?
`oc exec -c elasticsearch $espod -- logs` ?

**Comment by benscottub** [comment]
Hi Rich, Thanks for the quick response. I'm not exactly sure when it stopped working. That command did produce a lot more logs including java exceptions and stack traces. It looks cert related, I have attached the logs here. 
[es_logs.txt](https://github.com/openshift/origin-aggregated-logging/files/3373776/es_logs.txt)

I was under the impression that the ansible playbook would generate its own self signed certs so I'm confused why the logs show this:

```
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

...
[2019-07-09T13:30:20,812][ERROR][c.f.s.h.SearchGuardHttpServerTransport] [logging-es-data-master-l5fhviab] SSL Problem Received fatal alert: certificate_expired
javax.net.ssl.SSLException: Received fatal alert: certificate_expired
```

I checked the master certificates that we reference elsewhere in the inventory file and they are all valid for several more years, IE:

```
openshift_master_overwrite_named_certificates=true
openshift_master_named_certificates=[{" removed stuff here " }]
openshift_hosted_router_certificate={" removed stuff here " }
```

Is there an additional flag we need to give elasticsearch in the ansible inventory to regenerate the certs? There is a playbook "redeploy-certificates.yml" mentioned in the docs at https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#fluentd-redeploy-certs but it doesn't seem to exist in the openshift-logging playbook directory. 

```
[bens@osmdev1 ~]$ ls -la /usr/share/ansible/openshift-ansible/playbooks/openshift-logging/
total 16
drwxr-xr-x.  3 root root   69 Jul  3 13:28 .
drwxr-xr-x. 38 root root 4096 Dec 28  2018 ..
-rw-r--r--.  1 root root   25 Jul  3 15:38 config.retry
-rw-r--r--.  1 root root  429 Dec  3  2018 config.yml
-rw-r--r--.  1 root root  207 Dec  3  2018 OWNERS
drwxr-xr-x.  2 root root   35 Dec 28  2018 private
```

**Comment by benscottub** [comment]
I grabbed the latest release-3.11 code, deleted the openshift-logging project and re-deployed from the config.yml script there. I am having the same result when I tap into the logs of the ES pod which I have attached here:

[es_logs.txt](https://github.com/openshift/origin-aggregated-logging/files/3374438/es_logs.txt)

I do see that there is a redeploy certificates playbook in the git repo, but it can't run unless the elasticsearch cluster actually comes up first (it crashes on checking the ES status).

I have also attached the ansible inventory file just in case it has some pertinent information I'm missing. 
[dev311.txt](https://github.com/openshift/origin-aggregated-logging/files/3374475/dev311.txt)

**Comment by richm** [comment]
> I grabbed the latest release-3.11 code, deleted the openshift-logging project and re-deployed from the config.yml script there.

That might not be sufficient.  logging keeps certs and cert files in `/etc/origin/logging` - you might need to remove those as well before re-deploying

**Comment by benscottub** [comment]
Thanks Rich, that's exactly the info I was missing. I deleted that directory and redeployed and elasticsearch starts up properly now.

**Comment by richm** [comment]
> Thanks Rich, that's exactly the info I was missing. I deleted that directory and redeployed and elasticsearch starts up properly now.

Is there a problem with the openshift-ansible 3.11 rpm package?
