### ISSUE TITLE
Missing '@' in front of kubernetes_metadata plugin in 3.11

### ISSUE THREAD

**Issue by dmilde** [openshift/origin-aggregated-logging#1709]
fluentd/configs.d/openshift/filter-k8s-meta.conf:

<filter kubernetes.**>
  type kubernetes_metadata
  ...
</filter>

Should be '@type kubernetes_metadata'.
Seems fixed in more recent releases.

**Comment by richm** [comment]
3.11 still uses fluentd 0.12 - is this an issue with 0.12?

**Comment by dmilde** [comment]
Should just be a typo -> missing @

**Comment by richm** [comment]
> Just a typo -> missing @-sign
> This should not work?

3.11 still uses fluentd 0.12 - is this an issue with 0.12?
