### ISSUE TITLE
Only getting logs for one container, though requesting for others

### ISSUE THREAD

**Issue by sspeiche** [openshift/origin-aggregated-logging#171]
I'm running with internal cluster, I'm navigating from the web console into the archive but it is showing the wrong pods.

Running version: 
OpenShift Master: v3.2.1.1-1-g33fa4ea
Kubernetes Master: v1.2.0-36-g4a3f9c5

Requesting archive logs for pod: jenkins-1-fkwkz 

URL that web console is generating: 

```
#/discover?_g=(time:(from:now-1w,mode:relative,to:now))&_a=(columns:!(kubernetes_container_name,jenkins),index:'sspeiche-test2.dde0388e-3338-11e6-8212-0a49376ec1e3.*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'kubernetes_pod_name:%20jenkins-1-fkwkz%20%26%26%20kubernetes_namespace_name:%20sspeiche-test2')),sort:!(time,desc))
```

Query that shows in Kibana:

```
kubernetes_pod_name: jenkins-1-fkwkz && kubernetes_namespace_name: sspeiche-test2
```

but only seeing mongodb logs:

![screen shot 2016-06-16 at 10 13 14 am](https://cloud.githubusercontent.com/assets/727196/16119780/fb94f82e-33aa-11e6-9bf6-068d73ff0605.png)

@kwoodson Could you provide logs from the node that this pod (jenkins-1-fkwkz) is running? /var/log/message/*.log.pos

**Comment by ewolinetz** [comment]
Per the Apache Lucene query page[1], it makes mention that only terms immediately proceeding a `:` are used for that field search.  Within the Discover tab that you show above, can you update your query to be the following and see if it returns more accurate results?
`kubernetes_pod_name:"jenkins-1-fkwkz" AND kubernetes_namespace_name:"sspeiche-test2"`

[1] https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/1.7//query-dsl-query-string-query.html#query-string-syntax

**Comment by sspeiche** [comment]
@ewolinetz I tried this difference and same result, I will have to dig into the query syntax

@benjaminapetersen Have you seen this? Sam pointed me your way

It sure would be nice if kibana gave some syntax help, even if just a popup guide

**Comment by ewolinetz** [comment]
@sspeiche @benjaminapetersen it looks like this is still with the older console version.  The archive link wasn't using an index name with a UUID in it, and the query wasn't structured as it is now per https://github.com/openshift/origin-web-console/pull/274.

I created https://github.com/openshift/origin-kibana/issues/24 for adding some links to help with learning the Kibana experience/query syntax

**Comment by jcantrill** [comment]
@sspeiche @benjaminapetersen @ewolinetz  are we able to confirm that #openshift/origin-web-console/pull/274 resolved this issue so we can close?

**Comment by richm** [comment]
It has been resolved
