### ISSUE TITLE
When does the ES Image Tag v3.11 on Docker hub gets updated with the latest changes

### ISSUE THREAD

**Issue by normanschlatter** [openshift/origin-aggregated-logging#1724]
Question @ Title

thanks

**Comment by jcantrill** [comment]
Images are no longer published to a publicly accessible respository. You will need to build the images yourself.

**Comment by richm** [comment]
3.11 images are now being published to quay.io and docker.io.  We strongly recommend using quay.io

@sradco

```
>skopeo inspect docker://quay.io/openshift/origin-logging-fluentd:v3.11 | more
...
        "vcs-ref": "e4084a56ce97e3bdd84441fc488bf8ab249ef896",
```
https://github.com/openshift/origin-aggregated-logging/commit/e4084a56ce97e3bdd84441fc488bf8ab249ef896

**Comment by richm** [comment]
@normanschlatter ^^^
