### ISSUE TITLE
Compatibility of hack scripts with MacOS

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#1729]
I am running into some issues with some scripts when run on MacOS.
One examples is found in [hack/get-cluster-run-tests.sh#L121](https://github.com/openshift/origin-aggregated-logging/blob/8502b3aae46f8c7c3f5e08ee258e2880911eea58/hack/get-cluster-run-tests.sh#L121) where I run into:
```
++ mktemp --tmpdir -d logging-XXXXXXXXXX
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
+ workdir=
```
The `mkdir` does not support `--tmpdir` option on MacOS. There may be way to fix it, see https://stackoverflow.com/a/31397073. For now the workaround is to setup `$WORKDIR` manually.

**Comment by jcantrill** [comment]
@lukas-vlcek is there any more to add or can we close this issue?  Do you have a PR you wish to resolve?

**Comment by lukas-vlcek** [comment]
@jcantrill I think there are may be more examples of code that would not work correctly on other platforms. If we officially support other platforms then I can go and prepare PR for this case and I will be reporting other cases if I run into them. If we, however, do not support other platforms then we can close it.

**Comment by jcantrill** [comment]
> @jcantrill I think there are may be more examples of code that would not work correctly on other platforms. If we officially support other platforms then I can go and prepare PR for this case and I will be reporting other cases if I run into them. If we, however, do not support other platforms then we can close it.

This scripts are basically for our development purposes.  Add the PRs you require otherwise I would close this issue
