### ISSUE TITLE
support adding custom labels in Kibana console

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin-aggregated-logging#174]
Hi , is there a way we can add custom labels to be displayed in Kibana console? I need to add more things to be displayed. Is it possible?

**Comment by richm** [comment]
@priyanka5 I'm not sure what you mean.  Can you be more specific?  Do you want to be able to add custom tags to certain logs in fluentd so that those tags show up in kibana?

**Comment by jcantrill** [comment]
@priyanka5 please reopen if you need additional information.
