### ISSUE TITLE
0010-seed-acl _always_ seeds acls

### ISSUE THREAD

**Issue by scne59** [openshift/origin-aggregated-logging#1760]
I recently noticed that [/usr/share/elasticsearch/init/0010-seed-acl](https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/init/0010-seed-acl) does **always**  (re-)seed the acl documents with es_seed_acl command.
IMHO the algorithm is somehow twisted. I think it should only seed if either FORCE_SEED_ACL is set or any ACL document is missing.

It should really first check "force" with "-z" and if true check the acls documents.
If any document is missing it correctly sets force="true"
The last part should then check with "-n" if a (re-)seed is necessary.

The `resp=$(es_util --query=${index}/$d/0 -w %{response_code} | cut -d '}' -f2)` will also never find a document because it matches the empty string even if the document exists (output ends with somethin like "fQp9"}}200").
Should be "-f3" then.

**Comment by richm** [comment]
Can you provide a reproduction scenario?

**Comment by scne59** [comment]
This should work on any EFK install that has 0010-seed-acl (it has been unchanged since it's first commit):
```
# prepare debug session
$ oc rsh -c elasticsearch logging-es-data-master-oysrxa7x-3-zh4z7
sh-4.2$ cd /tmp
sh-4.2$ cp /usr/share/elasticsearch/init/0010-seed-acl .
sh-4.2$ chmod +x 0010-seed-acl
 
# first call with default settings, acl seeding is enforced
sh-4.2$ ./0010-seed-acl
[2019-09-27 17:46:12,101][INFO ][container.run            ] Forcing the seeding of ACL documents
[2019-09-27 17:46:12,107][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
[2019-09-27 17:46:12,169][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
.
.searchguard index already exists, so we do not need to create one.
Populate config from /opt/app-root/src/sgconfig/
Will update 'config' with /opt/app-root/src/sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with /opt/app-root/src/sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with /opt/app-root/src/sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with /opt/app-root/src/sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with /opt/app-root/src/sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success
/tmp
[2019-09-27 17:46:16,886][INFO ][container.run            ] Seeded the searchguard ACL index
.
 
# setting FORCE_SEED_ACL to true reveals syntax error in line #29
sh-4.2$ export FORCE_SEED_ACL=true
sh-4.2$ ./0010-seed-acl
./0010-seed-acl: line 29: [: missing `]'
 
# fix the error
sh-4.2$ sed -i  's/200\"\]/200\" \]/' 0010-seed-acl
 
# restart fixed script, now it thinks the "roles" document is missing but it actually exists
sh-4.2$ ./0010-seed-acl
.
[2019-09-27 17:52:47,965][INFO ][container.run            ] Missing ACL document 'roles'. Reseeding all ACL documents
.
sh-4.2$ es_util --query=.searchguard/roles/0
{"_index":".searchguard","_type":"roles","_id":"0","_version":120,"found":true,"_source":{"roles":"###base64####"}}sh-4.2$
 
# fix the error
sh-4.2$ sed -i 's/-f2/-f3/' 0010-seed-acl
 
# restart fixed script, now it finds the docs but doesn't re-seed (but FORCE_SEED_ACL is still set!)
sh-4.2$ ./0010-seed-acl
sh-4.2$
 
# modify control flow logic
sh-4.2$ sed -i -e '0,/ -z / s// -n /' -e '0,/ -n / s// -z /' 0010-seed-acl
 
# restart fixed script, now it enforces acl seeding
sh-4.2$ ./0010-seed-acl
[2019-09-28 10:47:53,720][INFO ][container.run            ] Forcing the seeding of ACL documents
[2019-09-28 10:47:53,738][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
[2019-09-28 10:47:53,799][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
.
[2019-09-28 10:48:00,806][INFO ][container.run            ] Seeded the searchguard ACL index
.
 
# unset FORCE_SEED_ACL and restart, no acl seeding happening
sh-4.2$ export FORCE_SEED_ACL=''  
sh-4.2$ ./0010-seed-acl
sh-4.2$
 
# remove roles document and restart, missing "roles" document is detected and acl seeding is enforced
sh-4.2$ es_util --query=.searchguard/roles/0 -XDELETE
{"found":true,"_index":".searchguard","_type":"roles","_id":"0","_version":2750,"result":"deleted","_shards":{"total":2,"successful":2,"failed":0}}sh-4.2$
sh-4.2$ ./0010-seed-acl
[2019-09-28 10:51:16,214][INFO ][container.run            ] Missing ACL document 'roles'. Reseeding all ACL documents
[2019-09-28 10:51:16,219][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
[2019-09-28 10:51:16,281][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
.
[2019-09-28 10:51:21,857][INFO ][container.run            ] Seeded the searchguard ACL index
.
```
There is a Red Hat [case](https://access.redhat.com/support/cases/#/case/02482443) for this.
The fix is [here](https://github.com/scne59/origin-aggregated-logging/commit/3a81c9b95160714907ef51409de11022e065c9e8#diff-4aa1053df24cb2f5e18ec0734412939a)

**Comment by jcantrill** [comment]
@scne59 please provide an actual PR

**Comment by richm** [comment]
> @scne59 please provide an actual PR

I'm working on one.  I found some problems with our usage of curl.

**Comment by richm** [comment]
https://github.com/openshift/origin-aggregated-logging/pull/1761

**Comment by richm** [comment]
@scne59 We _always_ want to re-seed acls, in case we provide new acls in an update.  Is there some usage that you require that you _do not_ want to always re-seed the acls?  For example, are you manually editing the roles, rolesmapping, etc. for some reason, and you want to preserve these updates when elasticsearch is restarted?

**Comment by scne59** [comment]
Hi Rich,

yes, I had tried to manually "fix" the [root url problem](https://github.com/openshift/origin-aggregated-logging/issues/1641) for our elastalert running on 3.11.82 by modifying the action_groups until we can upgrade to a fixed OCP version.
I was a bit surprised that the documents where changed to their defaults after a while.
Maybe we should change the env var to something like DISABLE_ACL_SEEDING and leave it unset.
Always seeding the acls was the default behaviour before the init scripts where introduced.
For the root url problem I have now replaced the sg_action_grous.yml with a configmap subPath mount.

KR,
 Jochen

**Comment by richm** [comment]
@scne59 thanks - then - please check out my latest PR https://github.com/openshift/origin-aggregated-logging/pull/1761 - basically, you would need to set `FORCE_SEED_ACL=false`, and then elasticsearch will not attempt to reseed unless there is a missing acl doc.

**Comment by scne59** [comment]
Yep, got it. Looks good to me.
