### ISSUE TITLE
need docs on using "custom" ssl certificates for fluentd, elasticsearch, etc

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-aggregated-logging#18]
some people will want to use their own SSL certs for the "internal" communication between fluentd and elasticsearch.

Currently the docs clearly illustrate how to do this for Kibana itself, but not for the internal communications. Talking with @sosiouxme on the phone we determined this is "as easy as" replacing the secrets after they are generated, but this needs to be documented somehow.

**Comment by sosiouxme** [comment]
If you look at the contents of a secret, it is just key-value pairs where the values are base64 encoded. So all you need to do to replace a value is base64 encode your value (e.g. `base64 < foo.crt`),  `oc edit secret bar` to replace the encoded value, and redeploy your pods. It's easy enough, but annoying to describe. And we should document the secrets, their contents, and what uses them.

**Comment by richm** [comment]
What is the status of this issue?  Did we ever document this?

**Comment by sosiouxme** [comment]
I'm fairly sure not...

On Fri, Jun 10, 2016 at 3:09 PM, Richard Megginson <notifications@github.com

**Comment by ewolinetz** [comment]
We did not, I can start on this
