### ISSUE TITLE
Utility fluent sanitizer

### ISSUE THREAD

**Issue by v4mpir0ck** [openshift/origin-aggregated-logging#1803]
Hello,

i cant figure it out how to use sanitizer util to clean file buffers
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/utils/sanitize_msg_chunks
someone can explain?
thanks,
Regards

**Comment by jcantrill** [comment]
> Hello,
> 
> i cant figure it out how to use sanitizer util to clean file buffers
> https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/utils/sanitize_msg_chunks
> someone can explain?
> thanks,
> Regards

https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/utils/sanitize_msg_chunks#L27

You pass it a directory of buffers and it creates new buffers that can be ingested by fluent
