### ISSUE TITLE
Custom logging configuration not working in OKD3.11 - no patterns matched tag="test.cycle"

### ISSUE THREAD

**Issue by imranrazakhan** [openshift/origin-aggregated-logging#1812]
I want to add additional input plugin for EFK logging but its not working.

**_Steps To Reproduce_**

Create following files and updated **logging-fluentd** configmap

**input-http-application.conf**
```
<source>
  @type http
  port 8888
  bind 0.0.0.0
</source>
```

**output-http-application.conf**
```
<match test.cycle>
  @type stdout
</match>
```

change **fluent.conf** like below
....
```
# sources
# ordered so that syslog always runs last...
@include configs.d/user/input-http-application.conf
@include configs.d/openshift/input-pre-*.conf
@include configs.d/dynamic/input-docker-*.conf
@include configs.d/dynamic/input-syslog-*.conf
@include configs.d/openshift/input-post-*.conf
#
```
....
```
<label @OUTPUT>
# matches
  @include configs.d/user/output-http-application.conf
  @include configs.d/openshift/output-pre-*.conf
  @include configs.d/user/output-operations.conf
  @include configs.d/openshift/output-applications.conf
  # no post - applications.conf matches everything left
#
</label>
```
....

Now i when i am trying following 
`curl -i -X POST -d 'json={"action":"logout","user":2}' http://localhost:8888/test.cycle`

its giving error  

`2020-01-03 16:48:17 -0500 [warn]: no patterns matched tag="test.cycle"`

In **/var/log/fluentd/fluentd.log** i can see its adding this match
`2020-01-03 16:47:42 -0500 [info]: adding match in @OUTPUT pattern="test.cycle" type="stdout"`

**Comment by jcantrill** [comment]
This is not a supported usecase for OKD cluster logging, but you have no routing that ship the message to the `OUTPUT` label

**Comment by YevheniiKokhanevych** [comment]
Hi,
Could you please, provide information when docker image openshift/origin-logging-fluentd:v3.11.0 will be stable? Last time, it is updated very often, with a different version of fluentd inside of the container.

**Comment by jcantrill** [comment]
> Hi,
> Could you please, provide information when docker image openshift/origin-logging-fluentd:v3.11.0 will be stable on DockerHub? Last time, it is updated very often, with a different version of fluentd inside of the container.

I'm not certain we still push images to dockerhub.  Please look at quay.io
