### ISSUE TITLE
missing input-pre-audit-log.conf and filter-pre-a-audit-exclude.conf in configs.d

### ISSUE THREAD

**Issue by aelicieguo** [openshift/origin-aggregated-logging#1865]
In run.sh there is:

if [ "${AUDIT_CONTAINER_ENGINE:-}" = "true" ] ; then
    cp -f $CFG_DIR/input-pre-audit-log.conf $CFG_DIR/openshift
    cp -f $CFG_DIR/filter-pre-a-audit-exclude.conf $CFG_DIR/openshift
else
    touch $CFG_DIR/openshift/input-pre-audit-log.conf
    touch $CFG_DIR/openshift/filter-pre-a-audit-exclude.conf
fi

There should be input-pre-audit-log.conf and filter-pre-a-audit-exclude.conf files in configs.d so that these files are built into the image during docker build.

**Comment by jcantrill** [comment]
@aelicieguo in which version of logging are you referring?  We are in the process of moving to ClusterLogForwarder CR which began in 4.3 as TP.  The run script in this repo is no longer current.  Additionally, many of the capabilities that were enabled in the run.sh have been moved to config generation as part of ClusterLogForwarding
