### ISSUE TITLE
Feature request: Allow setting Fluentd's merge_json_log via container labels

### ISSUE THREAD

**Issue by dbluxo** [openshift/origin-aggregated-logging#1870]
The `merge_json_log` setting configures Fluentd to inspect each log message to determine if it's format is 'JSON' and to merge it into the JSON payload document posted to Elasticsearch. Nowadays this setting is `false` by default and is a change from 3.11 and earlier deployments where it was `true`. Also described in this [PR](https://github.com/openshift/cluster-logging-operator/pull/74/files).

While on the one hand activating the setting in some places can be very very helpful in evaluating logs, on the other hand you can run into some [problems](https://github.com/openshift/origin-aggregated-logging/issues/1492) because it is always a cluster-wide setting.

It would be great to have the possibility to label the containers with e.g. `openshift_merge_json_log=true`. In the filter pipeline, Fluentd would determine if the label is set and true (the Kubernetes metadata are well known to Fluentd), and only then would it perform a `merge_json_log`. For all other cases it would still be disabled.

The risks described would continue to exist. However, a user would have the possibility at application level to take this risk for his project in order to obtain a better evaluation of the log messages.

**Comment by jcantrill** [comment]
@sichvoge may wish to weigh in here but given where we are going with the current logstore, I lean to not enabling any form of merge_json_log.  It may be useful for some to accept the risk but ultimately when things go sideways it will be expected for us to figure out, understand why, and provide support.  I'm not inclined to add something that has the potential to destabilize the log store

**Comment by dbluxo** [comment]
> "[...] but given where we are going with the current logstore, I lean to not enabling any form of merge_json_log."

What do you mean? Where are you going to with the current logstore?
