### ISSUE TITLE
need docs on scaling elasticsearch

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-aggregated-logging#19]
we currently allude to some gotchas with scaling elasticsearch, but we may need to more explicitly document how to do it (simply).

**Comment by ewolinetz** [comment]
Docs were updated per https://github.com/openshift/openshift-docs/pull/2136

**Comment by ewolinetz** [comment]
it may also be good to note that we have https://github.com/openshift/origin-aggregated-logging/issues/151 to track creating some sort of scale up/down mode.  This _should_ all go away with the use of PetSets when available.
