### ISSUE TITLE
hack/logging-dump.sh script doesn't collect connectivity data for fluentd pods

### ISSUE THREAD

**Issue by cpassare** [openshift/origin-aggregated-logging#1964]
Hello,

the logging dump script doesn't collect connectivity data for fluentd pods.

More detailed, lines:

https://github.com/openshift/origin-aggregated-logging/blob/master/hack/logging-dump.sh#L162
https://github.com/openshift/origin-aggregated-logging/blob/master/hack/logging-dump.sh#L163

Don't collect elasticsearch host and port values.

Environment variables ES_HOST and ES_PORT are not present. 

Tried version Openshift 4.4

**Comment by jcantrill** [comment]
@cpassare pull requests are welcome.  though for master (4.6 and later) please make any requests against https://github.com/openshift/cluster-logging-operator/tree/master/must-gather  all others can be here against the respective branch like `release-4.5`
