### ISSUE TITLE
How to perform curl command to Secured ElasticSearch

### ISSUE THREAD

**Issue by SAbdulRahuman** [openshift/origin-aggregated-logging#1972]
Hi,
I have installed ElasticSearch in openshift-logging namespace in my openshift cluster.
I'm able to perform curl to elasticsearch using **bearer token**, now I want to perform curl to ElasticSearch using certs.

**CURL working with oc exec**
oc exec elasticsearch-cdm -- curl -tlsv1.2 --insecure -H "Authorization: Bearer $(token)" "https://172.30.245.25:9200/_cat/health"

CURL working with elasticsearch service route using **bearer token**
curl -tlsv1.2 --cacert -H "Authorization: Bearer $(token)"  https://$(esRoutes)/_cat/health

Now I want to perform curl using TLS certification, I have extracted secrets from running elasticsearch cluster and included the cert and key filename below,

**Certs and Keys:**
admin-ca  admin-cert  admin-key  elasticsearch.crt  elasticsearch.key  logging-es.crt  logging-es.key

How to perform CURL to running ElasticSearch (in openshift namespace opernshift-logging) using certs ?.

**Comment by jcantrill** [comment]
the admin certs can be used simply by exec'ing to the pod and using es_util
```
oc exec -c elasticsearch $pod -- es_util --query=_cat/health
```
See https://github.com/openshift/origin-aggregated-logging/tree/master/elasticsearch#es_util
