### ISSUE TITLE
Fluentd to external Elasticsearch stops sending logs

### ISSUE THREAD

**Issue by DavidHuntt** [openshift/origin-aggregated-logging#2033]
After some issues to get Fluentd and ES stable (thank you Jeff), I updated Fluentd to send logs to external log server (Nagios Log Server - ELK stack). Logs will send for a day then stop. There are no apparent errors that I can find. Restarting the logging-fluent daemon set restarts (without issue) but only a portion of nodes will resume sending logs. Not sure if I should stop the ES and Kibana pods. (Won't lie, getting +32Gb back in memory resources sure would be nice!)

Logging-fluend appended configuration;
```
            - name: USE_REMOTE_SYSLOG
              value: 'true'
            - name: REMOTE_SYSLOG_HOST
              value: IP member 2
            - name: REMOTE_SYSLOG_HOST_BACKUP
              value: IP member 2
            - name: REMOTE_SYSLOG_PORT
              value: '5544'
            - name: REMOTE_SYSLOG_PORT_BACKUP
              value: '5544'
            - name: REMOTE_SYSLOG_TYPE
              value: syslog
```

I did notice the appended configuration wasn't happy with a round-robin lookup for REMOTE_SYSLOG_HOST, so it was updated with each member IP separately.

**Comment by jcantrill** [comment]
What version of logging is this?

> After some issues to get Fluentd and ES stable (thank you Jeff), I updated Fluentd to send logs to external log server (Nagios Log Server - ELK stack). 

The external log server is an Elasticsearch cluster?  If so, have your reached the watermark thresholds where it stops accepting data?  This statement does not jive with enabling syslog unless they have some agent that accepts syslog anf further forwards to ES

**Comment by DavidHuntt** [comment]
3.11
`quay.io/openshift/origin-logging-fluentd v3.11.0 3643ce22b369 `

Watermark set at 90% and elasticsearch looks healthy
`/var/log/elasticsearch/f49b1b36-537c-44f7-803e-47799a7e1bf4.log:[2020-12-16 23:04:48,115][INFO ][cluster.routing.allocation.decider] [6ec96358-bce3-4fab-be93-f4b8d844100d] updating [cluster.routing.allocation.disk.watermark.low] to [90%]`

**Comment by jcantrill** [comment]
> Watermark set at 90% and elasticsearch looks healthy
> `/var/log/elasticsearch/f49b1b36-537c-44f7-803e-47799a7e1bf4.log:[2020-12-16 23:04:48,115][INFO ][cluster.routing.allocation.decider] [6ec96358-bce3-4fab-be93-f4b8d844100d] updating [cluster.routing.allocation.disk.watermark.low] to [90%]`

Doesn't this speak to the setting not the actually amount of disk used?

**Comment by DavidHuntt** [comment]
So I reverted it back to the OKD EFK stack. It's running, looks good but not getting the logs. Did notice this in the pod logs
`'block' action stops input process until the buffer full is resolved`
Followed the steps to clear the /var/lib/fluentd files. No change in Kibana

If I open the kibana-ops UI I see logs, Opening kibana UI, nothing.
Before I start playing with the filters, shouldn't default config collect the logs?

**Comment by DavidHuntt** [comment]
To your previous about disk, though I've abandoned that for now, disk is fine, I'm using AWS storage through an AWS Storage Gateway Appliance with a 150GB cache. Monitoring that I'm not reaching anywhere near stressing it.

**Comment by DavidHuntt** [comment]
`/remove-lifecycle stale
`
Let me monitor this a bit longer and get back to you with any further concerns or comments. Thx!
