### ISSUE TITLE
Strings that contain numbers do not match number strings for which they are a substring

### ISSUE THREAD

**Issue by bdurrow** [openshift/origin-aggregated-logging#2034]
**Describe the bug**
As a admin_user (although this problem was brought to me by a project_user) when I use kibana to search for a number that I expect to find in the message field, results that I would expect to match do not.  For instance if I perform the following queries, the first produces no results but the second produces results (the second has an extra 1 at the beginning of 1234):
kubernetes.namespace_name:"foo" AND kubernetes.container_name.raw:"bar" AND message:"1234"
kubernetes.namespace_name:"foo" AND kubernetes.container_name.raw:"bar" AND message:"11234"

This is not expected behavior for myself or my users.  I would expect a string of numbers to behave in the same way that a string of alphas works.

**Environment**
OKD: 4.6.0-0.okd-2020-11-27-200126
clusterlogging.4.6.0-202010201329.p0
elasticsearch-operator.4.6.0-202010200139.p0.2

Kibana Image: registry.redhat.io/openshift4/ose-logging-kibana6@sha256:ef55bbd18acac7097227e347acd567dfe92a66d550ae6608b60b3ef17e80eac2
Elasticsearch Image: registry.redhat.io/openshift4/ose-logging-elasticsearch6@sha256:2f368a0e2cbfeaf6a287c40482f3ac4ebdfe17c82633f663ed72c3e9c06ee768
Fluentd Image: registry.redhat.io/openshift4/ose-logging-fluentd@sha256:15fe2c97e0810b950d95fdf618c6586850537c602bd618b1fe1eecaa554f2b17

**Logs**
I don't think that there are any logs relevant to this issue.  If you would like to see something please let me know.

**Expected behavior**
Searching for a string of numbers that are present in the message field should match as a substring as if they were alphas.

**Actual behavior**
No results were found unless the number matched exactly, for instance 1234 would not match if the message has 11234 in the text.

**To Reproduce**
1. Open Kibana
2. Find a document that has a number of at several digits (for instance 1234567)
3. Search for that number omitting the first digit (for instance 234567)

**Additional context**

**Comment by jcantrill** [comment]
> **Describe the bug**
> For instance if I perform the following queries, the first produces no results but the second produces results (the second has an extra 1 at the beginning of 1234):
> kubernetes.namespace_name:"foo" AND kubernetes.container_name.raw:"bar" AND message:"1234"
> kubernetes.namespace_name:"foo" AND kubernetes.container_name.raw:"bar" AND message:"11234"

You are stating you have a record with a number represented as a string. That record contains the message field of "11234".  You would expect it will return all records with the sequence: "1234" in them.

Regardless of your ask, I would encourage you to peruse the Elastic.co documention and forums as we are doing nothing special to the actual store or query capabilites that would alter Elastic's general behavior
