### ISSUE TITLE
Consume the downward API for setting max heap used by ElasticSearch

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#214]
Add the downward API into the evaluation of setting max heap in follow-up to:

https://github.com/openshift/origin-aggregated-logging/commit/efb942bd74622cd07c0be63344f4225a45405e32

**Comment by ewolinetz** [comment]
Would we need that information be exposed on the downward api? it doesn't look like there's anything in there currently that will tell us information about our host (such as RAM) [1]

[1] https://docs.openshift.org/latest/dev_guide/downward_api.html

**Comment by jcantrill** [comment]
closing without prejudice. At some point we introduced setting an ENV var via the downward api
