### ISSUE TITLE
Clean up old searchguard indices

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#225]
We currently don't curate the searchguard indices we create -- curator is configured to exclude them so we don't delete ones currently in use.

Since we create an index per elasticsearch node, whenever it starts up that can add up quickly.

We can probably configure it when we are scaling down the cluster, after Kibana, Fluentd, and Curator are stopped; issue a delete on all .searchguard.\* indices before stopping ES too.

**Comment by jcantrill** [comment]
2.x code base moved to one index per DC name instead of podname;  5.x codebase uses a single index for the cluster
