### ISSUE TITLE
README link to fluentd component outdated

### ISSUE THREAD

**Issue by pfeifferj** [openshift/origin-aggregated-logging#2264]
**Describe the bug**
The reference to fluentd in the [README](https://github.com/openshift/origin-aggregated-logging/tree/master#fluentd) is outdated and should probably point to [https://github.com/fluent/fluentd](https://github.com/fluent/fluentd) instead.

**Comment by jcantrill** [comment]
@pfeifferj pull requests are welcome.  Note this repo is under limited development and fluentd changes have been moved to https://github.com/viaq/logging-fluentd
