### ISSUE TITLE
Some variable names mistakes in /deployer/scripts/install.sh, mix lower and upper case

### ISSUE THREAD

**Issue by harobed** [openshift/origin-aggregated-logging#228]
Some syntax mistakes in `/deployer/scripts/install.sh`:

* here https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/install.sh#L63 `es_pvc_size` is in lower case
* here https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/install.sh#L392 it is in uppercase

Same bug with:

* `es_pvc_prefix`
* `es_ops_pvc_size`
* `es_ops_pvc_prefix`

**Comment by jcantrill** [comment]
@ewolinetz something to review for the upgrade work.

**Comment by ewolinetz** [comment]
resolved with #229 thanks!
