### ISSUE TITLE
Update Kibana mappings to use datetime format

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#231]
using a wildcard such as `logging.{uuid}.*` for a Kibana index template isn't optimal since Kibana would still need to query all indices to know the correct date range.

Kibana has a means to make this more efficient if we use the format like `[logging.{uuid}.]YYYY.MM.DD`.
Anything within "[ ]" is considered static and then YYYY.MM.DD will be expanded to actual date values when being used as an index for querying.

This came out of our discussions with Peter Portante.

**Comment by jcantrill** [comment]
closing without prejudice. I dont see us modifying the index-patterns anytime soon
