### ISSUE TITLE
Add other operations to Curator so it can do more than delete

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#232]
Currently we can only delete indices within Curator which may not work if we need to maintain logs for longer periods of time.
Adding `optimize` and `close` can help us extend the amount of time the data can stay around without ES trying to keep all that information in its heap.

**Comment by JayKayy** [comment]
+1 would very much like to see this.

**Comment by ewolinetz** [comment]
related trello:
https://trello.com/c/UlmNQ0Av/381-3-have-curator-optimize-yesterday-s-indices-logging

**Comment by jcantrill** [comment]
Closing since we are moving to rolling indices in 4.x
