### ISSUE TITLE
How to configure volume.alpha.kubernetes.io/storage-class: "static" in ES PVC ?

### ISSUE THREAD

**Issue by harobed** [openshift/origin-aggregated-logging#236]
How to configure "static" instead "dynamic" here:

```
        volume.alpha.kubernetes.io/storage-class: "dynamic"
```

https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/templates/support.yaml#L297

I suggest to append new config parameter ?

**Comment by jcantrill** [comment]
@pmorie  did you tell me in a conversation that the value for dynamic provisioning is immaterial?  It is the presence of the annotation that matters.  'Static' would imply removing the annotation all together and the admin explicitly setting up storage i believe.

**Comment by harobed** [comment]
Yes, it's to remove this annotation

**Comment by pmorie** [comment]
I don't understand exactly what the question is here.

**Comment by jcantrill** [comment]
@pmorie My question to you is: The value of this annotation is irrelevent correct?  Its the presence of the the annotation that enables dynamic provisioning.  Is that right?

@harobed I'm not certain what you are asking

**Comment by pmorie** [comment]
@jcantrill yes, for the alpha version of dynamic provisioning, the value of the annotation is meaningless.

**Comment by jcantrill** [comment]
@harobed please reopen if needed.
