### ISSUE TITLE
Make additional plugins available on Kibana|Elasticsearch images

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#237]
The Marvel plugin gives us the ability to view ES cluster health from Kibana and may be very useful to add for operations groups.
https://www.elastic.co/guide/en/marvel/current/introduction.html

We would need to verify how this would interact with searchguard and what roles we would want to have access to this (probably make it only available for cluster-admins)

**Comment by ewolinetz** [comment]
Marvel requires a license, we would need to find an open source alternative for this card...

**Comment by ewolinetz** [comment]
ElasticHQ[1] looks pretty promising, it wouldn't be viewable from Kibana necessarily though

[1] http://www.elastichq.org/index.html

**Comment by ewolinetz** [comment]
https://github.com/signalfx/collectd-elasticsearch was suggested by @portante

**Comment by lukas-vlcek** [comment]
1) We should not look at anything that is based on _site plugin architecture because this is not going to be supported starting with ES 5.x, see https://www.elastic.co/blog/running-site-plugins-with-elasticsearch-5-0

2) Having useful monitoring that stores data to ES means we will need to operate another ES cluster

**Comment by ewolinetz** [comment]
expanding this scope slightly to also include a head plugin: 'elasticsearch-head' or 'elasticsearch-kopf' -- whichever would work better for us.

**Comment by jcantrill** [comment]
@ewolinetz I thought we had issues using 'elasticsearch-head' because of the restrictions that searchguard adds

**Comment by ewolinetz** [comment]
@jcantrill with the new version of SG we may have more available to us; it would need to be investigated further

**Comment by portante** [comment]
The ["kopf" plugin](https://github.com/lmenezes/elasticsearch-kopf) is another really good one to include.  I have dropped using the "head" plugin in favor of that one.

**Comment by jcantrill** [comment]
closing without prejudice
