### ISSUE TITLE
Setting ENABLE_OPS_CLUSTER does not set ES_HOST correctly for kibana-ops DC

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#24]
Within the deployer script when set ENABLE_OPS_CLUSTER to true, we are not setting the value ES_HOST to point to the operations ElasticsSearch service.

**Comment by sosiouxme** [comment]
I think from fluentd https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/run.sh#L187 handles it. Are you saying kibana-ops ES_HOST isn't pointed at the ops ES? Maybe https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/run.sh#L188 needs adjustment.

**Comment by ewolinetz** [comment]
Correct, the value of ES_HOST for kibana-ops is incorrect.  That's the line I was looking at as well :+1:
