### ISSUE TITLE
Give ability to ingest Kubernetes events in Fluentd

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#244]
Provide this plugin to the Fluentd image and document how users can configure their Fluentd to use it:
https://github.com/ViaQ/fluent-plugin-openshift_metadata_input

There may need to be a stipulation on how many fluentd pods we have querying this at a time to reduce duplicate entries

**Comment by jcantrill** [comment]
Larger issue to consider is where this fits into the role of metrics and logging co-existing.  @richm we should discuss with Tushar and @rettori

**Comment by jcantrill** [comment]
cc @lukas-vlcek as maybe this also fits into some of the work you are doing know with performance monitoring.

**Comment by jcantrill** [comment]
@ewolinetz Did we resolve this with the implementation of https://trello.com/c/RXMD3VJZ/   Could probably use some improvement but the event router provides these bits I believe

**Comment by ewolinetz** [comment]
@jcantrill unfortunately, I'm not sure. But, yes, I believe that this is what the event router provides.

**Comment by aleks-mariusz** [comment]
could anyone provide some examples of how to confligure fluentd to ingest kubernetes events please ?

**Comment by jcantrill** [comment]
When installing logging using openshift-ansible set the var `openshift_logging_install_eventrouter` to `true` in your inventory.  This deploys the eventrouter to the default namespace where all events will be pushed to elasticsearch into the '.operations' indices.

**Comment by jcantrill** [comment]
Satisfied with the event router feature
