### ISSUE TITLE
Kibana pod crashes and shows "crash loop back off"

### ISSUE THREAD

**Issue by priyanka5** [openshift/origin-aggregated-logging#250]
Hi I am following document to setup EFK in origin 1.2.1 from document here:
https://docs.openshift.org/latest/install_config/aggregate_logging.html 

But kibana pod is crashing after each 1- 2 min with message:

```
{"name":"Kibana","hostname":"logging-kibana-1-bo5zq","pid":1,"level":50,"err":{"message":"Request Timeout after 5000ms","name":"Error","stack":"Error: Request Timeout after 5000ms\n    at null.<anonymous> (/opt/app-root/src/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n    at Timer.listOnTimeout (timers.js:92:15)"},"msg":"","time":"2016-09-29T10:59:15.480Z","v":0}
{"name":"Kibana","hostname":"logging-kibana-1-bo5zq","pid":1,"level":60,"err":{"message":"Request Timeout after 5000ms","name":"Error","stack":"Error: Request Timeout after 5000ms\n    at null.<anonymous> (/opt/app-root/src/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n    at Timer.listOnTimeout (timers.js:92:15)"},"msg":"","time":"2016-09-29T10:59:15.483Z","v":0}
```

how to resolve this?

**Comment by jcantrill** [comment]
This could be a result of ES not being up.  Have you checked the rest of the stack to determine if it is functional: https://github.com/openshift/origin-aggregated-logging#efk-health

**Comment by priyanka5** [comment]
@jcantrill thanks for response, I ran "Check-EFK-running.sh" and below is the output, which gives no error but kibana pod is still not up, any help?

Checking component installation and if pods are running:
-------------------------------------------------------
Success - [3/3] deployment configs found.
-------------------------------------------------------
Success - [3/3] unique replication controllers found.
-------------------------------------------------------
Success - [2/2] routes found.
-------------------------------------------------------
Success - [6/6] services found.
-------------------------------------------------------
Success - [1/1] oauth clients found.
-------------------------------------------------------
Success - [1/1] daemonsets found.
-------------------------------------------------------

**Comment by jcantrill** [comment]
have you additionally reviewed: https://github.com/openshift/origin-aggregated-logging/tree/master/deployer#troubleshooting

**Comment by priyankagithub5** [comment]
@jcantrill no  I have not tried this, I assume this is for troubleshooting when EFK is deployed successfully but gives error after that such as login loop. My problem is that Kibana pod is not up , so I think there is no use in checking this :( would u really helpful if you can provide more details on troubleshooting . Thanks again!

**Comment by priyanka5** [comment]
@jcantrill no  I have not tried this, I assume this is for troubleshooting when EFK is deployed successfully but gives error after that such as login loop. My problem is that Kibana pod is not up , so I think there is no use in checking this :( would be really helpful if you can provide more details on troubleshooting . Thanks again!

**Comment by jcantrill** [comment]
@priyanka5 my guess is your ES instance is not running and accepting requests but without logs from that pod, we can not say.  The kibana error seems to indicate it is unable to connect and ES is the only place it tries.  Also, have you considered trying the latest images which are v1.3 of origin.  Origin latest also includes https://github.com/openshift/origin/commit/1fbfe81169ba6c64eeadc2b2dd035a6f7b883da3 which is diagnostic checks for the EFK stack

**Comment by priyanka5** [comment]
@jcantrill thanks, tried with latest image v1.3 but it gives imagepull back error. Posting elastic search logs below with v1.2:

SLF4J: Found binding in [jar:file:/usr/share/elasticsearch/plugins/openshift-elasticsearch-plugin/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/elasticsearch/plugins/cloud-kubernetes/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[2016-10-07 09:52:11,857][WARN ][io.fabric8.kubernetes.api.KubernetesHelper] Lookup logging-es-cluster result: host not found
[2016-10-07 09:52:13,363][WARN ][io.fabric8.kubernetes.api.KubernetesHelper] Lookup logging-es-cluster result: host not found
[2016-10-07 09:52:14,869][WARN ][io.fabric8.kubernetes.api.KubernetesHelper] Lookup logging-es-cluster result: host not found
[2016-10-07 09:52:14,878][INFO ][cluster.service          ] [Wendigo] new_master [Wendigo][EB9wdqDkRGipDwQrOzJNZA][logging-es-jhlmcvb6-1-loh9z][inet[/10.1.0.9:9300]], reason: zen-disco-join (elected_as_master)
[2016-10-07 09:52:14,909][INFO ][http                     ] [Wendigo] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.1.0.9:9200]}
[2016-10-07 09:52:14,909][INFO ][node                     ] [Wendigo] started
[2016-10-07 09:52:14,913][INFO ][gateway                  ] [Wendigo] recovered [0] indices into cluster_state
[2016-10-07 09:52:17,028][INFO ][cluster.metadata         ] [Wendigo] [.searchguard.logging-es-jhlmcvb6-1-loh9z] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings [ac]
[2016-10-07 09:52:17,320][INFO ][cluster.metadata         ] [Wendigo] [.searchguard.logging-es-jhlmcvb6-1-loh9z] update_mapping [ac] (dynamic)

**Comment by jcantrill** [comment]
@ewolinetz tagging you in...

**Comment by ewolinetz** [comment]
@priyanka5 can you send the output from `$ oc describe dc logging-kibana`? It may shed some light on why you're getting an image pull error

**Comment by priyanka5** [comment]
@ewolinetz , below is the output:

Name:           logging-kibana
Created:        4 hours ago
Labels:         component=kibana
                logging-infra=kibana
                provider=openshift
Annotations:    openshift.io/generated-by=OpenShiftNewApp
Latest Version: 1
Selector:       component=kibana,provider=openshift
Replicas:       1
Triggers:       <none>
Strategy:       Rolling
Template:
  Labels:               component=kibana,provider=openshift
  Annotations:          openshift.io/generated-by=OpenShiftNewApp
  Service Account:      aggregated-logging-kibana
  Containers:
  kibana:
    Image:      docker.io/openshift/origin-logging-kibana:latest
    Port:
    QoS Tier:
      memory:   BestEffort
      cpu:      BestEffort
    Environment Variables:
      ES_HOST:  logging-es
      ES_PORT:  9200
  kibana-proxy:
    Image:      docker.io/openshift/origin-logging-auth-proxy:latest
    Port:       3000/TCP
    QoS Tier:
      cpu:      BestEffort
      memory:   BestEffort
    Environment Variables:
      OAP_BACKEND_URL:          http://localhost:5601
      OAP_AUTH_MODE:            oauth2
      OAP_TRANSFORM:            user_header,token_header
      OAP_OAUTH_ID:             kibana-proxy
      OAP_MASTER_URL:           https://ose-master.test.com:8443
      OAP_PUBLIC_MASTER_URL:    https://ose-master.test.com:8443
      OAP_LOGOUT_REDIRECT:      https://ose-master.test.com:8443/console/logout
      OAP_MASTER_CA_FILE:       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      OAP_DEBUG:                false
  Volumes:
  kibana:
    Type:       Secret (a volume populated by a Secret)
    SecretName: logging-kibana
  kibana-proxy:
    Type:       Secret (a volume populated by a Secret)
    SecretName: logging-kibana-proxy

Deployment #1 (latest):
        Name:           logging-kibana-1
        Created:        4 hours ago
        Status:         Complete
        Replicas:       1 current / 1 desired
        Selector:       component=kibana,deployment=logging-kibana-1,deploymentconfig=logging-kibana,provider=openshift
        Labels:         component=kibana,logging-infra=kibana,openshift.io/deployment-config.name=logging-kibana,provider=openshift
        Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed

No events.

**Comment by ewolinetz** [comment]
@priyanka5 it looks like it was able to pull the images correctly and that there is currently a pod running...
are you still seeing a crash loop? 

There was nothing in the ES logs you had pasted above that would give reason as to why Kibana couldn't connect to it...

**Comment by priyanka5** [comment]
@ewolinetz , yes it s able to pull image, but pod is still crashing and status is "Crash loop back off" , logs are:

{"name":"Kibana","hostname":"logging-kibana-1-463v9","pid":1,"level":50,"err":{"message":"Request Timeout after 5000ms","name":"Error","stack":"Error: Request Timeout after 5000ms\n    at null.<anonymous> (/opt/app-root/src/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n    at Timer.listOnTimeout (timers.js:92:15)"},"msg":"","time":"2016-10-07T14:20:08.406Z","v":0}
{"name":"Kibana","hostname":"logging-kibana-1-463v9","pid":1,"level":60,"err":{"message":"Request Timeout after 5000ms","name":"Error","stack":"Error: Request Timeout after 5000ms\n    at null.<anonymous> (/opt/app-root/src/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n    at Timer.listOnTimeout (timers.js:92:15)"},"msg":"","time":"2016-10-07T14:20:08.409Z","v":0}

**Comment by ewolinetz** [comment]
@priyanka5 to see if this is a dns issue can you do the following?
```
$ oc debug dc/logging-kibana
 . . .
curl --cacert /etc/kibana/keys/ca --cert /etc/kibana/keys/cert --key /etc/kibana/keys/key 'https://logging-es:9200/'
```

**Comment by priyanka5** [comment]
@ewolinetz yes seems some DNS error , below is the output:

sh-4.2$ curl --cacert /etc/kibana/keys/ca --cert /etc/kibana/keys/cert --key /et                                 c/kibana/keys/key 'https://logging-es:9200/'

curl: (6) Could not resolve host: logging-es; Unknown error

**Comment by ewolinetz** [comment]
@priyanka5 what does the resolv.conf look like in the debug pod?
$ cat /etc/resolv.conf

**Comment by priyanka5** [comment]
@ewolinetz sorry I could not check this over weekend. Please find the content of resolve.conf in debug pod, where "171.30.50.12" is the private IP of AWS instance where openshift is running :

search logging.svc.cluster.local svc.cluster.local cluster.local ec2.internal
nameserver 171.30.50.12
nameserver 171.30.50.12
options ndots:5

**Comment by ewolinetz** [comment]
@priyanka5 sorry for the lack of response on this. Looking back through, I see that the check-logs.sh didn't find any indices within Elasticsearch. Out of curiosity, do you have any Fluentd pods running?

If you do, do you see any errors in their logs?
I'm wondering if this is an issue that the other pods on that node may be experiencing. If it is, then restarting docker and openshift-node might resolve that issue.

**Comment by priyanka5** [comment]
@ewolinetz : no problem , actually I found the issue , my docker container is not able to access internet. I am running this on CentOS 7 . Not sure why its happening , I have already tried lot of things . but no success. looking more

**Comment by jcantrill** [comment]
@priyanka5 please reopen this issue if you require additional assistance.
