### ISSUE TITLE
Curator timing out with connecting to ES to delete indices some times

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#252]
This can sometimes be mitigated by deleting the Curator pod and forcing it to run again

**Comment by portante** [comment]
We have seen this on bare-metal instances as well.  Deleting an ES index requires memory structures being torn down and then metadata scrubbed from the disk.  This can be intensive.

We might want to consider `closing` instances first, and deleting them later in less active periods.

Another consideration is to `optimize` the indices soon after they are "complete", which will lower both their memory and on-disk footprint to make them easier to delete.

**Comment by ewolinetz** [comment]
Do we think that adding the `--timeout` flag for Curator [1] (and make it able to be configured via an ENV var) would be an appropriate fix? While `closing` an index first may help with this, we can't assume that someone would close at all.

[1] https://www.elastic.co/guide/en/elasticsearch/client/curator/3.5/timeout.html

**Comment by richm** [comment]
+1 for `--timeout`

**Comment by ewolinetz** [comment]
resolved via #270
