### ISSUE TITLE
Uninstall should remove configmaps?

### ISSUE THREAD

**Issue by sdodson** [openshift/origin-aggregated-logging#253]
Should uninstall remove configmaps?

**Comment by jcantrill** [comment]
I think it depends if we consider 'uninstall' to be:
* Nuke everything and start from scratch (maybe we need an 'implode' option to uninstall?)
or
* remove resources but keep my config because I'm going to try to install again

I could see cases for both.

**Comment by ewolinetz** [comment]
I think uninstall should include configmaps, with the exception of the deployer configmap.

**Comment by jcantrill** [comment]
I know this is targeted to the deployer but, @ewolinetz,  Looking at our 'delete_logging' ansible task I dont see any reference to configmaps.  I would expect maybe they would get removed if we delete the logging project too?  Take away for ansible work?

**Comment by ewolinetz** [comment]
They should be cleaned up if we delete the logging project. But I'll take on cleaning them up in the Ansible entry point.

**Comment by ewolinetz** [comment]
this is now encompassed in the openshift_logging Ansible role
https://github.com/ewolinetz/openshift-ansible/blob/logging_deployer_tasks/roles/openshift_logging/tasks/delete_logging.yaml#L86-L93
