### ISSUE TITLE
Fix spaces/indentation in elasticsearch/run.sh

### ISSUE THREAD

**Issue by richm** [openshift/origin-aggregated-logging#258]
See https://github.com/openshift/origin-aggregated-logging/pull/222/files/342389bbbe3b920358f4ec683520c67c3b9f6f20#r84350608

**Comment by richm** [comment]
tech debt/code cleanup issue

**Comment by lukas-vlcek** [comment]
What is recommended, tabs or spaces? :-)

**Comment by richm** [comment]
I prefer spaces.

**Comment by jcantrill** [comment]
I prefer spaces too.  We should agree on what a 'tab' means.  4 spaces?

**Comment by lukas-vlcek** [comment]
+1, I am fine with 4 spaces.
