### ISSUE TITLE
refactor index templates to avoid duplication

### ISSUE THREAD

**Issue by richm** [openshift/origin-aggregated-logging#259]
from https://github.com/openshift/origin-aggregated-logging/pull/222#discussion_r84355502

> Then we might want to consider having a mapping.json file, and then assembling the template by writing out that specific template with the mapping pulled from the single file. This is fairly easy to do since it is all JSON. A simple python program would have the dictionary containing the skeleton of the template, reads in the mapping.json file, and then writes out via json.dumpf the full template.

**Comment by lukas-vlcek** [comment]
Mapping files need to come from https://github.com/ViaQ/elasticsearch-templates. They shouldn't be modified or generated here in any way.

Note that one advantage of not generating these files here is ease of testing (see how we can easily [implement test](https://github.com/openshift/origin-aggregated-logging/blob/342389bbbe3b920358f4ec683520c67c3b9f6f20/hack/testing/check-EFK-running.sh#L90-L110) that lists all files from `elasticsearch/index_templates` and check for each that there is an index template existing in ES).

**Comment by jcantrill** [comment]
closing without prejudice
