### ISSUE TITLE
Accept a Storage Selector for the Deployer

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#262]
So that we can specify that a PVC match a particular PV label, we should be able to accept a storage-selector label to add to the PVC that we generate.

**Comment by ewolinetz** [comment]
https://docs.openshift.org/latest/install_config/persistent_storage/selector_label_binding.html

**Comment by ewolinetz** [comment]
https://docs.openshift.com/container-platform/3.3/install_config/storage_examples/binding_pv_by_label.html

**Comment by jcantrill** [comment]
Adding as blocked since this will probably only be addressed in the openshift ansible work

**Comment by ewolinetz** [comment]
we will be able to do this in ansible by specifying something like `es_pv_selector={"logging-pvc":"ansible"}` in the role variable

**Comment by jcantrill** [comment]
@ewolinetz Closable because we implemented in ansible? https://github.com/ewolinetz/openshift-ansible/blob/logging_deployer_tasks/roles/openshift_logging/defaults/main.yml#L52

**Comment by ewolinetz** [comment]
:+1:
