### ISSUE TITLE
Be able to specify resource limits for EFK components

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#269]
CPU and Memory specifically, currently we can limit ES memory and Fluentd CPU

**Comment by jcantrill** [comment]
Is this the same as https://trello.com/c/dCrXfPxx/

**Comment by ewolinetz** [comment]
No, this is so we can provide a memory and processor limit on the other components.

**Comment by jcantrill** [comment]
@ewolinetz I don't imagine us working to push this into the deployer.  You agree we can close because of https://github.com/ewolinetz/openshift-ansible/pull/21

**Comment by ewolinetz** [comment]
:+1:
