### ISSUE TITLE
Add health checks

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#291]
Adding health checks (readiness and liveliness probes) seems like it would be a good idea. I'm not sure how exactly they might be implemented for the fluentd or curator pods, but I've worked out things that should work for the rest:

pod|hook type|details
---|---|---
elasticsearch|command|`curl --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key --cacert /etc/elasticsearch/secret/admin-ca https://127.0.0.1:9200` _(edit: similar idea has been implemented in the meantime https://github.com/openshift/origin-aggregated-logging/pull/358)_
kibana|HTTP|port 5601, path `/`
kibana-proxy|HTTP|port 3000, see below for path

The [kibana proxy](https://github.com/fabric8io/openshift-auth-proxy) would need to be extended with a status endpoint that returns HTTP 399 and doesn't require authentication. Elasticsearch uses a command rather than an HTTP hook because it requires client TLS certificates for all connections.

**Comment by jcantrill** [comment]
Liveness probe for fluentd should consider evaluation to resolve: https://bugzilla.redhat.com/show_bug.cgi?id=1395448#c13

**Comment by jcantrill** [comment]
Also mentioned in https://github.com/openshift/origin-aggregated-logging/issues/22

**Comment by elyscape** [comment]
One way to probe fluentd would be to add [a monitor_agent source][monitor_agent] and periodically execute a script that returns success or failure based on the values of `buffer_queue_length`, `buffer_total_queue_size`, and/or `retry_count` for the various output plugins.

[monitor_agent]: http://docs.fluentd.org/v0.12/articles/monitoring

**Comment by richm** [comment]
@elyscape yeah, something like that.  We have noticed at very high load that the fluentd http monitor endpoint will stop responding for a couple of minutes.  It seems during this time that fluentd is working - I suppose it is too busy processing logs to respond to the http monitor endpoint in a timely manner.  I'm not sure what to do about this.  Do you know if it is better in fluent 0.14?

**Comment by elyscape** [comment]
I have no idea, unfortunately. It might be a worthwhile to reach out to the Fluentd community and/or developers.

**Comment by lukas-vlcek** [comment]
Notice: When it comes to implementing both readiness and liveness probes for services with complex state (such as Elasticsearch in this case) it is worth pointing out existing Kubernetes ticket: https://github.com/kubernetes/kubernetes/issues/27114
It says that as of now it is not possible to start liveness probe only after readiness probe passes. Which can bring more complexity to probes implementation and their configuration.
