### ISSUE TITLE
Investigate hostmount SCC with SELinux

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#304]
In our docs we state to use the `privileged` SCC with host mounting for ES since previously we had issues with SELinux.

We should reinvestigate if this is still an issue and update our documentation if necessary.

**Comment by madddi** [comment]
I'm using the "hostaccess" SCC without issues. The directory SELinux context is `system_u:object_r:svirt_sandbox_file_t:s0`.

**Comment by ewolinetz** [comment]
+1 @madddi  
Have you tried using the `hostmount-anyuid` SCC? I believe that is the one we had been eyeing when this issue was written.

**Comment by madddi** [comment]
No, I only used the `hostaccess` SCC as it grants less privileges and seems to work just fine. Is there any reason against this?

**Comment by ewolinetz** [comment]
Other than being more restrictive on the `RUNASUSER` or `FSGROUP`, or not needing `nfs` volumes, I can't think of a reason against it.
@smarterclayton or @liggitt is there a preference for one over the other?
