### ISSUE TITLE
Update search-guard ACL

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#31]
To address the following error:

[ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to com.floragunn.searchguard.tokeneval.MalformedConfigurationException: no bypass or execute filters at all for action indices:admin/mappings/fields/get

I believe this occurs when people are navigating to the settings page in Kibana, and Kibana tries to pull the fields for the logstash-* index.

**Comment by ewolinetz** [comment]
I think as part of this, we should also update search-guard to not print the stack trace when this is encountered.

**Comment by ewolinetz** [comment]
@lukas-vlcek do you think you could take this up since you have been most recently working with search-guard?  This will probably need to be tracked in both our fork and merged into upstream.

**Comment by richm** [comment]
Was this done?

**Comment by floragunncom** [comment]
Search Guard 2 (for Elasticsearch 2) is out and it comes with a lot of fixes and makes it easier to update the ACL on the fly, see https://github.com/floragunncom/search-guard

**Comment by jcantrill** [comment]
@ewolinetz is this issue still relevant given we are upgrading the stack and have rewritten the openshift-elasticsearch plugin?

**Comment by ewolinetz** [comment]
@jcantrill I haven't yet seen this error come up with the latest stack so we can probably close it.  If it comes up again, I'll reopen this
