### ISSUE TITLE
How can I config ElasticSearch log at ERROR level?

### ISSUE THREAD

**Issue by harobed** [openshift/origin-aggregated-logging#352]
Hi,

`openshift/origin-logging-elasticsearch:v1.3.1` image is executed and I have some DEBUG message in log.

How can I config ElasticSearch log at ERROR level?

Best regards,
Stéphane

**Comment by jcantrill** [comment]
​The log level configuration​ is mounted in the pod from a config map [1].
Edit the config map [2] to set the log level to the value you desire and
restart the pod

[1]
https://github.com/openshift/origin-aggregated-logging/blob/release-1.3/elasticsearch/logging.yml#L4
[2]
https://github.com/openshift/origin-aggregated-logging/blob/release-1.3/elasticsearch/logging.yml#L4

**Comment by jcantrill** [comment]
Closing.  Please reopen if this does not solve your question
