### ISSUE TITLE
Question, regarding fluentd volume configuration

### ISSUE THREAD

**Issue by jtslear** [openshift/origin-aggregated-logging#36]
Guys,

I've dismantled this as we want to borrow some bits of this but make it work for our specific environment.  In the process I do not understand how the master branch can be working.  Either some magic is going on, or what is built does not match what is on master.

The volume configuration for fluentd as noted below:
https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/fluentd.yaml#L79

Does not match where fluentd is configured to look for the log files:
https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/fluent.conf#L147

**Comment by ewolinetz** [comment]
Hi @jtslear, 

We are able to get /var/log/containers/ from the `varlog` volume mount - https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/fluentd.yaml#L77

The `varlibdockercontainers` is an extra volume mount that isn't actually used and should probably be removed from the template.

**Comment by jtslear** [comment]
@ewolinetz DON'T REMOVE IT

After going back and forth I figured out how this works.  The kubernetes plugin uses the file path to determine what to query k8s.  But these are just symlinked files.  Fluentd won't have any way to read them if you end up removing that volume mount.
