### ISSUE TITLE
Readiness probe timeout should be set less than 1sec

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#370]
Elasticsearch readiness probe script was introduced in https://github.com/openshift/origin-aggregated-logging/pull/358

There is known issue that prevents probe script timeout control from Docker/Kubernetes. See https://github.com/openshift/openshift-ansible/pull/3733#pullrequestreview-31314038

The timeout has to be controlled from within the probe script itself and it is probably safer to set it to less than 1 sec.

I do not know if we control version of curl that is used by probe script but be aware that (taken from `man curl`):

````
-m, --max-time <seconds>
              Maximum time in seconds that you allow the whole operation to take.  This is useful for preventing your batch jobs from hanging
              for  hours  due to slow networks or links going down.  Since 7.32.0, this option accepts decimal values, but the actual timeout
              will decrease in accuracy as the specified timeout increases in decimal precision.  See also the --connect-timeout option.

              If this option is used several times, the last one will be used.
````

Notice: "`Since 7.32.0, this option accepts decimal values, ...`"

**Comment by lukas-vlcek** [comment]
Adding reference to related ticket: https://github.com/kubernetes/kubernetes/issues/26895
//cc @rhcarvalho

**Comment by rhcarvalho** [comment]
> I do not know if we control version of curl that is used by probe script but be aware that (taken from man curl)

Whatever binary run in a probe script must be available in the Docker image.

In this case, I see the image is based on CentOS 7 (https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/Dockerfile#L1), but there might be a version of this image based on RHEL, though that I do not know... I wouldn't expect a major difference anyway.

**Comment by lukas-vlcek** [comment]
Closing in favour of https://github.com/openshift/origin-aggregated-logging/issues/372
