### ISSUE TITLE
Update version of node supported for kibana-auth-proxy

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#374]
The kibana-auth-proxy image will terminate when running a newer version of nodejs, however we currently are supporting two different versions of node in enterprise. We should update the auth-proxy image to work with 4.7.2

This should be a blocker for 1.6

cc @jcantrill @tdawson

**Comment by pweil-** [comment]
@ewolinetz @tdawson @jcantrill to be clear, what makes this a blocker, the support statement?  Being able to package whatever you depend on independent of other containers is part of the goodness of containers.

**Comment by ewolinetz** [comment]
@pweil- This is more for supporting multiple versions at the enterprise puddle level when doing builds.

**Comment by tdawson** [comment]
Also the fact that the security teams keep asking me every couple of months when I'm going to get nodejs-0.10 out of all our images.  It hasn't been supported for years.  Not by upstream, not by Red Hat.

But yes, there is also the fact that "there can be only one" in our puddles and repos.  When other logging images chose to go to nodejs-4 I brought up the issue and was told that moving this image to nodejs-4 would happen "next release".  That's was a couple of releases ago.

**Comment by richm** [comment]
There can be more than one nodejs version in our puddles/repos.  The yum command must specify the full N-V (or N-V-R) of the nodejs package in order to install the older one.

**Comment by tdawson** [comment]
Normal Yum repos, yes
Puddle, no
Errata system, no
When building the final images we have to use puddles that are created based on the errata system.  The errata system can only handle one version of a package at a time.
I'm a little surprised by the push back on this.  How big of a bug is this?

**Comment by jcantrill** [comment]
Closing as we intend to utilize the oauth-proxy https://trello.com/c/87ApT6N9
