### ISSUE TITLE
Mounting /var/lib/docker/containers in fluentd pod leads to unmountable docker drives

### ISSUE THREAD

**Issue by portante** [openshift/origin-aggregated-logging#376]
See also [BZ #1437952](https://bugzilla.redhat.com/show_bug.cgi?id=1437952).

We unconditionally mount `/var/lib/docker/containers` in the fluentd pod in order to support the ability for `fluentd` to collect logs from Docker's `json-file` logger.

This mount is present, but left unused when using Docker's `journald` logger.

The effect of mounting this directory in the fluentd pods is that those mounts cannot be removed, nor the fluentd pods' mount removed, when the container is torn down.  This can lead to orphaned mounts.

We should deprecate `json-file` logger support, and then only mount that directory when the user selects `json-file` logger, after documenting all the risks.

**Comment by timchenxiaoyu** [comment]
I have some problem ,how to slave this ?

**Comment by richm** [comment]
I don't think this is a problem anymore with the change to oci-umount - please confirm
