### ISSUE TITLE
Unable to deploy the 'logging-deployer- POD - unauthorized:  authentication required

### ISSUE THREAD

**Issue by ghost** [openshift/origin-aggregated-logging#377]
I'll admit I'm pretty new to OpenShift and frankly half the time it feels like I'm fumbling around in the dark.
Today I'm trying to setup aggregated logging and deploying the EFK Stack.  We have an application running in OSE but honestly the logs are flying by and I can't get anything meaningful from the way logging is done in a containerized world (e.g. 5000 lines at a time pumped out to some stream...).
When I attempt to deploy the POD (logging-deployer) I keep getting:
Failed to pull image "bdsoselogging-deployer:3.4.1": unauthorized: authentication required 
When the POD tries to start, and I have no idea what's failing, what secret I should be using, etc.
In the 'logging' project >> Resources >> Secrets there are several secrets:
![image](https://cloud.githubusercontent.com/assets/7916480/24929796/41345b2a-1ed5-11e7-81ce-0b9f010b6518.png)
Are any of these the secret I should use in the 'logging-deployer' Configmap? ('image-pull-secret')
If not, what would I use?  I'm completely confused.
Thanks and best wishes.

**Comment by jcantrill** [comment]
* Have you followed the instructions here: https://github.com/openshift/origin-aggregated-logging/tree/release-1.4/deployer 
* From where are you trying to source your logging images?

If you require images from an authenticated registry, put your creds into a secret and specify the name with the image-pull-secret var.

**Comment by jcantrill** [comment]
Closing as 1.4 is out-of-date and we no longer rely on the deployer.
