### ISSUE TITLE
EFK doubt

### ISSUE THREAD

**Issue by Yashu5** [openshift/origin-aggregated-logging#38]
Hi, I have deployed EFK in openshift 3.1, In doc it is mentoined "Unfortunately there is no way to stream logs as they are created at this time."

how much time gap is there between log generation and display in kibana and why??

**Comment by ewolinetz** [comment]
It should normally be just a few seconds. The gap consists of:
1. Fluentd reading the logs from local disk (not sure how long this takes, and it would depend on how active all the other container logs were too)
2. ES indexing the logs, which should just take about a second
3. Kibana retrieving the logs from ES; you can have Kibana auto-reload periodically

It is important to note that the logs are buffered in Fluentd and bulk loaded into Elasticsearch periodically (better performance than individual requests for each log message). This is configured in the Elasticsearch plugin at 5 seconds.
