### ISSUE TITLE
Set Xms equal to Xmx at Elasticsearch startup

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#383]
We should not make it possible to start ES with `Xms < Xmx`. One of the reasons is that we may not be able to fully benefit from **disabled swap** (#206) via mlockall.

**Comment by ewolinetz** [comment]
Do we have node sizing documentation currently that references sizing for ES that we can add to to make sure users are aware of this? We should make sure that this information is well dispersed in our docs since we are effectively changing how this will work on smaller test installations.

**Comment by jcantrill** [comment]
@ewolinetz I dont see it as a huge issue to document. In practice, this is recommended way of running java servers to avoid GC issues.  My suspicion is that any deployment quickly grabs all the memory it can anyway.  And to your point, we adjust max heap based on whats available to the container.

**Comment by portante** [comment]
I believe we should not allow the user to set `Xms` < `Xmx`, nor allow them to set `Xmx`, but derive `Xmx` from the size of the container as we do today, documenting the behavior of halving the container size for `Xmx`.

I believe we do most of that today, no?

**Comment by lukas-vlcek** [comment]
My first take on this https://github.com/openshift/origin-aggregated-logging/pull/389
