### ISSUE TITLE
Origin 1.4.1 multiple errors: cannot read property  byName of undefined, UI completely broken, Could not locate that index-pattern-field (id: @timestamp)

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin-aggregated-logging#393]
![image](https://cloud.githubusercontent.com/assets/1156788/25500433/a31ad7fc-2b54-11e7-8427-69b8498f2e4f.png)
![image](https://cloud.githubusercontent.com/assets/1156788/25500454/b6f1dd34-2b54-11e7-962b-78ba4addfccc.png)
![image](https://cloud.githubusercontent.com/assets/1156788/25500534/fbce5720-2b54-11e7-9b07-d1e7740f0d25.png)

even though my status shows:
![image](https://cloud.githubusercontent.com/assets/1156788/25500709/aff23b7c-2b55-11e7-9901-441a3b7a396e.png)

**Comment by jcantrill** [comment]
A number of these issues are related to no data available.   Also, there are several backport fixes that are available in the HEAD of the release-1.4 branch that have not been pushed to a new image.

**Comment by jcantrill** [comment]
Closing as EOL
