### ISSUE TITLE
aggregated logging / elasticsearch maintenance

### ISSUE THREAD

**Issue by miheer** [openshift/origin-aggregated-logging#42]
We've installed the aggregated-logging Stack from https://github.com/openshift/origin-aggregated-logging/tree/master/deployment
Now, collecting and displaying logs works fine, but collected data grows, and we cant invoke elasticsearch's REST API to make some cleanup/maintenance jobs. even when i connect to the elasticsearch-pod and call
curl -X GET http://127.0.0.1:9200
the response is always
curl: (52) Empty reply from server

How do you maintain elasticsearch-data? Is there a special token / secret that must be used to connect elasticsearch?

**Comment by sosiouxme** [comment]
We haven't described a method for data maintenance. That work is under way. Part of what we need to do is put a client key/cert for an admin user directly into the ElasticSearch secret to be used from the pod.

You'll get nothing from http://127.0.0.1:9200 as the listener there is HTTPS. You could however connect using the fluentd user key/cert and CA from the fluentd secret. We could provide directions for doing this as a workaround until there is a better solution.

**Comment by richm** [comment]
For example::

    poduuid=`sudo docker ps | awk '/kibana/ && $2 ~ /^openshift\/origin-pod:/ {print gensub(/^.*_([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})_.*$/, "\\\1", 1)}'`
    esip=`dig @localhost logging-es.logging.svc.cluster.local +noall +answer | awk '/^;/ || /^$/ {next}; {print $NF}'`
    cert=/var/lib/origin/openshift.local.volumes/pods/$poduuid/volumes/kubernetes.io~secret/kibana/cert
    key=/var/lib/origin/openshift.local.volumes/pods/$poduuid/volumes/kubernetes.io~secret/kibana/key
    sudo curl -s -k --cert $cert --key $key https://$esip:9200/_cluster/health | python -mjson.tool

**Comment by sosiouxme** [comment]
Well, you really want the fluentd key/cert if you plan to edit any data. And I think it's a little clearer to access all this via oc...
```
oc get secret logging-fluentd --template='{{.data.ca}}' | base64 -d > ca
oc get secret logging-fluentd --template='{{.data.key}}' | base64 -d > key
oc get secret logging-fluentd --template='{{.data.cert}}' | base64 -d > cert
oc port-forward <es pod name> 9200:9200
curl -s --cacert ca --key key --cert cert https://localhost:9200/_cluster/health | python -mjson.tool
```

**Comment by richm** [comment]
There are a few problems with the above:

* The fluentd user apparently does not have rights to read all of the indexes - so /_cluster/health will work, but not /logging*/_search or etc. - this is why I used the kibana user, so::

    oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > ca
    ...

etc.

* you must specify the argument to `--cert` as a filename e.g. `--cert ./cert` or curl will complain

* to get the es pod name::

    espod=`oc get pods | awk '/^logging-es-/ {print $1}'`

* oc port-forward runs in the foreground?  I had to run it with `&` at the end to background it

* using localhost times out quite a bit running in my centos7 vm, the first few times I try it - after that, it seems to work fine

**Comment by sosiouxme** [comment]
We need to look at how we've set these permissions. The kibana user is supposed to be read-only, while the fluentd user can write to every index. I would have thought that would allow fluentd to read everything too.

In the end, we just need to provide an admin user.

**Comment by richm** [comment]
ok - so for now, use the kibana cert/key for reading, and the fluentd cert/key for writing

**Comment by richm** [comment]
We are going to use elasticsearch curator.  I have submitted a pull request: https://github.com/openshift/origin-aggregated-logging/pull/57
Please take a look

**Comment by ewolinetz** [comment]
The logging-curator image is now available in Dockerhub for use

**Comment by scheng1** [comment]
@scheng1

**Comment by scheng1** [comment]
@sosiouxme  how can i handle it ?  thanks
[root@test-master1 log]# oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > ca
[root@test-master1 log]# oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > key
[root@test-master1 log]# oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > cert
[root@test-master1 log]# curl -sv --cacert ca --key key --cert cert  https://localhost:9200/_cluster/health
* About to connect() to localhost port 9200 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: ca
  CApath: none
* warning: certificate file name "cert" handled as nickname; please use "./cert" to force file name
* NSS: client certificate not found: cert
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=logging-es,OU=OpenShift,O=Logging
* 	start date: Sep 05 02:07:08 2017 GMT
* 	expire date: Sep 05 02:07:08 2019 GMT
* 	common name: logging-es
* 	issuer: CN=logging-signer-20170905020703
> GET /_cluster/health HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9200
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 0
< 
* Connection #0 to host localhost left intact

**Comment by jcantrill** [comment]
@scheng1 Can you describe what you are trying to accomplish so we may now how to answer your question?

**Comment by scheng1** [comment]
@jcantrill I want to see the index of es

**Comment by richm** [comment]
@scheng1 the kibana cert/key do not have permissions.  You'll have to use the admin-cert and admin-key from the logging-elasticsearch secret.

**Comment by jcantrill** [comment]
@scheng1 There is a utility which you can use that has access to the certs.  You may invoke it assuming you have access to the pod and depending which version of logging you have by:

`oc exec <PODNAME> -- es_util --query='/_cat/indices?pretty'`

or

```
$ oc rsh <PODNAME>
$ QUERY='/_cat/indices?pretty' es_util
```

**Comment by sosiouxme** [comment]
On Wed, Sep 6, 2017 at 5:52 AM, Dodoing <notifications@github.com> wrote:

>
> [root@test-master1 log]# oc get secret logging-kibana --template='{{.
> data.ca}}' | base64 -d > key
> [root@test-master1 log]# oc get secret logging-kibana --template='{{.
> data.ca}}' | base64 -d > cert
>

Looks like you need `.data.key` and `.data.cert` here, respectively


>
>    - NSS: client certificate not found: cert
>
>
This is why the "Unauthorized"

**Comment by sosiouxme** [comment]
> @scheng1 <https://github.com/scheng1> the kibana cert/key do not have
> permissions. You'll have to use the admin-cert and admin-key from the
> logging-elasticsearch secret.
>
>
Oh yeah, that too. Heh.

The tool Jeff mentions is probably the easiest way...

**Comment by scheng1** [comment]
@sosiouxme @richm   the admin-cert and admin-key from the logging-elasticsearch secret are the same as  the kibana cert/key ，as follow：

sh-4.2$ cat secret/admin-ca (admin-cert and admin-key) 
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBATANBgkqhkiG9w0BAQsFADAoMSYwJAYDVQQDEx1sb2dn
...
YRorPI7cEnc/bjOd7vUj9pEgRSNN0mC2yLUZ2aBmfEcz/Q==
-----END CERTIFICATE-----
sh-4.2$ pwd
/etc/elasticsearch
***********************
[root@test-master1 log]# cat ca (kibana cert/key )
-----BEGIN CERTIFICATE-----
MIIC7jCCAdagAwIBAgIBATANBgkqhkiG9w0BAQsFADAoMSYwJAYDVQQDEx1sb2dn
...
YRorPI7cEnc/bjOd7vUj9pEgRSNN0mC2yLUZ2aBmfEcz/Q==
-----END CERTIFICATE-----
********************

**Comment by scheng1** [comment]
@sosiouxme  where can i find  `.data.key` and `.data.cert`  Thanks.
>Looks like you need `.data.key` and `.data.cert` here, respectively

**Comment by scheng1** [comment]
@jcantrill  I can not execute the cmd successful
>oc exec <PODNAME> -- es_util --query='/_cat/indices?pretty'

or

>$ oc rsh <PODNAME>
>$ QUERY='/_cat/indices?pretty' es_util

**Comment by sosiouxme** [comment]
@scheng1 just saying you used the same file from the secret in each of the following cases -- look at the template:

> # oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > ca
> # oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > key
> # oc get secret logging-kibana --template='{{.data.ca}}' | base64 -d > cert

In other words you wrote `.data.ca` to all three of ca, key, cert.

**Comment by scheng1** [comment]
@sosiouxme ` i am an idiot. extremely grateful.`

**Comment by scheng1** [comment]
@sosiouxme @richm @jcantrill thanks a lot. i have get what i want.
>health status index                                            pri rep docs.count docs.deleted store.size pri.store.size 
>green  open   .operations.2017.09.04                             1   2       4181            0        1mb        359.4kb 
>green  open   .kibana                                            1   2          1            0      9.5kb          3.1kb 
>green  open   .operations.2017.09.06                             1   2          4            0      101kb         33.6kb 
>green  open   .kibana.d033e22ae348aeb5660fc2140aec35850c4da997   1   2         15            8     86.9kb         26.2kb 
>green  open   .searchguard.logging-es-mgy4gafi-1-7zhcg           1   2          4            0    143.4kb         47.8kb 
>green  open   .searchguard.logging-es-0wire5xl-1-rl53q           1   2          4            0    143.4kb         47.8kb 
>green  open   .searchguard.logging-es-w1fjmrls-1-tn0n0           1   2          4            0    143.4kb         47.8kb 

one more question. The files copied by `oc cp logging/logging-es-pod:/etc/elasticsearch/secret/ ./` are null. In other words,just copy filename and there is nothing in the file.

**Comment by scheng1** [comment]
How EFK control  authorization that make user just can see his own index(named by project name).

**Comment by richm** [comment]
@scheng1 Fluentd gets the container logs which has the namespace name.  It uses the https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter to get the namespace uuid.  Fluentd writes to Elasticsearch using the index name `project.$namespace_name.$namespace_uuid.$date`
The https://github.com/fabric8io/openshift-elasticsearch-plugin looks up your auth credentials to see what projects you can view, and sets up searchguard to allow you to only view those indices for those projects.

**Comment by scheng1** [comment]
@richm  Thanks a lot.  Now, i want to display the logs of app which run in containers/pods,the logs are not in /var/log/containers/*.log if i mount the container log dir on the node by hostpath , how can i control the user just to see his own app logs and create index of es dynamically.

**Comment by scheng1** [comment]
if the app logs can write to container log files located in /var/log/containers/ ,that will be perfect.,and i just have to add some confit files to fluentd .

**Comment by richm** [comment]
@scheng1 I'm not sure I understand.  Perhaps this discussion should be continued on users@lists.openshift.redhat.com or dev@lists.openshift.redhat.com rather than in a closed github issue

**Comment by scheng1** [comment]
@richm  that's very nice of you
