### ISSUE TITLE
How to figure out if ES node is master using API?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-aggregated-logging#425]
I am trying to get rid of log-grepping from the functionality test and my current roadblock is this test:

```sh
	os::log::info "Checking that ElasticSearch pod ${elasticsearch_pod} recovered its indices after starting..."
	if oc logs "${elasticsearch_pod}" | grep -E "\[cluster\.service\s*\]" | grep -q "new_master"; then
		os::cmd::expect_success_and_text "oc logs ${elasticsearch_pod}" "\[gateway\s*\]\s*\[.*\]\s*recovered\s*\[[0-9]*\]\s*indices into cluster_state"
	elif oc logs "${elasticsearch_pod}" | grep -E "\[cluster\.service\s*\]" | grep -q "detected_master"; then
		os::log::info "ElasticSearch pod ${elasticsearch_pod} was able to detect a master"
	else
		os::log::fatal "ElasticSearch pod ${elasticsearch_pod} isn't master and was unable to detect a master"
	fi
```

As I understand it, the crux here is we need to determine if this current ES node is a master or not. I am trying to use the `_nodes/_local/name` endpoint to get this information but I am a little dismayed in that the response has a _list_ of nodes:

```
$ oc exec logging-es-ieq7sq9x-1-t4zbp -- curl -sk --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key https://localhost:9200/_nodes/_local/name?pretty
```
```json
{
  "cluster_name" : "logging-es",
  "nodes" : {
    "AggNlePNR9WjoNpn9g0v6w" : {
      "name" : "Janus",
      "transport_address" : "10.128.0.11:9300",
      "host" : "10.128.0.11",
      "ip" : "10.128.0.11",
      "version" : "2.4.4",
      "build" : "fcbb46d",
      "http_address" : "10.128.0.11:9200",
      "attributes" : {
        "master" : "true"
      }
    }
  }
}
```

Can we confirm that in multi-node deployments of ES we still get only one entry in this list? If so I can just index in and grab that first `{ .nodes[0].attributes.master }` element for this check.

/cc @richm @portante @lukas-vlcek

**Comment by lukas-vlcek** [comment]
@stevekuznetsov First, I am not sure `/_nodes/_local/name` is valid ES API option. IMO what you get using this call is [Nodes Info](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cluster-nodes-info.html) just for the `_local` node (i.e. `/_nodes/_local`) and you further try to filter this info down to `name` metric. But there is not such metric to my knowledge, so you end up with the high-level local node info only with all the optional metrics filtered out (seems that `attributes` is not considered metric thus there is no option to filter it out). Try `/_nodes/_local/http` and see if you get different result (you should get the same **except** there will be `http` metric included as well).

Second, `/_nodes/_local/` on multi-node cluster yields single entry under `.nodes` section, **but** the `.attributes` section will not tell you if the node is elected as master at this point. To my understanding the `attributes` section tells you what roles/attributes were configured to this node (for example via `elasticsearch.yml` file). I.e. if you see `attributes.master == true` then this means this node is master eligible (so it can be elected as a master).

To learn which node is currently holding the master role you can use: [`/_cat/master`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cat-master.html)
The [_cat APIs](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cat.html) are meant for CLI interaction, it does not return JSON but plain text.

For example to get only the node_id for the master from the `_cat/master` you can use `http://localhost:9200/_cat/master?h=id`

You can also use [`/_cat/nodes`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cat-nodes.html). Master node is marked with "*" in the master column.

If you do not want to use `_cat` APIs and you prefer JSON parsing you can use: `http://localhost:9201/_cluster/state/master_node`.

HTH

**Comment by stevekuznetsov** [comment]
Thank you for the explanation. I'll look into those APIs.

**Comment by stevekuznetsov** [comment]
> If you do not want to use `_cat` APIs and you prefer JSON parsing

I ended up gravitating to the `/_nodes/_local` API and JSON because I could not see any way to get the `/_cat` APIs to return to me information about only the local node. I think I'll extract out the local node ID and see if it matches the master ID from `/cluster/state/master_node`.
