### ISSUE TITLE
use DaemonSet for fluentd when on modern kubernetes/openshift

### ISSUE THREAD

**Issue by ibotty** [openshift/origin-aggregated-logging#44]
It ought to work from v1.1 on, right?

**Comment by ewolinetz** [comment]
It should, we will investigate the use of the DaemonSet for Fluentd for a future release.

**Comment by jcantrill** [comment]
On our board here: https://trello.com/c/jjIFKzNU/103-3-refactor-node-deployment-to-use-daemon-controller-cda and maybe duped here: https://trello.com/c/odQmYhqP/190-update-fluentd-to-be-deployed-via-daemonset-instead-of-rc-cda
