### ISSUE TITLE
Deployment of kibana, es and curator fails

### ISSUE THREAD

**Issue by vsedykh** [openshift/origin-aggregated-logging#440]
I'm trying to install aggregation logging to openshift cluster (Master and node). Fluetnd pods install and running without problems but deployments of kibana, es and curator fails with error like this:
error: couldn't get deployment logging-es-data-master-nudjod8r-2: Get https://172.30.0.1:443/api/v1/namespaces/logging/replicationcontrollers/logging-es-data-master-nudjod8r-2: dial tcp 172.30.0.1:443: getsockopt: network is unreachable
Same problem if i install using ansible or logging-deployer

**Comment by jcantrill** [comment]
@sosiouxme Isn't this most likely an issue with networking on the cluster unrelated to logging?

**Comment by sosiouxme** [comment]
It looks like the deployer pod trying to reach the master API and not having network access to it, which seems like a cluster networking issue. Most pods don't need to do this so you wouldn't notice it. However if you deploy a router does it log errors with similar failure to reach the master API?

**Comment by jcantrill** [comment]
Closing EOL
