### ISSUE TITLE
Port all test scripts to work on Ansible-installed cluster

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-aggregated-logging#443]
| Script | OK | Notes |
| ----- | ---- | ---- |
| `test-curator.sh`         | ✔️ | Needs `"${ENABLE_OPS_CLUSTER}"` as first arg |
| `test-datetime-future.sh` | ❌ | Needs edit to `get_test_user_token` for project, needs journal logging |
| `test-es-copy.sh`         | ❌ | #565  |
| `test-fluentd-forward.sh` | ❌ | #566  |
| `test-json-parsing.sh`    | ✔️ | #567 |
| `test-mux.sh`             | ❓ | #570|
| `test-upgrade.sh`         | ✔️  | get rid of this - doesn't currently work - need a new ansible based test |
| `test-viaq-data-model.sh` | ❓  | #568  |
| `check-EFK-running.sh` | ✔️ | |
| `check-logs.sh` | ✔️ | |

Proposal:

 - `hack/testing/logging.sh` takes parameters `$KUBECONFIG` and `$TEST_ONLY`, to trigger whether it calls into `hack/testing/setup.sh` before running component tests
 - `hack/testing/setup.sh` does cluster setup that normally would be done by a job (install OpenShift-Ansible, start cluster, etc)
 - `hack/testing/test-X.sh` (???) does set-up on cluster for specific test, then calls `test/X.sh` to run it
 - `test/X.sh` runs a test

We would use `hack/testing/test-X.sh` for instance to translate "is there an ops cluster" into simple input to the _actual_ test -- adding more items to the list of `DeploymentConfig`s or changing the `--selector` field, so the test script under `test/` can be super simple.

**Comment by stevekuznetsov** [comment]
Also a bunch of these expect to be called from `hack/testing` dir and are not well formed when called anywhere else.

**Comment by ewolinetz** [comment]
We should be able to create one-off plays to run to configure for the different tests now that the components are split up into different roles...

**Comment by richm** [comment]
I think we should get rid of the need to set `ENABLE_OPS_CLUSTER` in the individual tests.  Instead, the code can just figure out if ops clusters are in use or not.  For the CI tests, this is mostly to know whether or not es-ops is being used, which can easily be determined.  For example, look at https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/util.sh#L506:
```
    local es_pod=`get_running_pod es`
    local es_ops_pod=`get_running_pod es-ops`
    if [ -z "$es_ops_pod" ] ; then
        es_ops_pod=$es_pod
   fi
```
That's pretty much all the code needs to do to be able to work either with or without OPS.  Of course, the pre-condition is that es-ops is running.

**Comment by richm** [comment]
`test-upgrade.sh` has been broken ever since we moved to the ansible deployer . . .

**Comment by ewolinetz** [comment]
`test-upgrade.sh` should be phased out, its no longer needed since ansible is handling our installation rather than the deployer.

**Comment by richm** [comment]
Right - but - we still need to do some sort of automated upgrade testing

**Comment by stevekuznetsov** [comment]
> I think we should get rid of the need to set `ENABLE_OPS_CLUSTER` in the individual tests.

Agreed, kind-of.

> Instead, the code can just figure out if ops clusters are in use or not.

The approach I took in the E2E tests is a hybrid of this -- the test knows how to check for things. For example, `test/cluster/rollout.sh` knows how to check for deployments being finished. I prefer the user (entrypoint script in `hack/testing`) being _very_ explicit about what it's checking for. So instead of "we have an ops cluster" being passed to the test, we just pass the explicit list of `DeploymentConfig`s to look for. Similarly, I'd rather not auto-discover stuff because that means a bug in the test discovery code means the tests never run. I'd rather be very explicit and have tests under `test/` that know how to do one thing well.

**Comment by stevekuznetsov** [comment]
> Right - but - we still need to do some sort of automated upgrade testing

If there is no upgrade playbook in OpenShift-Ansible, this is just running the logging installer playbooks with newer versions, right?

**Comment by stevekuznetsov** [comment]
Right now the jobs are running this:

```sh
export KUBECONFIG=/etc/origin/master/admin.kubeconfig
export TEST_ONLY=true
export ENABLE_OPS_CLUSTER=true
export USE_LOCAL_SOURCE=true
export OS_O_A_L_DIR="$( pwd )"
export OS_ROOT="$( realpath ./../origin )"
hack/testing/check-EFK-running.sh
hack/testing/check-logs.sh
hack/testing/test-datetime-future.sh
hack/testing/test-curator.sh "${ENABLE_OPS_CLUSTER}"
USE_MUX_CLIENT=true MUX_ALLOW_EXTERNAL=true hack/testing/test-mux.sh || true
hack/testing/test-viaq-data-model.sh || true
hack/testing/test-mux.sh || true
hack/testing/test-fluentd-forward.sh || true
```

Are we against adding a different entrypoint script that we can evolve forward that would run all this instead of having to evolve `hack/testing/logging.sh` backward? Or would we rather do work on `logging.sh`?

**Comment by richm** [comment]
@stevekuznetsov It doesn't matter to me if we use logging.sh or not, as long as we have some entrypoint that both automated CI and developers can use.  That is, I, as a logging developer, should be able to launch the logging setup + tests exactly as done by Jenkins.

So in the new way of doing things - how does a developer add a new test to the CI?

**Comment by stevekuznetsov** [comment]
> So in the new way of doing things - how does a developer add a new test to the CI?

As per the "proposal" section at the top, I would expect a new test to be written as such:

 - a parameterized script is written under `test/` that knows how to execute one test on a real cluster with whatever special pre-conditions set-up already (admin user, logging driver, whatever)
 - a script is written under `hack/testing/test-*.sh` to trigger the test and optionally do test-specific set-up on the cluster
 - if the install configuration need be changed, the developer would need to change `hack/testing/setup.sh` for the local case and the jobs in `aos-cd-jobs` for CI

Having that setup in two places is not the best but if we need to support local devs running from nothing we need to have a path in the logging repo to do it, but for CI it does not make sense for that to be the source of truth (or pulls to openshift-ansible would need to amend logging repo setup scripts... that call playbooks in openshift-ansible).

**Comment by richm** [comment]
works for me

**Comment by stevekuznetsov** [comment]
Pull to add a new entrypoint in #450 

Current failure output from bad tests:

<details>
<summary><code>hack/testing/test-datetime-future.sh</code></summary>

```
[INFO] Logging test suite test-datetime-future started at Thu Jun  1 12:52:47 EDT 2017

No resources found.

error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
POD_NAME and COMMAND are required arguments for the exec command
See 'oc exec -h' for help and examples.
[WARNING] Logging suite test-datetime-future failed at Thu Jun  1 12:52:49 EDT 2017
[INFO] Logging suite test-datetime-future failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-es-copy.sh</code></summary>

```
[INFO] Logging test suite test-es-copy started at Thu Jun  1 12:52:49 EDT 2017

No resources found.
Error from server (NotFound): templates.template.openshift.io "logging-fluentd-template" not found
[WARNING] Logging suite test-es-copy failed at Thu Jun  1 12:52:51 EDT 2017
[INFO] Logging suite test-es-copy failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-fluentd-forward.sh</code></summary>

```
[INFO] Logging test suite test-fluentd-forward started at Thu Jun  1 12:52:52 EDT 2017

No resources found.
START wait_for_fluentd_to_catch_up at 2017-06-01 16:52:53.342127097+00:00
No resources found.

No resources found.
No resources found.
added es message 39ab1acc-c19b-46b7-8e28-a85298d61cd2
added es-ops message 346f22ab-60c1-4740-9c9a-128b016c800b
/data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

/data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
...
Error: found for project .operations message 346f22ab-60c1-4740-9c9a-128b016c800b - expected 1
/data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
No JSON object could be decoded
/data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
No JSON object could be decoded
failed - wait_for_fluentd_to_catch_up: not found 1 record project .operations for 346f22ab-60c1-4740-9c9a-128b016c800b after 300 seconds
Checking journal for 346f22ab-60c1-4740-9c9a-128b016c800b...

Jun 01 12:52:54 ip-172-18-6-83.ec2.internal 346f22ab-60c1-4740-9c9a-128b016c800b[65764]: 346f22ab-60c1-4740-9c9a-128b016c800b
Found 346f22ab-60c1-4740-9c9a-128b016c800b in journal
END wait_for_fluentd_to_catch_up took 617 seconds at 2017-06-01 17:03:10.404548612+00:00

error: expected 'logs (POD | TYPE/NAME) [CONTAINER_NAME]'.
POD or TYPE/NAME is a required argument for the logs command
See 'oc logs -h' for help and examples.
[WARNING] Logging suite test-fluentd-forward failed at Thu Jun  1 13:03:10 EDT 2017
[INFO] Logging suite test-fluentd-forward failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-json-parsing.sh</code></summary>

```
[INFO] Logging test suite test-json-parsing started at Thu Jun  1 13:03:11 EDT 2017
Adding test message 9f248532-6417-4d81-95e5-31665fb9e88e to Kibana . . .

Waiting 600 seconds for 9f248532-6417-4d81-95e5-31665fb9e88e to show up in Elasticsearch . . .

good - /data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-json-parsing.sh: found 1 record project logging for 9f248532-6417-4d81-95e5-31665fb9e88e
Testing if record is in correct format . . .
python: can't open file 'test-json-parsing.py': [Errno 2] No such file or directory
[WARNING] Logging suite test-json-parsing failed at Thu Jun  1 13:03:39 EDT 2017
[INFO] Logging suite test-json-parsing failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-mux.sh</code></summary>

```
[INFO] Logging test suite test-mux started at Thu Jun  1 13:03:39 EDT 2017
/data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-mux.sh: line 19: USE_MUX_CLIENT: unbound variable
[WARNING] Logging suite test-mux failed at Thu Jun  1 13:03:39 EDT 2017
[INFO] Logging suite test-mux failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-upgrade.sh</code></summary>

```
[INFO] Logging test suite test-upgrade started at Thu Jun  1 13:03:40 EDT 2017
/data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-upgrade.sh: line 29: ../../deployer/scripts/util.sh: No such file or directory
[WARNING] Logging suite test-upgrade failed at Thu Jun  1 13:03:40 EDT 2017
[INFO] Logging suite test-upgrade failure result ignored
```

</details>

<details>
<summary><code>hack/testing/test-viaq-data-model.sh</code></summary>

```
[INFO] Logging test suite test-viaq-data-model started at Thu Jun  1 13:03:41 EDT 2017

No resources found.
Error from server (NotFound): templates.template.openshift.io "logging-fluentd-template" not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[WARNING] Logging suite test-viaq-data-model failed at Thu Jun  1 13:03:42 EDT 2017
[INFO] Logging suite test-viaq-data-model failure result ignored
```

</details>

**Comment by richm** [comment]
On 06/01/2017 11:16 AM, Steve Kuznetsov wrote:
>
> Pull to add a new entrypoint in #450
>
> Current failure output from bad tests:
> hack/testing/test-datetime-future.sh
> [INFO] Logging test suite test-datetime-future started at Thu Jun  1 12:52:47 EDT 2017
>
> No resources found.
>
> error: expected 'exec POD_NAME COMMAND [ARG1] [ARG2] ... [ARGN]'.
> POD_NAME and COMMAND are required arguments for the exec command
> See 'oc exec -h' for help and examples.
> [WARNING] Logging suite test-datetime-future failed at Thu Jun  1 12:52:49 EDT 2017
> [INFO] Logging suite test-datetime-future failure result ignored

This means get_running pod fluentd failed.  So either fluentd was not running, or the get_running_pod() logic is not correct.
```
# make sure the host/node TZ is the same as the fluentd pod
fpod=`get_running_pod fluentd`
nodetz=`date +%z`
podtz=`oc exec $fpod -- date +%z`
```
> hack/testing/test-es-copy.sh
> [INFO] Logging test suite test-es-copy started at Thu Jun  1 12:52:49 EDT 2017
>
> No resources found.
> Error from server (NotFound): templates.template.openshift.io "logging-fluentd-template" not found
> [WARNING] Logging suite test-es-copy failed at Thu Jun  1 12:52:51 EDT 2017
> [INFO] Logging suite test-es-copy failure result ignored

The fluentd-template is not found.  We either need to add it in the test if it doesn't already exist, or rewrite the test to not use the template (recommended).

>
> hack/testing/test-fluentd-forward.sh
> [INFO] Logging test suite test-fluentd-forward started at Thu Jun  1 12:52:52 EDT 2017
>
> No resources found.
> START wait_for_fluentd_to_catch_up at 2017-06-01 16:52:53.342127097+00:00
> No resources found.
>
> No resources found.
> No resources found.
> added es message 39ab1acc-c19b-46b7-8e28-a85298d61cd2
> added es-ops message 346f22ab-60c1-4740-9c9a-128b016c800b
> /data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
>
> /data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
> ...
> Error: found for project .operations message 346f22ab-60c1-4740-9c9a-128b016c800b - expected 1
> /data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
> No JSON object could be decoded
> /data/src/github.com/openshift/origin-aggregated-logging/deployer/scripts/util.sh: line 423: 5: unbound variable
> No JSON object could be decoded
> failed - wait_for_fluentd_to_catch_up: not found 1 record project .operations for 346f22ab-60c1-4740-9c9a-128b016c800b after 300 seconds
> Checking journal for 346f22ab-60c1-4740-9c9a-128b016c800b...
>
> Jun 01 12:52:54 ip-172-18-6-83.ec2.internal 346f22ab-60c1-4740-9c9a-128b016c800b[65764]: 346f22ab-60c1-4740-9c9a-128b016c800b
> Found 346f22ab-60c1-4740-9c9a-128b016c800b in journal
> END wait_for_fluentd_to_catch_up took 617 seconds at 2017-06-01 17:03:10.404548612+00:00
>
> error: expected 'logs (POD | TYPE/NAME) [CONTAINER_NAME]'.
> POD or TYPE/NAME is a required argument for the logs command
> See 'oc logs -h' for help and examples.
> [WARNING] Logging suite test-fluentd-forward failed at Thu Jun  1 13:03:10 EDT 2017
> [INFO] Logging suite test-fluentd-forward failure result ignored

probably     local es_pod=`get_running_pod es` failed - problem with get_running_pod() logic?

>
> hack/testing/test-json-parsing.sh
> [INFO] Logging test suite test-json-parsing started at Thu Jun  1 13:03:11 EDT 2017
> Adding test message 9f248532-6417-4d81-95e5-31665fb9e88e to Kibana . . .
>
> Waiting 600 seconds for 9f248532-6417-4d81-95e5-31665fb9e88e to show up in Elasticsearch . . .
>
> good - /data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-json-parsing.sh: found 1 record project logging for 9f248532-6417-4d81-95e5-31665fb9e88e
> Testing if record is in correct format . . .
> python: can't open file 'test-json-parsing.py': [Errno 2] No such file or directory

missing file?

>
> [WARNING] Logging suite test-json-parsing failed at Thu Jun  1 13:03:39 EDT 2017
> [INFO] Logging suite test-json-parsing failure result ignored
> hack/testing/test-mux.sh
> [INFO] Logging test suite test-mux started at Thu Jun  1 13:03:39 EDT 2017
> /data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-mux.sh: line 19: USE_MUX_CLIENT: unbound variable
> [WARNING] Logging suite test-mux failed at Thu Jun  1 13:03:39 EDT 2017
> [INFO] Logging suite test-mux failure result ignored

Should use `"${USE_MUX_CLIENT:-}"` instead of raw unprotected variable access - same with `$MUX_ALLOW_EXTERNAL`

Or - make sure these variables are always set

>
> hack/testing/test-upgrade.sh
> [INFO] Logging test suite test-upgrade started at Thu Jun  1 13:03:40 EDT 2017
> /data/src/github.com/openshift/origin-aggregated-logging/hack/testing/test-upgrade.sh: line 29: ../../deployer/scripts/util.sh: No such file or directory
> [WARNING] Logging suite test-upgrade failed at Thu Jun  1 13:03:40 EDT 2017
> [INFO] Logging suite test-upgrade failure result ignored

This test must be skipped for now

>
> hack/testing/test-viaq-data-model.sh
> [INFO] Logging test suite test-viaq-data-model started at Thu Jun  1 13:03:41 EDT 2017
>
> No resources found.
> Error from server (NotFound): templates.template.openshift.io "logging-fluentd-template" not found

fluentd-template again

>
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded
> [WARNING] Logging suite test-viaq-data-model failed at Thu Jun  1 13:03:42 EDT 2017
> [INFO] Logging suite test-viaq-data-model failure result ignored

**Comment by jcantrill** [comment]
I believe these PRs fulfill the missing tests
- https://github.com/openshift/origin-aggregated-logging/pull/570
- https://github.com/openshift/origin-aggregated-logging/pull/568
- https://github.com/openshift/origin-aggregated-logging/pull/567
- https://github.com/openshift/origin-aggregated-logging/pull/566
- https://github.com/openshift/origin-aggregated-logging/pull/565
