### ISSUE TITLE
Origin 1.4.1 to 1.5.1 fluentd nodeselector in hosts

### ISSUE THREAD

**Issue by jantzen05** [openshift/origin-aggregated-logging#458]
running openshift-logging.yml upgrade with parameter openshift_logging_fluentd_nodeselector="logging-infra-fluentd=true" in /etc/ansible/hosts results in error:
`fatal: [serverX]: FAILED! => {"failed": true, "msg": "The conditional check '{{ openshift_logging_fluentd_nodeselector.keys() | count }} > 1' failed. The error was: error while evaluating conditional ({{ openshift_logging_fluentd_nodeselector.keys() | count }} > 1): 'unicode object' has no attribute 'keys'\n\nThe error appears to have been in '/opt/openshift/openshift-ansible/roles/openshift_logging/tasks/main.yaml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- fail:\n  ^ here\n"}
`
I added the nodeselector to have it in the configuration and not depend on the defaults.

**Comment by jantzen05** [comment]
This belong in openshift-ansible.
I get past this error but not having the variable in the ansible hosts file.

**Comment by jcantrill** [comment]
@ewolinetz Any ideas of the issue here?  Possibly the node selector needs to be defined as a map?

**Comment by ewolinetz** [comment]
@jantzen05 you should have `openshift_logging_fluentd_nodeselector={"logging-infra-fluentd": "true"}` which is the default. You can likely remove that from your hosts file all together.

**Comment by jantzen05** [comment]
I removed it, but also tried with this notation:
openshift_logging_fluentd_nodeselector={"logging-infra-fluentd": "true"}
I had written:
openshift_logging_fluentd_nodeselector="logging-infra-fluentd=true" which didn't work.
After moving the properties into the hosts file I did not change the notation.
