### ISSUE TITLE
Incorrect year used for syslog based message operations index

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#46]
When pulling in log files from the previous year in the current year; the index the logs are first created for are the current year.

E.g. logs from 12/27/2015 will be created in the index ".operations.2016.12.27" if it is read in in 2016 initially

**Comment by ewolinetz** [comment]
Should we do something like this in the record_transformer filter?
```
time ${Time.parse(Time.parse(time).to_s.gsub(Time.parse(time).year.to_s, (Time.parse(time).year - years_ago).to_s )) if Time.parse(time) > Time.now}
```
How can we figure out what `years_ago` should be?
  - parse from file name somehow?

Can using rsyslog resolve this for older, existing log files?

**Comment by portante** [comment]
@ewolinetz, what logs is fluentd reading?  Just `/var/log/messages`, or are you trying to ingest all log files in `/var/log/messages*.gz`?

**Comment by ewolinetz** [comment]
@portante `/var/log/messages*` so that would include any .gz I suppose.  At least, it would attempt to `tail` them.

https://github.com/ewolinetz/origin-aggregated-logging/blob/fix_syslog_date/fluentd/fluent.conf#L131

**Comment by portante** [comment]
@ewolinetz, do we have control over how rsyslog is configured to write to /var/log/messages?  Or is this something that we have no control over?

**Comment by ewolinetz** [comment]
@portante at this time, we should assume we don't have control over it.  When we change to a solution where rsyslog is the primary means of collecting and processing logs, then we would have control over how rsyslog is configured.  We have a card on our trello board to track that future effort (https://trello.com/c/oUvJg3JR/188-r-d-use-rsyslog-instead-of-fluentd-logging).

**Comment by portante** [comment]
It is also important to get the timezone right, normalized to UTC and then to choose the index.  Otherwise, clients might not be looking in the right index entirely.
