### ISSUE TITLE
Move ES DC names to use ordinal values in prep for stateful sets

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#468]
We should REALLY consider modifying the way we generate ES dc names to be 0-N (or 1-N) based in anticipation of moving to stateful sets.  We do have an 'upgrade' scenario to consider but given our only real requirement now is to mate an existing PV to an ES instance I see this as not a huge issue.  Also once we have a mechanism to migrate PV (PVC?) names it will be considerably easier.  Thought?

@richm @ewolinetz @lukas-vlcek @portante

**Comment by portante** [comment]
Why not have DC names match the PV since it is one-to-one?

**Comment by ewolinetz** [comment]
@portante we recently updated logic so that a DC should keep the pv it used before.
@jcantrill once we have stateful sets won't this be a non-issue since we wouldn't need to generate one DC per PVC?

**Comment by jcantrill** [comment]
@ewolinetz I guess it depends how we do greenfield PVCs now; I dont recall.  If we provide a PVC which will match what stateful sets do now... then DC generation name is a non-issue.  The names will match correctly when we move there.

**Comment by jcantrill** [comment]
Closing as likely we never will move to stateful sets.  We may need to wait for a PV migration tool if we ever wish to implement
