### ISSUE TITLE
Switch to curl --head

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#485]
Currently, we use `curl -X HEAD` to hit Elasticsearch in some cases in our scripts. Based on the below forum thread we should consider testing and possibly adding `--head` to `curl` calls as part of ES 5 upgrade.

https://discuss.elastic.co/t/head-no-longer-works-in-5-4-1/89321/3
(or another one here: https://discuss.elastic.co/t/curl-i-xhead-never-finish/89375)

//cc @t0ffel

**Comment by t0ffel** [comment]
yes, I'm going to test if --head works. because `-X HEAD` doesn't work for me in ES5.

/cc @portante

**Comment by t0ffel** [comment]
using `--head` in https://github.com/openshift/origin-aggregated-logging/pull/504
