### ISSUE TITLE
Cannot log into Kibana as user with 'project-admin' permission in 'logging' project

### ISSUE THREAD

**Issue by josefkarasek** [openshift/origin-aggregated-logging#487]
Search guard doesn't allow the user to view logs in kibana. Needed to change the permissions to cluster-admin.

**Comment by jcantrill** [comment]
@josefkarasek need some more details of what version you are testing, and the source of your images.  This change [1] modified how a user is able to view logs.  It is essentially equivalent to 'oc policy who-can view logs -n $namespace'
[1] https://github.com/openshift/origin-aggregated-logging/commit/7b8f90c10ba27bd174773587138ebff4d2b16299

**Comment by josefkarasek** [comment]
Can't reproduce
