### ISSUE TITLE
Add Logtrail plugin to kibana to see the logs in kibana ui

### ISSUE THREAD

**Issue by expuser111** [openshift/origin-aggregated-logging#488]
Hi, I would like to install the logtrail plugin into the openshift/origin-logging-kibana docker image and build my own image, so I could view my logs properly in kibana ui.

I create a docker file like

FROM openshift/origin-logging-kibana:latest
RUN kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz
ADD logtrail.json /opt/kibana/installedPlugins/logtrail/logtrail.json

But when i build the image, is showing error

Sending build context to Docker daemon  7.68 kB
Step 1 : FROM openshift/origin-logging-kibana:latest
 ---> d5e3ce4a04ca
Step 2 : RUN kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz
 ---> Running in e18ceeb7083c
/bin/sh: kibana: command not found
The command '/bin/sh -c kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz' returned a non-zero code: 127

In order to solve this, I gave  larsla/kibana-logtrail instead of docker.io/openshift/origin-logging-kibana:latest as docker image to the yml of logging-kibana deployments. When i logged into kibana ui, the logtrailer plugin installed successfully, but kibana couldnt connect to elastic search.
I gave environment variable  ELASTICSEARCH_URL = https://logging-es:9200
the error in get in log is 
log [22:52:02.901] [warning][elasticsearch] Unable to revive connection: https://logging-es:9200/
log [22:52:02.902] [warning][elasticsearch] No living connections
log [22:52:05.442] [warning][elasticsearch] Unable to revive connection: https://logging-es:9200/
log [22:52:05.443] [warning][elasticsearch] No living connections
log [22:52:02.901] [warning][elasticsearch] Unable to revive connection: https://logging-es:9200/
log [22:52:02.902] [warning][elasticsearch] No living connections
log [22:52:05.442] [warning][elasticsearch] Unable to revive connection: https://logging-es:9200/
log [22:52:05.443] [warning][elasticsearch] No living connections

Has anyone tried to incorporate logtrail plugin in EFK stack?

**Comment by jcantrill** [comment]
You look to first have a build issue:

> ---> Running in e18ceeb7083c
/bin/sh: kibana: command not found
The command '/bin/sh -c kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz' returned a non-zero code: 127

kibana is not in the path and the image runs calling an absolute: https://github.com/openshift/origin-aggregated-logging/blob/master/kibana/run.sh#L16

I do not know what else is happening, but this Kibana image works in conjuction with the remaing EFK stack and expects to connect to ES using certificates and requires a user to authenticate using the Openshift auth flow.

**Comment by expuser111** [comment]
Is there any way to install a plugin in the openshift/origin-logging-kibana ?
 or to remove  /bin/sh: kibana: command not found  ?error

**Comment by jcantrill** [comment]
You can remove the error by supplying the proper path to the Kibana executable directory.  You are on the correct path of building your own image.

**Comment by expuser111** [comment]
Hi,
I created the docker image

FROM openshift/origin-logging-kibana:latest
ENV HOME=/opt/app-root/src \
    KIBANA_HOME=/opt/kibana
RUN mkdir ${KIBANA_HOME}/pluginsh/
RUN  echo '#!/bin/bash \
set -e \
# Add kibana as command if needed \
if [[ "$1" == -* ]]; then \
	set -- kibana "$@" \
fi \
# Run as user "kibana" if the command is "kibana" \
if [ "$1" = 'kibana' ]; then  \
	if [ "$ELASTICSEARCH_URL" ]; then \
		sed -ri "s!^(\#\s*)?(elasticsearch\.url:).*!\2 '$ELASTICSEARCH_URL'!" /opt/kibana/config/kibana.yml \
	fi \
	set -- gosu kibana tini -- "$@" \
fi \
exec "$@"' > ${KIBANA_HOME}/pluginsh/run.sh
RUN cd ${KIBANA_HOME}/pluginsh/ && sh run.sh kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-5.4.1-0.1.14.zip
ADD logtrail.json /opt/kibana/installedPlugins/logtrail/logtrail.json

Now i was able to build the image and start kibana successfully. Kibana could connect to elasticsearch.
 But i see the below warn in kibana log and logtrail plugin is not installed. But I can see logtrail in /opt/kibana/installedPlugins/

{"type":"log","@timestamp":"2017-06-16T07:22:37Z","tags":["plugins","warning"],"pid":1,"path":"/opt/kibana/installedPlugins/logtrail","message":"Skipping non-plugin directory at /opt/kibana/installedPlugins/logtrail"}

Any help on this?

**Comment by jcantrill** [comment]
Are you certain this plugin is compatible with the version of Kibana we are using, which 4.x line?  From the addition of the plugin added for Openshift, it required us to modify the index.js file to include our plugin.  Based upon the zip URL I would suspect it is not compatible and is designed for  5.4.

**Comment by expuser111** [comment]
Sorry, that was a typo
the  logtrail plugin im using is 
RUN cd ${KIBANA_HOME}/pluginsh/ && kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.4/logtrail-4.x-0.1.4.tar.gz

but i have not updated index.js file. Can you please guide me in adding a new plugin?

**Comment by jcantrill** [comment]
@expuser111 Trying to resolve why our plugin is successful and I am unable to affirmatively see why it works.  We copy our plugin straight to the installed plugins dir [1]. The proper way to install plugins can be found [2]

[1] https://github.com/openshift/origin-aggregated-logging/blob/master/kibana/prep-install.origin#L9-L11
[2] https://www.elastic.co/guide/en/kibana/4.6/kibana-plugins.html

**Comment by pat2man** [comment]
This Dockerfile worked for me:

```Dockerfile
FROM openshift/origin-logging-kibana:latest
RUN /opt/kibana/bin/kibana plugin -i logtrail -u https://github.com/sivasamyk/logtrail/releases/download/0.1.14/logtrail-4.x-0.1.14.tar.gz
```

but I get prompted for a username and password. I assume there would be some further setup to point at the correct es config and index.
