### ISSUE TITLE
Fluent-plugin-parser missing?

### ISSUE THREAD

**Issue by ecwhipple** [openshift/origin-aggregated-logging#498]
I am looking at extending the functionality of origin-aggregated-logging to include parsing out the nested JSON from 'messages'. 

If I edit the Config Map to include a match stanza with '@type parser', then delete the pod (which spawns a new pod with the new config),
```
      <match kubernetes.var.log**>
        @type parser
        format json
        format1 /\s+time="(?<time>\d+-\d+-\d+.\d+:\d+:\d+.)"\slevel=(?<level>.*)\smsg="(?<msg>[^"]*)"\sevent="(?<event>[^"]*)"\srows=(?<rows>.*)/
        time_format %Y-%m-%dT%H:%M:%S
        key_name message
        reserve_data true
      </match>
```

I find the following messages in the logs at startup:
```
2017-06-20 15:08:28 -0500 [error]: fluent/supervisor.rb:165:start: fluentd main process died unexpectedly. restarting.
...
2017-06-20 15:08:34 -0500 [error]: fluent/supervisor.rb:369:rescue in main_process: config error file="/etc/fluent/fluent.conf" error="Unknown output plugin 'parser'. Run 'gem search -rd fluent-plugin' to find plugins"
```

Looking at the output of `gem list` on a running pod I see that the plugin does not appear to be installed:
```
sh-4.2# gem list 
...
ffi (1.9.14)                 
fluent-plugin-docker_metadata_filter (0.1.1)
fluent-plugin-elasticsearch (1.9.1)
fluent-plugin-flatten-hash (0.4.0)
fluent-plugin-kubernetes_metadata_filter (0.26.2)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluent-plugin-secure-forward (0.4.3)
fluent-plugin-systemd (0.0.5)
fluentd (0.12.29)            
http (0.9.8) 
...
```

I can install the plugin on the pod but it looks like the plugin list is managed in the fluentd/Dockerfile:
```
sh-4.2# gem install fluent-plugin-parser
Fetching: fluent-plugin-parser-0.6.1.gem (100%)
Successfully installed fluent-plugin-parser-0.6.1
Parsing documentation for fluent-plugin-parser-0.6.1
Installing ri documentation for fluent-plugin-parser-0.6.1
1 gem installed 
```

I am looking to confirm that adding that plugin to the Dockerfile will provide the functionality that I am after. Are there other hooks or caveats I should be aware of? I ask before making changes because it may spawn the rebuilding of an entire production environment.

**Comment by jcantrill** [comment]
All plugins are built into the image via the Dockerfile.  Additionally config is managed by openshift-andible openshift_logging role.  I suggest looking at the run.sh script to understand how configuration is consumed.  Most is pushed into a configmap if I recall and referenced by the fluentd daemonset.

**Comment by richm** [comment]
We don't currently have a way to install custom plugins in the fluentd image.  You'll have to build your own, based on the logging-fluentd image, if you want to use that plugin.  Or, submit a PR that adds that plugin to our base image.
