### ISSUE TITLE
origin-logging-elasticsearch container keeps crashing

### ISSUE THREAD

**Issue by Havilland** [openshift/origin-aggregated-logging#515]
Hello,

when I try to deploy the elasticsearch container it's crashing all the time. 

The following lines are outputted in the logs: 

> [2017-07-03 12:06:59,980][INFO ][container.run            ] Begin Elasticsearch startup script
> [2017-07-03 12:06:59,984][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
> [2017-07-03 12:06:59,985][INFO ][container.run            ] Inspecting the maximum RAM available...
> [2017-07-03 12:06:59,988][INFO ][container.run            ] ES_HEAP_SIZE: '4096m'
> [2017-07-03 12:06:59,989][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/hdump.prof
> [2017-07-03 12:06:59,995][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
> [2017-07-03 12:07:01,265][INFO ][node                     ] [Aleta Ogord] version[2.4.4], pid[1], build[fcbb46d/2017-01-03T11:33:16Z]
> [2017-07-03 12:07:01,266][INFO ][node                     ] [Aleta Ogord] initializing ...
> [2017-07-03 12:07:02,245][INFO ][plugins                  ] [Aleta Ogord] modules [reindex, lang-expression, lang-groovy], plugins [openshift-elasticsearch, cloud-kubernetes], sites []
> [2017-07-03 12:07:02,422][INFO ][env                      ] [Aleta Ogord] using [1] data paths, mounts [[/elasticsearch/persistent (172.27.154.42:/vol_inx_nl1_oscpdata1/logging)]], net usable_space [379.7gb], net total_space [380gb], spins? [possibly], types [nfs4]
> [2017-07-03 12:07:02,422][INFO ][env                      ] [Aleta Ogord] heap size [3.9gb], compressed ordinary object pointers [true]
> [2017-07-03 12:07:03,440][INFO ][http                     ] [Aleta Ogord] Using [org.elasticsearch.http.netty.NettyHttpServerTransport] as http transport, overridden by [search-guard2]
> [2017-07-03 12:07:03,826][INFO ][transport                ] [Aleta Ogord] Using [com.floragunn.searchguard.transport.SearchGuardTransportService] as transport service, overridden by [search-guard2]
> [2017-07-03 12:07:03,827][INFO ][transport                ] [Aleta Ogord] Using [com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] as transport, overridden by [search-guard-ssl]
> [2017-07-03 12:07:07,841][INFO ][io.fabric8.elasticsearch.plugin.kibana.IndexMappingLoader] Trying to load Kibana mapping for io.fabric8.elasticsearch.kibana.mapping.app from plugin: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
> [2017-07-03 12:07:07,925][INFO ][io.fabric8.elasticsearch.plugin.kibana.IndexMappingLoader] Trying to load Kibana mapping for io.fabric8.elasticsearch.kibana.mapping.ops from plugin: /usr/share/elasticsearch/index_patterns/com.redhat.viaq-openshift.index-pattern.json
> Exception in thread "main" java.lang.RuntimeException: Unable to load index mapping for io.fabric8.elasticsearch.kibana.mapping.empty.  The key was not in the settings or it specified a file that does not exists.
> 	at io.fabric8.elasticsearch.plugin.kibana.IndexMappingLoader.loadMapping(IndexMappingLoader.java:56)
> 	at io.fabric8.elasticsearch.plugin.kibana.IndexMappingLoader.<init>(IndexMappingLoader.java:42)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at <<<guice>>>
> 	at org.elasticsearch.node.Node.<init>(Node.java:213)
> 	at org.elasticsearch.node.Node.<init>(Node.java:140)
> 	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
> 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
> 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
> 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
> 

Has someone any ideas on what to to here?

**Comment by richm** [comment]
What version of openshift are you using?  Are you installing using openshift ansible?  Can you provide your ansible inventory file? It looks like you have some mismatch between what's in your configuration (provided usually by ansible) and what's in the elasticsearch image.

**Comment by Havilland** [comment]
Yes I used the ansible installation file using openshift 1.5.1 

> openshift_deployment_type=origin
> openshift_release=1.5.1
> openshift_install_examples=true
> 
> osm_use_cockpit=true
> osm_cockpit_plugins=['cockpit-kubernetes']
> 
> openshift_master_cluster_method=native
> openshift_master_cluster_hostname=XX
> openshift_master_cluster_public_hostname=XY
> 
> openshift_hosted_registry_storage_kind=nfs
> openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
> openshift_hosted_registry_storage_host=172.27.xx.xx
> openshift_hosted_registry_storage_nfs_directory=/
> openshift_hosted_registry_storage_volume_name=registry
> openshift_hosted_registry_storage_volume_size=10Gi
> 
> openshift_hosted_metrics_deploy=true
> 
> openshift_hosted_metrics_storage_kind=nfs
> openshift_hosted_metrics_storage_access_modes=['ReadWriteOnce']
> openshift_hosted_metrics_storage_host=172.27.xx.xx
> openshift_hosted_metrics_storage_nfs_directory=/
> openshift_hosted_metrics_storage_volume_name=metrics
> openshift_hosted_metrics_storage_volume_size=10Gi
> 
> openshift_hosted_logging_deploy=true
> 
> openshift_hosted_logging_storage_kind=nfs
> openshift_hosted_logging_storage_access_modes=['ReadWriteOnce']
> openshift_hosted_logging_storage_host=172.27.xx.xx
> openshift_hosted_logging_storage_nfs_directory=/
> openshift_hosted_logging_storage_volume_name=logging
> openshift_hosted_logging_storage_volume_size=10Gi
> 
> os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
> osm_cluster_network_cidr=10.129.0.0/16
> openshift_portal_net=10.130.0.0/16
> 
> osm_host_subnet_length=8
>

This is a multi master setup where the etcd hosts are installed on the masters.

What mismatch could result in this error?

Thank you for your answer!

**Comment by jcantrill** [comment]
You need to get a later version of ansible or manually update your configmap to be: https://github.com/openshift/openshift-ansible/pull/4657/files#diff-2893638087fc0f7bf540326310711b82R43

**Comment by richm** [comment]
Also note that when using `openshift_deployment_type=origin` the default version of the logging images will be `latest`.  You need to specify that the logging image version is `1.5.1`.

**Comment by Havilland** [comment]
@jcantrill I updated the config map and it worked, thank you for your help.

Can there be any problems if I have the latest logging images instead of the 1.5.1?

**Comment by jcantrill** [comment]
@Havilland The latest 1.5 changes will be available once https://github.com/openshift/origin-aggregated-logging/pull/519 merges.   There can always be issues when you work with the latest images.  We strive to ensure our CI catches breaking changes but there is never 100% coverage

**Comment by jcantrill** [comment]
Closing as I believe we have generally resolved your issue.  Please reopen as necessary.
