### ISSUE TITLE
Access other ES indicies from Kibana UI

### ISSUE THREAD

**Issue by stephenrlouie** [openshift/origin-aggregated-logging#537]
I'm deploying a [1.5 Openstack cluster with aggregated logging](https://github.com/openshift/openshift-ansible/tree/release-1.5) and wanted to use the EFK stack for more than this cluster. I deployed a fluentd aggregator that is pushing logs into the ES instance under a different index, lets say: `project.test.agg`. I cannot find the right role to assign to my user to let them access all ES indicies. (I've tried cluster-admin, I receive a `Courier Fetch Error: .... Authentication Exception` when I go to the kibana UI, adding `oadm policy add-role-to-user -n logging view <my user>` will let me see the logging index, so I think I'm in the right ball park for adding a role to my user.) 

I have confirmed that the index exists and logs are in ES, I've curled the [index API](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-get-index.html) for es and see the correct logs. If I push my aggregated logs into an existing index, I can see them along side the existing logs I have for "my project" 

If there is a better place for me to share this, let me know and we can close this.

**Comment by richm** [comment]
The index name must be in the following format in order to work with the OpenShift aggregated logging EFK stack: project.$project_name.$project_uuid.YYYY.MM.DD - where $project_name is the name of an existing OpenShift project, $project_uuid is the uuid (uid) of $project_name, YYYY is the 4 digit year, MM is the 2 digit (leading 0) month, and DD is the 2 digit (leading 0) day.

**Comment by stephenrlouie** [comment]
thanks @richm! good to know. Could you point me to where that is configured? Also is that error `Courier Fetch Error` expected when running `oadm policy add-cluster-role-to-user cluster-admin <my_user>`. I can open up a bug if that is not the desired behavior.

**Comment by richm** [comment]
> Could you point me to where that is configured?

Where what is configured?  The index name pattern that we use?  https://github.com/openshift/origin-aggregated-logging/blob/master/fluentd/configs.d/openshift/output-es-config.conf#L6
```
 index_name project.${begin record['kubernetes']['namespace_name'] rescue $log.error("record is missing kubernetes.namespace_name - record " + record.to_s) end}.${begin record['kubernetes']['namespace_id'] rescue $log.error("record is missing kubernetes.namespace_id - record " + record.to_s) end}.${begin Time.parse(record['@timestamp']).getutc.strftime(@logstash_dateformat) rescue $log.error("record is missing @timestamp - record " + record.to_s) end}
```

I've never seen `Courier Fetch Error` - you might ask the openshift origin guys about that.

`oc get project -o yaml|grep uid`

**Comment by stephenrlouie** [comment]
I'm curious where the config is for kibana to only display those logs specifically. I have been able to add any kind of index to ES, as I've added my own and curl'd ES. But I guess there is something in kibana that will only display logs of that follow that format.

**Comment by stephenrlouie** [comment]
thanks @richm, closing since that answers my question
