### ISSUE TITLE
logging-fluentd connection refused to ElasticSearch

### ISSUE THREAD

**Issue by danbev** [openshift/origin-aggregated-logging#54]
We are running into an issue following the [documentation](https://access.redhat.com/documentation/en/openshift-enterprise/3.1/installation-and-configuration/chapter-17-aggregating-container-logs). We have basically followed the docs apart from calling the our project ```mbaas-logging``` instead of the default. 

The issue we are seeing is with the fluentd pod:
```shell
$ oc logs -f logging-fluentd-1-3925v
2016-01-25 08:02:35 -0500 [info]: reading config file path="/etc/fluent/fluent.conf"
2016-01-25 08:04:06 -0500 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-25 08:02:48 -0500 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"logging-es.mbaas-logging.svc.cluster.local\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd\", :password=>\"obfuscated\"})! Connection refused - connect(2) (Errno::ECONNREFUSED)" plugin_id="object:1421250"
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:61:in `rescue in client'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:58:in `client'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:184:in `rescue in send'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:182:in `send'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:174:in `block in write'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:173:in `each'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluent-plugin-elasticsearch-1.0.0/lib/fluent/plugin/out_elasticsearch_dynamic.rb:173:in `write'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluentd-0.12.16/lib/fluent/buffer.rb:325:in `write_chunk'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluentd-0.12.16/lib/fluent/buffer.rb:304:in `pop'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluentd-0.12.16/lib/fluent/output.rb:321:in `try_flush'
  2016-01-25 08:04:06 -0500 [warn]: /usr/share/gems/gems/fluentd-0.12.16/lib/fluent/output.rb:140:in `run'
2016-01-25 08:05:39 -0500 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-25 08:02:50 -0500
error_class="Fluent::ElasticsearchOutput::ConnectionFailure" 
error="Can not reach Elasticsearch cluster 
({:host=>\"logging-es.mbaas-logging.svc.cluster.local\", 
:port=>9200, 
:scheme=>\"https\", 
:user=>\"fluentd\",  
:password=>\"obfuscated\"})! 
Connection refused - connect(2) (Errno::ECONNREFUSED)" plugin_id="object:1421250"
2016-01-25 08:05:39 -0500 [warn]: suppressed same stacktrace
  ```
The ES_HOST is defined in the [run.sh](https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/run.sh#L182):
```shell
es_host=logging-es.${project}.svc.cluster.local
```
If we look inspect /etc/resolv.conf for the fluentd pod:
```shell
[root@logging-fluentd-8-9ukoc /]# cat /etc/resolv.conf
nameserver 172.30.0.1
nameserver 10.0.2.3
search mbaas-logging.svc.cluster.local svc.cluster.local cluster.local feedhenry.io
options ndots:5
```
The original host we were dealing with was ```logging-es.mbaas-logging.svc.cluster.local```. We have 4 dots in that name, so the above _search_ args (in combination with _ndots_) would append ```mbaas-logging.svc.cluster.local``` to the first resolve try (because there are fewer than ndots:5). 
The order would be:  
1. logging-es.mbaas-logging.svc.cluster.local.mbaas-logging.svc.cluster.local
2. logging-es.mbaas-logging.svc.cluster.local.svc.cluster.local
3. logging-es.mbaas-logging.svc.cluster.local.cluster.local
4. ~~logging-es.mbaas-logging.svc.cluster.local.feedhenry.io~~

~~None of the above would be resolved with any on the dns servers.~~
The above was not a correct statement. It turns out that the last entry in the above list could be resolved by the second nameserver (10.0.2.3):
```shell
[vagrant@local ~]$ dig @10.0.2.3 logging-es.mbaas-logging.svc.cluster.local.feedhenry.io

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7 <<>> @10.0.2.3 logging-es.mbaas-logging.svc.cluster.local.feedhenry.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50317
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;logging-es.mbaas-logging.svc.cluster.local.feedhenry.io. IN A

;; ANSWER SECTION:
logging-es.mbaas-logging.svc.cluster.local.feedhenry.io. 6 IN A	192.168.33.12

;; Query time: 606 msec
;; SERVER: 10.0.2.3#53(10.0.2.3)
;; WHEN: Wed Jan 27 08:31:49 UTC 2016
;; MSG SIZE  rcvd: 100
```
We can in fact see this when we use curl:
```shell
curl -s -S -I -k --verbose https://logging-es.mbaas-logging.svc.cluster.local:9200
* About to connect() to logging-es.mbaas-logging.svc.cluster.local port 9200 (#0)
* Trying 192.168.33.12...
* Connection refused
* Failed connect to logging-es.mbaas-logging.svc.cluster.local:9200; Connection refused
* Closing connection 0
curl: (7) Failed connect to logging-es.mbaas-logging.svc.cluster.local:9200; Connection refused
```
Look at this, it is trying to connect to ```192.168.33.12``` and not the kubernetes services cluster ip ```172.30.177.137```.

If we bypass the dns resolution we can infact connect to the internal cluster ip:
```shell
$ curl -s -S -I -k -H "Host: logging-es.mbaas-logging.svc.cluster.local" --resolve logging-es.mbaas-logging.svc.cluster.local:9200:172.30.177.137 --verbose https://logging-es.mbaas-logging.svc.cluster.local:9200

* Added logging-es.mbaas-logging.svc.cluster.local:9200:172.30.177.137 to DNS cache
* About to connect() to logging-es.mbaas-logging.svc.cluster.local port 9200 (#0)
*   Trying 172.30.177.137...
* Connected to logging-es.mbaas-logging.svc.cluster.local (172.30.177.137) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* NSS error -12271 (SSL_ERROR_BAD_CERT_ALERT)
* SSL peer cannot verify your certificate.
* Closing connection 0
curl: (58) NSS: client certificate not found (nickname not specified)
```
If we simply use ```logging-es``` that would append ```.mbaas-logging.svc.cluster.local``` which can be resolved:
```shell
[vagrant@local ~]$  kubectl exec busybox -- nslookup logging-es.mbaas-logging.svc.cluster.local
Server:    172.30.0.1
Address 1: 172.30.0.1 kubernetes.default.svc.cluster.local

Name:      logging-es.mbaas-logging.svc.cluster.local
Address 1: 172.30.177.137 logging-es.mbaas-logging.svc.cluster.local
```
One solution for this would be to not use the full service name, as in ```my-svc.my-namespace.svc.cluster.local```. Since these pods all live in the same namespace/project they can refer to other services in the same namespace project using the simple service name (without the namespace.

As mentioned earlier the value for [ES_HOST](https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/run.sh#L182) is ```logging-es.mbaas-logging.svc.cluster.local``` in our case. This is then used when processing [fluentd.yaml](https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/run.sh#L190). 

We are currently working around this issue by editing the _logging-fluentd_ deployment configuration:
```shell
$ oc edit deploymentconfig logging-fluentd
```
and changing the ```ES_HOST``` value to ```logging-es``` (the [default](https://github.com/openshift/origin-aggregated-logging/blob/master/deployment/templates/fluentd.yaml#L129) value in fluentd.yaml). This works for us and we logs are showing up in Kibana. 

I'm trying to figure out if this is something specific to our environment or if this might also be an issue for others?

**Comment by sosiouxme** [comment]
The error doesn't say it's not resolving the address, it says the connection is refused:

```
error="Can not reach Elasticsearch cluster 
({:host=>\"logging-es.mbaas-logging.svc.cluster.local\", 
:port=>9200, 
:scheme=>\"https\", 
:user=>\"fluentd\",  
:password=>\"obfuscated\"})! 
Connection refused - connect(2) (Errno::ECONNREFUSED)" plugin_id="object:1421250"
```


You'll see this while elasticsearch is still coming up, which can take a while, especially after restarting the cluster or something. I think it is just coincidental that switching the ES_HOST value seemed to help. Both should work. You'll see a different error if there's an actual problem resolving the name (you might test using a bogus name to see).

**Comment by danbev** [comment]
@sosiouxme Thanks for your quick response!

> You'll see this while elasticsearch is still coming up, which can take a while, especially after restarting the cluster or something.

I see, but in our case ElasticSearch has been running for quite some time:
```shell
[vagrant@local ~]$ oc get po
NAME                          READY     STATUS      RESTARTS   AGE
logging-deployer-t0p5j        0/1       Completed   0          1d
logging-es-ip15a3d4-1-7ydf2   1/1       Running     0          1d
logging-fluentd-8-9ukoc       1/1       Running     0          19h
logging-kibana-1-3x4pt        2/2       Running     0          1d
```

> You'll see a different error if there's an actual problem resolving the name (you might test using a bogus name to see).

I gave this a try and updated the deployment config for logging-fluentd:
```shell
[vagrant@local ~]$ oc env dc/logging-fluentd --list
# deploymentconfigs logging-fluentd, container fluentd-elasticsearch
ES_HOST=bogus.mbaas-logging.svc.cluster.local
ES_PORT=9200
```
After scaling up the and following the log I see the same error:
```shell
2016-01-27 02:36:00 -0500 [warn]: temporarily failed to flush the buffer. next_retry=2016-01-27 02:40:10 -0500 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"bogus.mbaas-logging.svc.cluster.local\", :port=>9200, :scheme=>\"https\", :user=>\"fluentd\", :password=>\"obfuscated\"})! Connection refused - connect(2) (Errno::ECONNREFUSED)" plugin_id="object:1369d58"
  2016-01-27 02:36:00 -0500 [warn]: suppressed same stacktrace
```
While writing this comment I've found an issue with the issue description above and I've updated (see the striked through text for the incorrect parts of it). 

Thanks!

**Comment by ewolinetz** [comment]
@sosiouxme is there a reason that we would use the full service path vs just the service name? Not sure if there's a standard/best practice defined that I'm unaware of

**Comment by sosiouxme** [comment]
> @sosiouxme <https://github.com/sosiouxme> is there a reason that we would
> use the full service path vs just the service name? Not sure if there's a
> standard/best practice defined that I'm unaware of
>

This is probably a holdover from when I was thinking we would be using
static pods which would be in the default project. I can't think of a real
reason today, other than it makes  cut and paste easier for debugging.

**Comment by ewolinetz** [comment]
@danbev the solution may be that we drop the full service path from the template and beef up our documentation or point to docs regarding determining the full service path.

Just to confirm, simply using the service name within your fluentd config works with your given deployment?

**Comment by danbev** [comment]
> Just to confirm, simply using the service name within your fluentd config works with your given deployment?

This is working well for us. We currently edit both ``` ES_HOST``` and ```OPS_HOST``` and we have not hit any issues.
