### ISSUE TITLE
enabling secure-forward  on release-1.5 causes 'project not found' error in kibana

### ISSUE THREAD

**Issue by stephenrlouie** [openshift/origin-aggregated-logging#552]
I'm using release-1.5 via `openshift-ansible/playbook/byo/openshit-cluster/openshift-logging.yaml`. I have modified the [secure forward file](https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_logging/files/secure-forward.conf) to insecurely forward its logs to a fluentd aggregator I've set up.

I run the ansible playbook to install EFK with my modified forward file and have seen logs reach my aggregator. The issue is the host that has the forwarding on, no longer has projects show up in kibana. I  see `project..empty-project.*` with no logs making it to Kibana. It also displays some errors saying 
> `project.<my_project_name>.<HASH>` is not a configured pattern. User default pattern.....

My understanding was updating the secure_forward file would be independent and not effect what is specified in the `output-es-config`. Any help would be great, I'll continue to poke around.

**Comment by richm** [comment]
oc exec $fluentd_pod -- cat /etc/fluent/fluent.conf
oc exec $fluentd_pod -- ls -alrtF /etc/fluent/configs.d/openshift
oc exec $fluentd_pod -- ls -alrtF /etc/fluent/configs.d/user
oc exec $fluentd_pod -- cat /etc/fluent/configs.d/user/secure_forward.conf

**Comment by nhosoi** [comment]
How about logs from the fluentd and elesticsearch pod?
oc logs $fluentd_pod
oc logs $elasticsearch_pod

**Comment by jcantrill** [comment]
closing without prejudice
