### ISSUE TITLE
No adequate docs for supporting standalone ELK

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin-aggregated-logging#563]
https://github.com/openshift/origin-aggregated-logging/issues/100 is not covering the theme. The role is monstrously huge, most of us already have ELK installed and ready. Most of us don't use SSL for ELK.

Can you please add options to your playbook to setup only fluentd and prepare cluster for it, or at least write some documentation with manual steps for this? This playbook is not well documented, so I'm not able to do this on my own (no idea what includes I should leave for external ELK).

Please advice

**Comment by jcantrill** [comment]
Captured in trello https://trello.com/c/iIvuCJ9W/.

**Comment by jcantrill** [comment]
@ksemaev Can you define your usecase more in depth so we may better understand how you desired to use the Openshift fluentd image? 

What are your scaling and throughput expectations?

> Most of us don't use SSL for ELK.

Who is 'us' and what do you require?

**Comment by ksemaev** [comment]
@jcantrill Us - are people who are already have wide working environment, and are trying to implement openshift as a replacement for some of used infrastructure. IT teams already have a working ELK (or other) soliutions to monitor all of their services, so all we need is to get logs from new server instance (openshift) to our existing log aggregating system, not implementing the second containerized ELK solution.
For example, I managed to get logs from Openshift to current ELK using docker log driver "json-file" and filebeat, but would love to change it to journalctl and fluentd.  And all options that I have is to read all your giant role.
Maybe after you made such an amasing job making this origin-aggregated-logging solution - you can provide steps for setting up the logging to external ELK (as I see the link https://docs.openshift.org/latest/install_config/aggregate_logging.html#sending-logs-to-an-external-elasticsearch-instance helps to change log destination for fluentd, but there is no way to install only fluentd from the role)?

**Comment by jcantrill** [comment]
@ksemaev As of the 3.6 release, the openshift_logging role was refactored to split into component roles which will facilitate deploying fluentd only via the openshift_logging_{fluentd,mux} roles.  A card was added to our backlog and proposed for 3.8.  It is subject to prioritization by our PMs.
