### ISSUE TITLE
Fluentd Kafka Plugin to be included 

### ISSUE THREAD

**Issue by sayeedch** [openshift/origin-aggregated-logging#603]
Can the existing fluentd image include the kafka plugin to avoid having to secure forward logs to a separate fluentd deployment? This will require the ruby version to be updated from 2.0 to 2.1 or above.

**Comment by jcantrill** [comment]
You are welcome to build on top of the officially provided image.  We are unlikely to bundle any plugins with fluentd for which we are not prepared to support.  A kafka deployment model is not part of our current roadmap and adding the plugin introduces additional risk.  You are welcome to add a card to our Trello board https://trello.com/b/oJbshSIs/integration-services or add an RFE request to this repo.

**Comment by jcantrill** [comment]
Feature targeted for future logforwarding features
