### ISSUE TITLE
openshift_logging_es_ops_memory_limit upgrade to 3.6 is not honored.

### ISSUE THREAD

**Issue by jantzen05** [openshift/origin-aggregated-logging#605]
Hi

During upgrade from 1.5.1 to 3.6 setting openshift_logging_es_ops_memory_limit is not honored and instead openshift_logging_es_memory_limit is used for memory setting for the ops cluster.

In my inventory file I have 

openshift_logging_es_memory_limit="12G"
openshift_logging_es_ops_memory_limit="8G"

When I describe the ops pod I see:
INSTANCE_RAM: 12G

**Comment by jcantrill** [comment]
@ewolinetz Can you investigate this issue?

**Comment by richm** [comment]
probably should be moved to openshift-ansible

**Comment by ewolinetz** [comment]
don't worry about moving it, I'm looking into it now and i'll link back to this issue in my PR
