### ISSUE TITLE
Unable to deploy Kopf

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#607]
Unable to deploy because cant seem to build.  Tried on a cluster deployed using logging master
```
# oc logs -f logging-es-kopf-2-build
error: build error: stat /tmp/build/inputs/_site: no such file or directory
```

**Comment by josefkarasek** [comment]
I'm guessing that openshift version is 3.6 or master. There are known problems with older versions of openshift because of several features introduced in 3.6.
This looks like a change in the upstream repo. Will check as I get to my laptop tomorrow.

**Comment by StLuke** [comment]
I was able to reproduce this issue on openshift-ansible-3.6.173.0.83-1.git.0.84c5eff.el7.noarch
do we have any WA, fix?

**Comment by jcantrill** [comment]
@josefkarasek please take a look

**Comment by josefkarasek** [comment]
All we do is copy `_site` dir from github[0][1] into httpd docker image. I could not reproduce.

I assume that `stat /tmp/build/inputs/_site: no such file or directory` means that the pull failed. Does the build succeed in any subsequent try? 

[0] https://github.com/lmenezes/elasticsearch-kopf/tree/v2.1.2
[1] https://github.com/openshift/origin-aggregated-logging/blob/master/hack/kopf/logging-es-kopf-template.yaml#L652-L655

**Comment by himmatb** [comment]
Hi @josefkarasek 

I have used above mentioned image/template and deployed successfully kopf but getting below error 
but while creating kopf pod : 

/bin/bash: /opt/app-root/scripts/run-kopf.sh: Permission denied

Please help me where to change to make it work.

Thanks in advance.

**Comment by himmatb** [comment]
now i am getting below error : 

sed: couldn't open temporary file /etc/httpd/conf/sed2JcvyS: Read-only file system

Can anyone have clue why i am getting this error. 

do we not have stable openshift kopf available ?

**Comment by jcantrill** [comment]
Closing as Kopf was never a supported feature of Logging
