### ISSUE TITLE
CentOS-based fluentd container won't build, public_suffix requires Ruby version >= 2.1

### ISSUE THREAD

**Issue by t0ffel** [openshift/origin-aggregated-logging#610]
Currently when trying to build you get an error:

```
Successfully installed fluentd-0.12.39
Successfully installed excon-0.58.0
Successfully installed fluent-plugin-elasticsearch-1.9.5
Successfully installed lru_redux-1.1.0
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
       	public_suffix requires Ruby version >= 2.1.
Successfully installed unf_ext-0.0.7.4
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20170404
Successfully installed http-cookie-1.0.3
Successfully installed mime-types-data-3.2016.0521
```
looks like `public_suffix` v 3.0.0 was release in August and that causes the problem. If I explicitly specify `public_suffix:<3.0.0`, the image builds successfully.

Also `hack/build-images.sh` seem to fail silently during the CI, that's why we didn't learn about build failure right away - CI was probably grabbing the fluentd image from the repo, rather than locally.

**Comment by jcantrill** [comment]
It could be, but using the hack/build-images.sh to build upstream requires you to pass in the production stream to ensure you are getting origin images.  What command did you use to build the images?

**Comment by adrianlzt** [comment]
I'm hitting the same error and doing the workaround of forcing ``public_suffix`` version.
Could this change added to the repo?

**Comment by richm** [comment]
Fixed in current versions
