### ISSUE TITLE
Issues with syslog character encoding in fluentd

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#621]
As context, instead of using the built-in Elasticsearch instance, I'm pushing messages to a RabbitMQ instance and having something else pick them up. This involves a conversion to JSON. Unfortunately, fluentd's `in_tail` plugin will, by default, [force the encoding of messages it reads to `ASCII-8BIT`][ASCII-8BIT]. This is mostly fine, except that the origin-node service occasionally logs messages like this:
```
Aug 29 17:19:10 ip-192-168-32-82 origin-node: I0829 17:19:10.500708   14033 docker_manager.go:1373] Container "e8a6b32b1e4d101ff6fd7950de8eb425e16253005cf53924b9d3480c1b972e2a dev/config-1-deploy" exited after 883.317µs
```
`µ` is encoding in UTF-8 as the two-byte sequence `0xC2B5`. When fluentd attempts to convert a record containing this character to JSON, it fails with the following error:
```
Encoding::UndefinedConversionError: "\xC2" from ASCII-8BIT to UTF-8
```
While this is surfacing due to my nonstandard use of the container, it's possible that it might surface in sanctioned use later. Additionally, since we're logging UTF-8 into syslog (and, as a side note, containers might be as well), we should probably have fluentd treat these files as UTF-8.

The good news is that this is pretty easy to fix. By setting `encoding` to `UTF-8` in the various `in_tail` configuration sections, fluentd will treat the files as `UTF-8`, and the problem goes away entirely.

[ASCII-8BIT]: https://docs.fluentd.org/v0.12/articles/in_tail#encoding-fromencoding

**Comment by elyscape** [comment]
On further investigation, it looks like the journald input plugin doesn't force things to UTF-8 either. From an IRB session using the underlying library:
```
irb(main):028:0> puts j.current_entry.message
[1.02304307s] [8.72µs] Self-link added
=> nil
irb(main):029:0> j.current_entry.message
=> "[1.02304307s] [8.72\xC2\xB5s] Self-link added"
irb(main):030:0> j.current_entry.message.encoding
=> #<Encoding:ASCII-8BIT>
```
So we should probably use a filter instead of setting the `encoding` field on the `in_tail` inputs.

**Comment by richm** [comment]
should also see how it works with the latest logging which uses file buffering - we had a problem with the string -> msgpack -> file buffer.
