### ISSUE TITLE
Improve ES volume documentation

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#65]
It's become clear the official docs for dealing with ES volumes are inadequate. A discussion of how multiple instances attach separate volumes and the tradeoffs of hostmount vs NAS is in order.

**Comment by ewolinetz** [comment]
@sosiouxme does https://github.com/openshift/openshift-docs/pull/1844 satisfy this card?

**Comment by sosiouxme** [comment]
I think this is still relevant. Surely I can do better than:

> Elasticsearch replicas require their own storage, but an OpenShift Origin deployment configuration shares storage volumes between all its pods. So, when scaled up, the EFK deployer ensures each replica of Elasticsearch has its own deployment configuration.

We're now saying NAS is not supported, but block storage still works, and it's worth saying that it works but would not be as fast as local storage.

**Comment by jcantrill** [comment]
closing without prejudice
