### ISSUE TITLE
Question - possible to share kibana dashboard ?

### ISSUE THREAD

**Issue by Kapaski** [openshift/origin-aggregated-logging#656]
Hi there, 
In general, we have the standard installation of EFK stacks that comes with Openshift, and also have multiple users that can access to a project index in Elasticsearch through Kibana.
The issue is once user A created a dashboard against that index and saved, user B with the same access to the index can't actually see that dashboard. 

Could anyone point me to the right direction or documentations about how to make it happen?

Thanks in advance!

James

**Comment by jcantrill** [comment]
This is a complicated question.  The short answer given the bits you are most likely using is no.  There are a number of changes that have landed or will be landing in the near future that might address your needs:

* Recent addition to configure the ES plugin to allow `shared_ops` mode.  This allows users who are cluster-admin's to share the same Kibana index and thus dashboards.  Your brief description leads me to believe this does not resolve your needs.
* This change https://github.com/openshift/origin-aggregated-logging/pull/571 will allow you to export UI objects and you could import them back. 
* This change https://github.com/fabric8io/openshift-elasticsearch-plugin/commit/5f1f75569bdeb773cbafa0ccac4e331e6be9a452 which has not been released will allow non ops users to share an index, but it remains more of a 'global' type setting.  There is no functionality to say "users in group X can share kibana index Y"

**Comment by Kapaski** [comment]
Thanks @jcantrill appreciate the answer, will close the issue
