### ISSUE TITLE
Secure forward output plugins should use "buffer_queue_full_action" setting of "block"

### ISSUE THREAD

**Issue by portante** [openshift/origin-aggregated-logging#712]
We should consider changing the `buffer_queue_full_action` for the secure forward output plugins to use `block` instead of `exception`, like we do for Elasticsearch output plugins.

**Comment by jcantrill** [comment]
@portante is this still relevent for our LogForwarding feature?  What are the ramifications of the switch?

**Comment by portante** [comment]
@jcantrill, yes, I think it is still relevant. By using `exception` instead of `block`, logs will be lost when the log forward method fails for whatever reason.

But we really want the behavior in https://github.com/containers/conmon/issues/84 along with these kinds of changes to give the admins the ability to balance the behavior.

**Comment by jcantrill** [comment]
Closing as this is fixed in later releases.
