### ISSUE TITLE
Rename logging project to openshift-logging or merge into openshift-infra

### ISSUE THREAD

**Issue by portante** [openshift/origin-aggregated-logging#720]
There is a PR coming to exempt all projects prefixed with `openshift-` from having cluster-wide over-commit resource limits applied.  See https://github.com/openshift/origin/pull/16845.

If we rename the `logging` project to `openshift-logging`, we can drop the quota annotation we need to avoid the over-commit limits.

**Comment by jcantrill** [comment]
done as part of 3.9
