### ISSUE TITLE
Sending logs ONLY to an external elasticsearch instance

### ISSUE THREAD

**Issue by ksemaev** [openshift/origin-aggregated-logging#721]
As are followup question for https://github.com/openshift/origin-aggregated-logging/issues/563 and the explanation for https://docs.openshift.com/container-platform/3.3/install_config/aggregate_logging.html#sending-logs-to-an-external-elasticsearch-instance please tell:

Is there a way to use this role to install only fluentd to send Logs to an External Elasticsearch Instance? Or maybe there are some sequence of playbooks that setup cluster for external logging and installs fluentd for this?

Seems like now the only option is to install whole EFK to Openshift, and then change dc/fluentd to make it send logs to another instance. Please tell me if I got this wrong)

**Comment by jcantrill** [comment]
As stated in https://github.com/openshift/origin-aggregated-logging/issues/563#issuecomment-336473793  the roles have been broken up but a playbook is yet to exist to deploy only fluentd.  This would be proposed work as part of our backlog which would include documentation.  Feel free to submit a PR for a playbook if you have something tfrom which hat the rest of the community could benefit

**Comment by ksemaev** [comment]
@jcantrill I tried to dive into role, but it is way too complicated for the person, who didn't participate in the creation of it in first place. But I surely would like to contribute in it, please tell me who can guide me through some questions regarding it?

**Comment by richm** [comment]
@ksemaev on freenode irc, use `#openshift-dev` - on email, use dev@lists.openshift.redhat.com
preface any emails/comments with [logging] so that the logging developers will pay attention

**Comment by jcantrill** [comment]
This is made easier with the introduction of LogForwarding.  Closing issues.
