### ISSUE TITLE
Create index-mappings for  cluster admins to '.all' and '.operations' only

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#764]
We currently create index-mappings for the alias '.all' and the '.operations' index and every other project indices.  Since '.all' should reference every 'project.PROJECTNAME.*' index, there is no reason to create additional index mappings.  In clusters with may indices, this will make the discovery drop list really, really long for no benefit.

cc @openshift/team-integration-services

**Comment by jcantrill** [comment]
cc @ewolinetz @tkatarki

**Comment by ewolinetz** [comment]
+1
I thought we were going to create an all alias for each user though since we would want to limit by what the user has access to (both the indices referenced by the alias and permissions)

**Comment by jcantrill** [comment]
In one recent version of the plugin there was a user 'all' index but i removed it.  My logic is you can create a query to match the pattern of project.* which should search across your available indices.  To be frank though, I don't know if we have tested that to see what kind of result you get.
