### ISSUE TITLE
[warn]: rewrite_tag_filter: [DEPRECATED] Use <rule> section instead of rewriterule1

### ISSUE THREAD

**Issue by nhosoi** [openshift/origin-aggregated-logging#769]
Even though Dockerfile.centos7 sets up the correct version for fluent-plugin-rewrite-tag-filter as follows
` 'fluent-plugin-rewrite-tag-filter:<2.0.0' \`
I started getting the warning If I test the master branch.
` [warn]: rewrite_tag_filter: [DEPRECATED] Use <rule> section instead of rewriterule1`

This diff cleans up the warnings.
https://github.com/openshift/origin-aggregated-logging/compare/master...nhosoi:rewrite_tag_filter
But according to the fluent-plugin-rewrite-tag-filter README, the change is required for fluentd >= v0.14.2.
https://github.com/fluent/fluent-plugin-rewrite-tag-filter

Are we migrating to Fluentd v0.14.x?  Or is this accidental?

**Comment by richm** [comment]
We are not migrating yet to fluent 0.14
I'm not sure why we are getting the warning, but the code seems to work
Is it possible that there is a new version of rewrite_tag_filter 1.x.y _and_ a new 2.0.0 version, which both have the `<rule>` feature?

**Comment by nhosoi** [comment]
@richm, yes, that was it!
```
Date:   Mon Nov 6 09:52:13 2017 +0900
    Release v1.6.0
```
And v1.6.0 code has the warning:
` log.warn "rewrite_tag_filter: [DEPRECATED] Use <rule> section instead of #{k}"`
Now, should we switch to <rule> now or wait for the downstream to catch up?

**Comment by josefkarasek** [comment]
Did not find any useful info what's in 1.6 release. Please let me know if you find something.
In the meantime I'm in favor for locking to 1.5

**Comment by jcantrill** [comment]
@richm Can we close this because of #773

**Comment by richm** [comment]
closed - fixed by https://github.com/openshift/origin-aggregated-logging/pull/773
