### ISSUE TITLE
[Build] fluentd docker build fail 

### ISSUE THREAD

**Issue by JooyoungJeong** [openshift/origin-aggregated-logging#775]
[ec2-user@ipfluentd]$ git branch -v
* (detached from v3.6.0) c2f32fb Merge pull request #546 from richm/release-3.6-mux-client-no-k8s

[ec2-user@ fluentd]$ pwd
/home/ec2-user/work/origin-aggregated-logging/fluentd

[ec2-user@ fluentd]$ sudo docker build -f Dockerfile.centos7 --tag xxxxtest/test_test:v11234 .        
Sending build context to Docker daemon  79.87kB
Step 1/12 : FROM centos:centos7
 ---> d123f4e55e12
Step 2/12 : MAINTAINER OpenShift Development <dev@lists.openshift.redhat.com>
 ---> Using cache
 ---> 214704d023b8
Step 3/12 : ENV DATA_VERSION 1.6.0 FLUENTD_VERSION 0.12.37 GEM_HOME /opt/app-root/src HOME /opt/app-root/src PATH /opt/app-root/src/bin:/opt/app-root/bin:$PATH RUBY_VERSION 2.0
 ---> Using cache
 ---> ec637c1b5b69
Step 4/12 : LABEL io.k8s.description "Fluentd container for collecting of docker container logs" io.k8s.display-name "Fluentd ${FLUENTD_VERSION}" io.openshift.expose-services "9200:http, 9300:http" io.openshift.tags "logging,elk,fluentd"
 ---> Using cache
 ---> 6efb4971b8c6
Step 5/12 : RUN rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 &&     yum install -y --setopt=tsflags=nodocs       gcc-c++       ruby       ruby-devel       libcurl-devel       make       bc       iproute &&     yum clean all
 ---> Using cache
 ---> 51eb5eb7d314
Step 6/12 : RUN mkdir -p ${HOME} &&     gem install -N --conservative --minimal-deps --no-ri      'activesupport:<5'      'elasticsearch-transport:<5'      'elasticsearch-api:<5'      'elasticsearch:<5'       fluentd:${FLUENTD_VERSION}      'fluent-plugin-elasticsearch:>1.9.2'       fluent-plugin-kubernetes_metadata_filter       fluent-plugin-rewrite-tag-filter       fluent-plugin-secure-forward      'fluent-plugin-systemd:<0.1.0'       fluent-plugin-viaq_data_model       systemd-journal
 ---> Running in e6d348c0756b
Successfully installed concurrent-ruby-1.0.5
Successfully installed i18n-0.9.1
Successfully installed thread_safe-0.3.6
Successfully installed tzinfo-1.2.4
Successfully installed minitest-5.10.3
Successfully installed activesupport-4.2.10
Successfully installed multi_json-1.12.2
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.13.1
Successfully installed elasticsearch-transport-2.0.2
Successfully installed elasticsearch-api-2.0.2
Successfully installed elasticsearch-2.0.2
Building native extensions.  This could take a while...
Successfully installed msgpack-1.1.0
Building native extensions.  This could take a while...
Successfully installed yajl-ruby-1.3.1
Building native extensions.  This could take a while...
Successfully installed cool.io-1.5.1
Building native extensions.  This could take a while...
Successfully installed http_parser.rb-0.6.0
Successfully installed sigdump-0.2.4
Successfully installed tzinfo-data-1.2017.3
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
        serverengine requires Ruby version >= 2.1.0.
Successfully installed string-scrub-0.0.5
Successfully installed fluentd-0.12.37
Successfully installed lru_redux-1.1.0
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
        public_suffix requires Ruby version >= 2.1.
ERROR:  Error installing fluent-plugin-rewrite-tag-filter:
        serverengine requires Ruby version >= 2.1.0.
Successfully installed unf_ext-0.0.7.4
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20170404
Successfully installed http-cookie-1.0.3
Successfully installed mime-types-data-3.2016.0521
Successfully installed mime-types-3.1
Successfully installed netrc-0.11.0
Successfully installed rest-client-2.0.2
Successfully installed recursive-open-struct-1.0.0
Successfully installed http-form_data-1.0.3
Successfully installed resolve-hostname-0.1.0
Successfully installed proxifier-1.0.3
Successfully installed fluent-plugin-secure-forward-0.4.5
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.18
Successfully installed systemd-journal-1.3.1
Successfully installed fluent-plugin-systemd-0.0.8
Successfully installed fluent-plugin-viaq_data_model-0.0.11
27 gems installed
The command '/bin/sh -c mkdir -p ${HOME} &&     gem install -N --conservative --minimal-deps --no-ri      'activesupport:<5'      'elasticsearch-transport:<5'      'elasticsearch-api:<5'      'elasticsearch:<5'       fluentd:${FLUENTD_VERSION}      'fluent-plugin-elasticsearch:>1.9.2'       fluent-plugin-kubernetes_metadata_filter       fluent-plugin-rewrite-tag-filter       fluent-plugin-secure-forward      'fluent-plugin-systemd:<0.1.0'       fluent-plugin-viaq_data_model       systemd-journal' returned a non-zero code: 1

**Comment by richm** [comment]
you need to use https://github.com/openshift/origin-aggregated-logging/commit/d83f55c22926bc4a6488444198c68c9815dec4f9 for master branch or

https://github.com/openshift/origin-aggregated-logging/commit/d365512b8072921cd936f20d86668640e808acb8 for release-3.6 branch
