### ISSUE TITLE
Install fails with Command not found error Urgent

### ISSUE THREAD

**Issue by helletheone** [openshift/origin-aggregated-logging#839]
Hey, i want to activat the logging on our cluster. But i get this error:

Openshift Origin version 3.6: 
OS: Centos 7
Setup: Multi-Master Setup( 1 LB Native & 3 Masters & 3 Worker Nodes) :

TASK [openshift_logging : Run JKS generation script] ***********************************************************************************************************************************************************************
fatal: [master1.example.de -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "non-zero return code", "rc": 127, "stderr": "+ '[' 2 -lt 1 ']'\n+ dir=/tmp/openshift-logging-ansible-HYILj0\n+ SCRATCH_DIR=/tmp/openshift-logging-ansible-HYILj0\n+ PROJECT=logging\n+ [[ ! -f /tmp/openshift-logging-ansible-HYILj0/system.admin.jks ]]\n+ generate_JKS_client_cert system.admin\n+ NODE_NAME=system.admin\n+ ks_pass=kspass\n+ ts_pass=tspass\n+ dir=/tmp/openshift-logging-ansible-HYILj0\n+ echo Generating keystore and certificate for node system.admin\n+ keytool -genkey -alias system.admin -keystore /tmp/openshift-logging-ansible-HYILj0/system.admin.jks -keyalg RSA -keysize 2048 -validity 712 -keypass kspass -storepass kspass -dname 'CN=system.admin, OU=OpenShift, O=Logging'\n/root/.ansible/tmp/ansible-tmp-1513010720.0-52542015687757/generate-jks.sh: line 89: keytool: command not found\n", "stdout": "Generating keystore and certificate for node system.admin\n", "stdout_lines": ["Generating keystore and certificate for node system.admin"]}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.retry

What can i do?

**Comment by richm** [comment]
@helletheone 
Are you using openshift-ansible packages from rpm?  If so, `rpm -qa|grep openshift`
If not, what openshift-ansible git branch are you using?  `git describe --tags`
Do you have the `java-1.8.0-openjdk-headless` package installed?  This package provides the `keytool` command

**Comment by helletheone** [comment]
Yes we use the RPM-Install-version. But with rpm -qa|grep openshift
comes nothing 

only with : openshift-cluster]# rpm -qa | grep origin
i got this: 
origin-excluder-3.6.1-1.0.008f2d5.noarch
origin-master-3.6.1-1.0.008f2d5.x86_64
origin-sdn-ovs-3.6.1-1.0.008f2d5.x86_64
origin-docker-excluder-3.6.1-1.0.008f2d5.noarch
origin-3.6.1-1.0.008f2d5.x86_64
origin-clients-3.6.1-1.0.008f2d5.x86_64
origin-node-3.6.1-1.0.008f2d5.x86_64
tuned-profiles-origin-node-3.6.1-1.0.008f2d5.x86_64




The branch is: openshift-ansible-3.6.173.0.78-1-2-g9cd90eb

and no java is not installed

**Comment by jcantrill** [comment]
@helletheone please reopen this issue against https://github.com/openshift/openshift-ansible.
