### ISSUE TITLE
ImagePullBackOff while deploying EFK

### ISSUE THREAD

**Issue by Yashu5** [openshift/origin-aggregated-logging#84]
Hi, I am following readme to deploy EFK in origin 1.1.0.1. But It always fails with ImagePullBackOff status of pods. In events I could see below:

![image](https://cloud.githubusercontent.com/assets/1378542/13603431/36e3432c-e563-11e5-862b-f4037d94c8d1.png)

I tried pulling image on my machine using "docker pull <imagename>" , which pulls image without any issue. Could anyone help me with this? 

Note: I am able to create apps from other docker images + metrics setup is also working fine.

Thanks,
Yash

**Comment by richm** [comment]
Can you provide the output of:
oc describe pod logging-es-steancmv-1-fwqt9
oc logs logging-es-steancmv-1-fwqt9
oc get pods

**Comment by Yashu5** [comment]
HIi @richm , thanks for response here , It is able to pull images now, I think there was a space issue, I just cleaned up my environment and started a fresh logging setup, seems to be working fine.
