### ISSUE TITLE
Sometime can't get log in kibana

### ISSUE THREAD

**Issue by mdshuai** [openshift/origin-aggregated-logging#87]
If node time zone is inconsistent with container time zone, is this can affect logging function ?

**Comment by jcantrill** [comment]
@mdshuai Can you provide more details of what you are suggesting here.

**Comment by richm** [comment]
@mdshuai Your nodes and your containers should all be configured to use timezone GMT

**Comment by ewolinetz** [comment]
As of https://github.com/openshift/origin-aggregated-logging/pull/170 this should be resolved.

@mdshuai can you please verify this?

**Comment by richm** [comment]
closing - please open a new issue if there is still a problem
