### ISSUE TITLE
failed to verify certification when using mux

### ISSUE THREAD

**Issue by zhanglianx111** [openshift/origin-aggregated-logging#873]
openshift version:oc v3.6.1+008f2d5
I want the logs out of openshift cluster into openshift and i use the docs of mux-logging-service.md.
But i get "failed to verify certification while connecting ssl session host="xxx.xxx.com" hostlabel=xxx.xxx.com"".
Who can help me? thanks!

**Comment by himmatb** [comment]
+1 Same issue for me ..
Anyone please help us on this issue..

**Comment by himmatb** [comment]
@zhanglianx111 Did you get any solution for this , if yes please share me fixes and steps..

**Comment by richm** [comment]
Can you provide
- the exact parameters you specified to ansible when configuring mux
- the exact configuration of the external fluentd you are using to try to send logs to mux
please remove or obscure any passwords or external hostnames/ip addresses

**Comment by himmatb** [comment]
@richm  I am trying to ingest logs from outside the cluster(from VM) into internal openshift cluster elasticsearch.
I have followed docs of mux-logging-service.md to make mux configuration.

1. Below configuration i am using in ansible for mux:

# mux - secure_forward listener service
openshift_logging_mux_allow_external=true
openshift_logging_use_mux=true
openshift_logging_mux_hostname=XXXXX.XXXX.com
openshift_logging_use_mux_client=true
openshift_logging_mux_client_mode=maximal
openshift_logging_mux_namespaces=["externalvmlogs"]
# mux tuning parameters
#openshift_logging_mux_file_buffer_limit=2Gi
openshift_logging_mux_cpu_limit=500m
openshift_logging_mux_memory_limit=2Gi
#openshift_logging_mux_buffer_queue_limit=1024
openshift_logging_mux_port=24284
#openshift_logging_mux_buffer_size_limit: 16m
#openshift_logging_mux_replicas: 1
--------------------------------------------------------------
2. Obtained mux CA cert and shared_key using below command : 
 1. oc get secret logging-mux --template='{{index .data "ca"}}' | base64 -d > mux-ca.crt
 2. oc get secret logging-mux --template='{{index .data "shared_key"}}' | \
  base64 -d > mux-shared-key

-------------------------------------------------------------
3. External fluentd client conf:
# Log Forwarding
<match *.*>
  @type secure_forward
  self_hostname fluentd-agent-vm
  shared_key XXXXXXXXXXXXXXX
  secure yes
  enable_strict_verification yes
  ca_cert_path /root/mux/mux-ca.crt
  #ca_private_key_path /root/mux/mux.key
  #ca_private_key_passpharse ocpsecureforward
  <server>
    host XXXX.XXXX.com
    port 24284
  </server>

  # use longer flush_interval to reduce CPU usage.
  # note that this is a trade-off against latency.
  <buffer>
    flush_interval 60s
  </buffer>
</match>
-------------------------------------------------------------------------------
4. logging-mux service configuration is below :
Services:  logging-mux
Selectors:
component=mux, provider=openshift
Type: ClusterIP 
IP:172.xx.xx.5
Hostname: logging-mux.logging.svc 
Session affinity: None
External IPs:192.xxx.xx.158 
------------------------------------------------------------------------------
Output:
2018-02-28 20:10:30 +0000 [info]: starting fluentd-1.1.0 pid=22697 ruby="2.2.4"
2018-02-28 20:10:30 +0000 [info]: spawn command to main:  cmdline=["/usr/local/rvm/rubies/ruby-2.2.4/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/local/rvm/gems/ru
by-2.2.4/bin/fluentd", "-c", "fluentd.conf", "--under-supervisor"]
2018-02-28 20:10:31 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.6.0'
2018-02-28 20:10:31 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.5.0'
2018-02-28 20:10:31 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2018-02-28 20:10:31 +0000 [info]: gem 'fluentd' version '1.1.0'
2018-02-28 20:10:31 +0000 [info]: adding match pattern="*.**" type="secure_forward"
2018-02-28 20:10:31 +0000 [info]: adding source type="tail"
2018-02-28 20:10:31 +0000 [info]: #0 starting fluentd worker pid=22701 ppid=22697 worker=0
2018-02-28 20:10:31 +0000 [info]: #0 following tail of /var/log/httpd/access_log
2018-02-28 20:10:31 +0000 [info]: #0 fluentd worker is now running worker=0
2018-02-28 20:10:31 +0000 [warn]: #0 failed to verify certification while connecting ssl session host="XXXX.XXXX.com" hostlabel="XXXX.XXXX.com"
2018-02-28 20:10:36 +0000 [warn]: #0 dead connection found: XXXX.XXXX.com, reconnecting...
2018-02-28 20:10:36 +0000 [warn]: #0 failed to verify certification while connecting ssl session host="XXXX.XXXX.com.com" hostlabel="XXXX.XXXX.com"

-------------------------------------------
Let me know any other details require.

**Comment by richm** [comment]
I don't know what the problem is.
```
failed to verify certification while connecting ssl session host="XXXX.XXXX.com" hostlabel="XXXX.XXXX.com"
```
This looks like some sort of DNS or SSL problem.

you may find this helpful: https://github.com/ViaQ/Main/blob/master/README-install_with_mux.md#post-install-checking

**Comment by himmatb** [comment]
Hi Richm,

We tried to run below command but throwing below Error, Kindly assist.
 echo hello | openssl s_client -quiet -connect localhost:24284

[root@console ~]# echo hello | openssl s_client -quiet -connect localhost:24284
socket: Bad file descriptor
connect:errno=9

Thanks

**Comment by himmatb** [comment]
Need your urgent support to fix this connectivity issue.

Thanks

**Comment by richm** [comment]
@nhosoi is this the same issue that you recently worked on around mux certs?
