### ISSUE TITLE
can not install efk 3.7

### ISSUE THREAD

**Issue by RainF930125** [openshift/origin-aggregated-logging#886]
I got an error like this when I try to install efk with command:ansible-playbook -i ${my_inventory_file} -vv openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml 
<img width="1442" alt="efk_deploy_failed_3 7" src="https://user-images.githubusercontent.com/24642919/34666961-d0132388-f4a1-11e7-8b03-0f9a50563504.png">

thanks for your help

**Comment by jcantrill** [comment]
- What version of openshift-ansible are you using?
- How are you running openshift-ansible (e.g. source, rpms, container)

**Comment by RainF930125** [comment]
@jcantrill Thanks for your response.
Openshift-ansible's version is release-3.7,I install openshift-origin 3.7 is successful with rpms.But it's not install EFK automatically.So, I manual deploy EFK with the above mentioned command.
I just want to call the APIs from es. I found a var like 'openshift_logging_es_allow_external=true' in efk 3.7 documents.So what can I do to fix this question?

**Comment by jcantrill** [comment]
@ewolinetz Any thoughts here? Does he need to get a later version of 3.7. Maybe its associated with changes related to upgrade

**Comment by ewolinetz** [comment]
@RainF930125 that error should be resolved now with the latest 3.7 release. 
I believe you are seeing the same as here: https://github.com/openshift/openshift-ansible/issues/6740

**Comment by RainF930125** [comment]
@ewolinetz I got an new error. like the image below.
![image](https://user-images.githubusercontent.com/24642919/35849437-862914e0-0b5c-11e8-8211-114e090bf9d0.png)

**Comment by jcantrill** [comment]
@ewolinetz is it possible the v3.7 tag is not updated or possibly this requires a different version of ansible?

**Comment by ewolinetz** [comment]
@RainF930125 What version of ansible are you using? `ansible --version`

**Comment by RainF930125** [comment]
@ewolinetz 
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

**Comment by ewolinetz** [comment]
Can you try downgrading to 2.3 or bumping up to 2.4.3?
For release v3.7 we support 2.3, v3.9 will support 2.4 I believe

**Comment by RainF930125** [comment]
@ewolinetz  My deployment was successful with ansible v2.4.2 and openshift-ansible release-3.7.
But now, I want to access elasticsearch API from outside.I follow the guide with `

$ curl -k -H "Authorization: Bearer $token" -H "X-Proxy-Remote-User: $(oc whoami)" -H "X-Forwarded-For: 127.0.0.1" https://es.example.test/_cat/indices

`
and provide every var, but return below respose when I access /_cat/indices
`{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "no permissions for cluster:monitor/state"
            }
        ],
        "type": "security_exception",
        "reason": "no permissions for cluster:monitor/state"
    },
    "status": 403
}`

I can access '/_cat/health'.

I used ldap authentication.

**Comment by richm** [comment]
@RainF930125 That's a different issue.  Please open a new issue.  Closing this issue.
