### ISSUE TITLE
curator starts before elasticsearch during deploy

### ISSUE THREAD

**Issue by richm** [openshift/origin-aggregated-logging#90]
The curator pod starts before the elasticsearch pod during deploy.  This causes errors like this in the curator logs::

    logging-curator running [1] jobs
    2016-03-11 18:33:13,831 ERROR     Connection failure.
    logging-curator run finish

This is because elasticsearch hasn't started yet::

    [2016-03-11 18:33:18,372][INFO ][node                     ] [Outrage] version[1.5.2], pid[8], build[62ff986/2015-04-27T09:21:06Z]
    [2016-03-11 18:33:18,377][INFO ][node                     ] [Outrage] initializing ...
    [2016-03-11 18:33:19,601][INFO ][plugins                  ] [Outrage] loaded [searchguard, openshift-elasticsearch-plugin, cloud-kubernetes], sites []

Is there some way we can orchestrate the pods in the deployer?

**Comment by sosiouxme** [comment]
We could. We could wait until there are endpoints on the ES service. That could take a while. Perhaps better, we could deploy everything just as we do now (so docker pulls can happen asynchronously), then wait for endpoints on the ES service, then restart the curator pod.

Fluentd has this issue too, but the deployer doesn't automatically roll out any of those.

I'm not sure we should even consider it an issue. Things are supposed to fail (and retry) when their dependencies are missing. We need to get used to that in the cloud.

**Comment by ewolinetz** [comment]
What about updating Curator to test for a connection to ES for a set amount of time before actually starting up/running its initial clean up? (Similar to how Fluentd and Kibana handle ES not being up yet).

**Comment by ewolinetz** [comment]
we now poll ES to see if it has started up before we fully start up Curator with #138
