### ISSUE TITLE
Add a fluentd_exporter 

### ISSUE THREAD

**Issue by ljuaneda** [openshift/origin-aggregated-logging#902]
Add a Prometheus exporter for Fluentd to scape metrics from the monitoring agent.
based on https://github.com/V3ckt0r/fluentd_exporter

**Comment by ljuaneda** [comment]
I've already done it through a side-container but maybe it'll be more efficient to include it directly in the fluentd-elasticsearch container.

Anyway, my Dockerfile :

```
FROM rhscl/s2i-base-rhel7:1-6.18

ENV GOLANG_VERSION 1.9.2

RUN set -eux; \
        goRelArch='linux-amd64'; \
        url="https://golang.org/dl/go${GOLANG_VERSION}.${goRelArch}.tar.gz"; \
        wget -O go.tgz "$url"; \
        tar -C /usr/local -xzf go.tgz; \
        rm go.tgz; \
        rm ${HOME}/.wgetrc; \
        \
        export PATH="/usr/local/go/bin:$PATH"; \
        go version

ENV GOROOT /usr/local/go
ENV GOPATH /go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

RUN set -eux; \
        cd $GOPATH/src; \
        git clone https://github.com/V3ckt0r/fluentd_exporter.git; \
        cd fluentd_exporter; \
        mv vendor src; \
        export GOPATH=$(pwd); \
        go build fluentd_exporter.go; \
        mv fluentd_exporter /go/bin; \
        rm -fr $GOPATH/src

EXPOSE 9309

CMD ["/go/bin/fluentd_exporter"]
```

**Comment by jcantrill** [comment]
@openshift/sig-integration-services Opinions on a side car vs https://github.com/fluent/fluent-plugin-prometheus.  I like the idea of the additional metrics provided by fluent but i have resource concerns this plugin will add given we already consume a significant amount of memory

**Comment by josefkarasek** [comment]
@jcantrill I assume the plugin is not active unless explicitly configured to do so, e.g.:
```
<source>
  @type prometheus
</source>
```
If that's the case, we can easily collect metrics in `dev/test` and disable it for `prod`

**Comment by richm** [comment]
> I assume the plugin is not active unless explicitly configured to do so
correct

There's also the problem of access - we are going to need some sort of proxy that secures access to the fluentd endpoint, perhaps the oauth-proxy.

**Comment by jcantrill** [comment]
@ewolinetz Do we have an understanding of this plugin vs the one from our original impl?

**Comment by ewolinetz** [comment]
@jcantrill it looks similar in terms of what it provides out of the box, however this appears to run in its own container vs being a part of fluentd.

The original impl also gave us the ability to also create metrics via filters, though I'm not sure if we would use that since it would be specific to applications (unless we wanted to expose that for customers)

**Comment by jcantrill** [comment]
Closing as metrics are available for fluentd
