### ISSUE TITLE
Unable to connect to elasticsearch at http://localhost:9200

### ISSUE THREAD

**Issue by ravimanupati53** [openshift/origin-aggregated-logging#957]
I am unable to connect to elasticsearch at localhost:9200 and the status of kibana went to Red. 

When I tried to look on the logging deployments it states that it was terminated with an exit code 143. 

The Metrics was totally down for all applications. 

Cassandra service is perfectly started and working fine but the server was refusing the connection.

Any solutions?

**Comment by richm** [comment]
@ravimanupati53 I don't know about metrics - if you have an issue with metrics, please file a separate issue
as far as logging - first thing will be to get the dump of the logging information - https://github.com/openshift/origin-aggregated-logging/blob/master/hack/README-dump.md and https://github.com/openshift/origin-aggregated-logging/blob/master/hack/logging-dump.sh
