### ISSUE TITLE
Deployment fails on oc process logging-fluentd-template

### ISSUE THREAD

**Issue by allen13** [openshift/origin-aggregated-logging#97]
I am running the deploy based on this pod https://gist.github.com/allen13/ad4f720dc0b94da26cc7
I followed this guide to set things up https://docs.openshift.org/latest/install_config/aggregate_logging.html

deploymentconfig "logging-es-ugoyxphc" created
+ (( n++ ))
+ (( n<1 ))
+ oc process logging-fluentd-template
+ oc create -f -
json: cannot unmarshal object into Go value of type string

**Comment by ewolinetz** [comment]
There seems to be some issues surrounding the http scheme being set when the template is created

**Comment by allen13** [comment]
I noticed that when I run oc process logging-fluentd-template locally, after the half-deploy it works. So the template itself isn't broken. Possibly the oc client or config?

**Comment by ewolinetz** [comment]
@allen13 I've noticed that as well... and even more strange is that  we don't see this issue with our CI builds, the deployer is able to complete successfully there.

**Comment by arnaudmz** [comment]
I had a quick look into it, it seems that shipped version of oc/openshift binary within openshift/origin-logging-deployment:latest image has not been updated to speak k8s 1.2.0 DaemonSet API used in Origin-1.1.4.

After bind-mounting oc binary within the container, I also had to be updated run.sh to replace `openshift admin ca` calls to `openshift adm ca.`

Seems to work.

**Comment by ewolinetz** [comment]
I have rebuilt and pushed the deployment image to dockerhub

**Comment by ewolinetz** [comment]
Please note that with the current origin image, your logging deployer will need to have the `cluster-admin` role instead of `edit` to create a daemonset.

**Comment by elyscape** [comment]
@ewolinetz Unfortunately, it doesn't have the current version of OpenShift. From a debug pod:
```shellsession
sh-4.2$ openshift version
openshift v1.1-29-gc42d958
kubernetes v1.1.0-origin-1107-g4c8e6f4
etcd 2.1.2
```

**Comment by elyscape** [comment]
It looks like the rebuild may have used an old version of the `openshift/origin:latest` image.

**Comment by ewolinetz** [comment]
the origin image on our logging build machine is out of date... I'll get that updated and will rebuild again. sorry for that.

**Comment by elyscape** [comment]
And it works now!

**Comment by ewolinetz** [comment]
Thanks for the confirmation! Closing this issue
