### ISSUE TITLE
Unable to Ingest external VM Logs to openshift cluster elasticsearch 

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#976]
I have openshift cluster setup on aws and have enabled openshift efk logging solution on top of that. I can able to see containers logs , operations logs and application/projects logs. But now 
I am trying to connect external fluentd agent which i is running on aws server which is present outside of openshift cluster, trying to ingest server logs openshift elasticsearch. But i am not able to connect. 
Please provide me expert advice on that. 
Thanks in advance.!

**Comment by richm** [comment]
@himmatb can you provide more details about what you have done?  Are you trying to send logs from outside the cluster into the internal OpenShift cluster Elasticsearch?  Or are you trying to get the internal OpenShift cluster Fluentd to send logs to another Fluentd running outside of the cluster?

**Comment by himmatb** [comment]
@richm  I am trying to sends logs from outside the cluster into internal openshift cluster elasticsearch. i have deployed EFK stack using an Ansible playbook on AWS openshift cluster environment in one of the aws region. i am able to get all the project wise logs of container's present in cluster.

I would like to ingest application logs from AWS server in another region which is present outside of cluster to internal openshift cluster elasticsearch.

Below steps i have taken to archive this : 

1. In ansible host file i have enable below flag to make to Expose Elasticsearch as a Route as per documentation :
openshift_logging_es_allow_external=True
openshift_logging_es_hostname=elasticsearch.xxxxxx.com

2. I am able access Elasticsearch through the exposed route from external VM:
curl -k -H "Authorization: Bearer xxxxxxxxxxxxx" -H "X-Proxy-Remote-User: xyz" -H "X-Forwarded-For: xxclusteripxx" https://elasticsearch.xxxxx.com

3. I have configure fluentd agent on my external VM and try to push logs using ES exposed route. but not able to connect.
Please provide me your valuable input to make this work.
Thanks in advance.

**Comment by richm** [comment]
> I have configure fluentd agent on my external VM and try to push logs using ES exposed route. but not able to connect.

How?  What exactly did you do?

**Comment by himmatb** [comment]
Below is Fluentd configuration i used to connect to internal elasticsearch cluster  : 

<source>
  @type tail
  path /var/log/httpd/access_log 
  pos_file /var/log/td-agent/httpd_access_log.pos 
  tag apache.access 
  format apache2 
</source>

<match **>
  @type elasticsearch
  logstash_format true
  include_timestamp true
  logstash_prefix apachelogs
  logstash_prefix_separator -
  logstash_dateformat %Y.%m.%d
  user admin
  password XXtokenhereXX
  hosts https://elasticsearch.XXXX.com
  ssl_verify false
  ca_file /root/keys/cert-ca.cert
  type_name vm_apache_logs #(optional; default=fluentd)
  flush_interval 60s
</match>

But i am getting below certificate error : 

2018-02-26 12:38:38 +0000 [warn]: #0 failed to flush the buffer. retry_time=1 next_retry_seconds=2018-02-26 12:38:36 +0000 chunk="5661cc61c117c5179e4d092189b0a748
" error_class=Elasticsearch::Transport::Transport::Errors::Unauthorized error="[401] "

--------------------------------------------------------------
I can share more information below about my route in openshift: 

Route >>logging-es created 3 days ago
https://elasticsearch.XXXXXXX.com
 Exposed on router 'router' 3 days ago
Details
Path:none
Service:logging-es
Target Port:any
TLS Settings
Termination Type:Re-encrypt
Insecure Traffic:None
Certificate:none
Key:none
CA Certificate: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Destination CA Cert: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
above two ca certificates are available in route configuration.

Let me now any other details require .
Please help me on this. i really wanted to complete this . i am not understanding me whether i have taken right way to connect or not . Please guide me with other approach if any or if i am doing wrong .

**Comment by richm** [comment]
Fluentd cannot do token auth.  You have this:
```
user admin
password XXtokenhereXX
```
This will do _password_ auth using the token as the password.  This is very different from _token_ auth, in which the token is sent as the `Authorization: Bearer $tokenvalue` HTTP header.

The only way this is currently supported is to configure the Elasticsearch service to use an externalIP, and use the internal cluster fluentd cert and key to do client cert auth.

See https://github.com/ViaQ/Main/blob/master/README-install.md#enabling-external-fluentd-access
and you'll need to export the fluentd client cert and key from the logging-fluentd secret to your external fluentd machine.
